import type { PrismaClient, LoadStatus } from '@prisma/client';
import type { PrismaTransaction } from '@/config/database';
import type { LoadStatusRepoPort } from '../types/loadStatusTypes';

const LOAD_DETAIL_INCLUDE = {
  stops: {
    orderBy: { sequence: 'asc' as const },
  },
  carrier: true,
  driver: true,
  vehicle: true,
  broker: true,
  shipper: true,
  consignee: true,
  statusHistory: {
    orderBy: { createdAt: 'desc' as const },
  },
  checkCalls: {
    orderBy: { createdAt: 'desc' as const },
  },
  accessorialCharges: {
    orderBy: { createdAt: 'asc' as const },
  },
} as const;

export const loadStatusRepositoryPrisma = (
  prisma: PrismaClient | PrismaTransaction,
): LoadStatusRepoPort => ({
  updateStatus: async (loadId: string, status: LoadStatus) =>
    prisma.load.update({
      where: { id: loadId },
      data: { status },
      include: LOAD_DETAIL_INCLUDE,
    }),

  createStatusHistory: async (data) => {
    await prisma.loadStatusHistory.create({
      data: {
        loadId: data.loadId,
        fromStatus: data.fromStatus,
        toStatus: data.toStatus,
        changedByUserId: data.changedByUserId,
        notes: data.notes,
      },
    });
  },

  createAccessorialCharge: async (data) => {
    await prisma.accessorialCharge.create({
      data: {
        loadId: data.loadId,
        type: data.type,
        description: data.description,
        amount: data.amount,
        billTo: data.billTo,
        isAutoGenerated: data.isAutoGenerated,
      },
    });
  },
});
