import type { PrismaClient, LoadStatus } from '@prisma/client';
import type { PrismaTransaction } from '@/config/database';
import type { LoadStatusRepoPort } from '../types/loadStatusTypes';

const LOAD_DETAIL_INCLUDE = {
  stops: {
    orderBy: { sequence: 'asc' as const },
  },
  carrier: true,
  driver: true,
  vehicle: true,
  contact: true,
  customer: true,
  statusHistory: {
    orderBy: { createdAt: 'desc' as const },
    include: { changedBy: true },
  },
  checkCalls: {
    orderBy: { createdAt: 'desc' as const },
  },
  accessorialCharges: {
    orderBy: { createdAt: 'asc' as const },
  },
} as const;

export const loadStatusRepositoryPrisma = (
  prisma: PrismaClient | PrismaTransaction,
): LoadStatusRepoPort => ({
  updateStatus: async (loadId: string, status: LoadStatus) =>
    prisma.load.update({
      where: { id: loadId },
      data: { status },
      include: LOAD_DETAIL_INCLUDE,
    }),

  createStatusHistory: async (data) => {
    await prisma.loadStatusHistory.create({
      data: {
        loadId: data.loadId,
        fromStatus: data.fromStatus,
        toStatus: data.toStatus,
        changedByUserId: data.changedByUserId,
        notes: data.notes,
      },
    });
  },

  createAccessorialCharge: async (data) => {
    await prisma.accessorialCharge.create({
      data: {
        loadId: data.loadId,
        type: data.type,
        description: data.description,
        amount: data.amount,
        billTo: data.billTo,
        isAutoGenerated: data.isAutoGenerated,
      },
    });
  },

  sumAccessorialCharges: async (loadId: string) => {
    const result = await prisma.accessorialCharge.aggregate({
      where: { loadId },
      _sum: { amount: true },
    });
    return (result._sum.amount ?? 0).toString();
  },

  updateFinancials: async (loadId, financials) => {
    await prisma.load.update({
      where: { id: loadId },
      data: {
        dispatchFee: financials.dispatchFee,
        partnerSplit: financials.partnerSplit,
        ratePerMile: financials.ratePerMile,
      },
    });
  },
});
