import type { PrismaClient } from '@prisma/client';
import type { PrismaTransaction } from '@/config/database';
import type {
  LoadRepoPort,
  LoadQueryInput,
  OrgSettingsQueryPort,
} from '../types/loadTypes';

const LOAD_DETAIL_INCLUDE = {
  stops: {
    orderBy: { sequence: 'asc' as const },
  },
  carrier: true,
  driver: true,
  vehicle: true,
  broker: true,
  shipper: true,
  consignee: true,
  statusHistory: {
    orderBy: { createdAt: 'desc' as const },
  },
  checkCalls: {
    orderBy: { createdAt: 'desc' as const },
  },
  accessorialCharges: {
    orderBy: { createdAt: 'asc' as const },
  },
} as const;

const LOAD_LIST_INCLUDE = {
  stops: {
    orderBy: { sequence: 'asc' as const },
  },
  carrier: {
    select: { id: true, name: true },
  },
  driver: {
    select: { id: true, firstName: true, lastName: true },
  },
  _count: {
    select: { accessorialCharges: true },
  },
} as const;

const buildListWhere = (
  organizationId: string,
  filters: LoadQueryInput['filters'],
) => {
  const where: Record<string, unknown> = {
    organizationId,
    deletedAt: null,
  };

  if (filters.status !== undefined && filters.status.length > 0) {
    where['status'] = { in: filters.status };
  }

  if (filters.carrierId !== undefined) {
    where['carrierId'] = filters.carrierId;
  }

  if (filters.equipmentType !== undefined) {
    where['equipmentType'] = filters.equipmentType;
  }

  if (filters.dateFrom !== undefined || filters.dateTo !== undefined) {
    const createdAt: Record<string, Date> = {};
    if (filters.dateFrom !== undefined) {
      createdAt['gte'] = filters.dateFrom;
    }
    if (filters.dateTo !== undefined) {
      createdAt['lte'] = filters.dateTo;
    }
    where['createdAt'] = createdAt;
  }

  if (filters.search !== undefined && filters.search.length > 0) {
    where['OR'] = [
      { loadNumber: { contains: filters.search, mode: 'insensitive' } },
      { brokerRefNumber: { contains: filters.search, mode: 'insensitive' } },
      { carrier: { name: { contains: filters.search, mode: 'insensitive' } } },
      { stops: { some: { city: { contains: filters.search, mode: 'insensitive' } } } },
    ];
  }

  return where;
};

export const loadRepositoryPrisma = (
  prisma: PrismaClient | PrismaTransaction,
): LoadRepoPort => ({
  create: async (organizationId, loadNumber, input) => {
    const { stops, accessorialCharges, ...loadData } = input;

    return prisma.load.create({
      data: {
        organizationId,
        loadNumber,
        ...loadData,
        stops: {
          create: stops.map((stop) => ({
            type: stop.type,
            sequence: stop.sequence,
            contactId: stop.contactId,
            placeId: stop.placeId,
            facilityName: stop.facilityName,
            address: stop.address,
            city: stop.city,
            state: stop.state,
            zip: stop.zip,
            appointmentDate: stop.appointmentDate,
            appointmentTime: stop.appointmentTime,
            appointmentNumber: stop.appointmentNumber,
            contactName: stop.contactName,
            contactPhone: stop.contactPhone,
            notes: stop.notes,
          })),
        },
        ...(accessorialCharges !== undefined && accessorialCharges.length > 0
          ? {
              accessorialCharges: {
                create: accessorialCharges.map((charge) => ({
                  type: charge.type,
                  description: charge.description,
                  amount: charge.amount,
                  billTo: charge.billTo ?? 'customer',
                  isAutoGenerated: charge.isAutoGenerated ?? false,
                })),
              },
            }
          : {}),
        statusHistory: {
          create: {
            fromStatus: null,
            toStatus: input.status ?? 'QUOTED',
            notes: 'Load created',
          },
        },
      },
      include: LOAD_DETAIL_INCLUDE,
    });
  },

  findById: (id, organizationId) =>
    prisma.load.findFirst({
      where: {
        id,
        organizationId,
        deletedAt: null,
      },
      include: LOAD_DETAIL_INCLUDE,
    }),

  list: ({ organizationId, filters, skip, take, orderBy }) =>
    prisma.load.findMany({
      where: buildListWhere(organizationId, filters),
      skip,
      take,
      orderBy,
      include: LOAD_LIST_INCLUDE,
    }),

  count: ({ organizationId, filters }) =>
    prisma.load.count({
      where: buildListWhere(organizationId, filters),
    }),

  update: async (id, input) => {
    const { stops, accessorialCharges, ...loadData } = input;

    // If accessorialCharges are provided, atomically replace them
    if (accessorialCharges !== undefined) {
      await prisma.accessorialCharge.deleteMany({ where: { loadId: id } });
    }

    // If stops are provided, replace them atomically
    if (stops !== undefined) {
      await prisma.stop.deleteMany({ where: { loadId: id } });
    }

    return prisma.load.update({
      where: { id },
      data: {
        ...loadData,
        ...(stops !== undefined
          ? {
              stops: {
                create: stops.map((stop) => ({
                  type: stop.type,
                  sequence: stop.sequence,
                  contactId: stop.contactId,
                  placeId: stop.placeId,
                  facilityName: stop.facilityName,
                  address: stop.address,
                  city: stop.city,
                  state: stop.state,
                  zip: stop.zip,
                  appointmentDate: stop.appointmentDate,
                  appointmentTime: stop.appointmentTime,
                  appointmentNumber: stop.appointmentNumber,
                  contactName: stop.contactName,
                  contactPhone: stop.contactPhone,
                  notes: stop.notes,
                })),
              },
            }
          : {}),
        ...(accessorialCharges !== undefined
          ? {
              accessorialCharges: {
                create: accessorialCharges.map((charge) => ({
                  type: charge.type,
                  description: charge.description,
                  amount: charge.amount,
                  billTo: charge.billTo ?? 'customer',
                  isAutoGenerated: charge.isAutoGenerated ?? false,
                })),
              },
            }
          : {}),
      },
      include: LOAD_DETAIL_INCLUDE,
    });
  },

  softDelete: async (id, deletedAt) => {
    await prisma.load.update({
      where: { id },
      data: { deletedAt },
    });
  },

  createCheckCall: async (loadId, calledByUserId, input) => {
    return prisma.checkCall.create({
      data: {
        loadId,
        calledByUserId,
        location: input.location,
        latitude: input.latitude,
        longitude: input.longitude,
        status: input.status,
        eta: input.eta,
        notes: input.notes,
        brokerNotified: input.brokerNotified,
        brokerNotes: input.brokerNotes,
      },
      include: {
        calledBy: {
          select: { id: true, firstName: true, lastName: true },
        },
      },
    });
  },

  listCheckCalls: async (loadId) => {
    return prisma.checkCall.findMany({
      where: { loadId },
      orderBy: { createdAt: 'desc' },
      include: {
        calledBy: {
          select: { id: true, firstName: true, lastName: true },
        },
      },
    });
  },

  listStatusHistory: async (loadId) => {
    return prisma.loadStatusHistory.findMany({
      where: { loadId },
      orderBy: { createdAt: 'desc' },
      include: {
        changedBy: {
          select: { id: true, firstName: true, lastName: true },
        },
      },
    });
  },

  listDocuments: async (loadId, organizationId) => {
    return prisma.document.findMany({
      where: {
        loadId,
        organizationId,
        isArchived: false,
      },
      orderBy: { createdAt: 'desc' },
      select: {
        id: true,
        organizationId: true,
        loadId: true,
        type: true,
        fileName: true,
        fileSize: true,
        mimeType: true,
        uploadStatus: true,
        notes: true,
        createdAt: true,
      },
    });
  },
});

export const orgSettingsQueryPrisma = (
  prisma: PrismaClient | PrismaTransaction,
): OrgSettingsQueryPort => ({
  getProhibitedCommodities: async (organizationId) => {
    const settings = await prisma.orgSettings.findUnique({
      where: { organizationId },
      select: { prohibitedCommodities: true },
    });

    return settings?.prohibitedCommodities ?? [];
  },
});
