import type { PrismaClient, LoadStatus } from '@prisma/client';
import { Prisma } from '@prisma/client';
import type { PrismaTransaction } from '@/config/database';
import { ConflictError } from '@/shared/errors';
import type { LoadStatusRepoPort } from '../types/loadStatusTypes';

const LOAD_DETAIL_INCLUDE = {
  stops: {
    orderBy: { sequence: 'asc' as const },
    include: {
      place: {
        select: { latitude: true, longitude: true },
      },
    },
  },
  carrier: true,
  driver: true,
  vehicle: true,
  contact: true,
  customer: true,
  statusHistory: {
    orderBy: { createdAt: 'desc' as const },
    include: { changedBy: { select: { id: true, firstName: true, lastName: true } } },
  },
  checkCalls: {
    orderBy: { createdAt: 'desc' as const },
    include: { calledBy: { select: { id: true, firstName: true, lastName: true } } },
  },
  accessorialCharges: {
    orderBy: { createdAt: 'asc' as const },
  },
} as const;

export const loadStatusRepositoryPrisma = (
  prisma: PrismaClient | PrismaTransaction,
): LoadStatusRepoPort => ({
  updateStatus: async (loadId: string, status: LoadStatus, expectedVersion?: number) => {
    try {
      const where = expectedVersion !== undefined
        ? { id: loadId, version: expectedVersion }
        : { id: loadId };

      return await prisma.load.update({
        where,
        data: { status, version: { increment: 1 } },
        include: LOAD_DETAIL_INCLUDE,
      });
    } catch (error: unknown) {
      if (
        error instanceof Prisma.PrismaClientKnownRequestError &&
        error.code === 'P2025'
      ) {
        throw new ConflictError(
          'Load was modified by another user. Please refresh and try again.',
        );
      }
      throw error;
    }
  },

  createStatusHistory: async (data) => {
    await prisma.loadStatusHistory.create({
      data: {
        loadId: data.loadId,
        fromStatus: data.fromStatus,
        toStatus: data.toStatus,
        changedByUserId: data.changedByUserId,
        notes: data.notes,
      },
    });
  },

  createAccessorialCharge: async (data) => {
    await prisma.accessorialCharge.create({
      data: {
        loadId: data.loadId,
        type: data.type,
        description: data.description,
        amount: data.amount,
        billTo: data.billTo,
        isAutoGenerated: data.isAutoGenerated,
        ...(data.stopId !== undefined && { stopId: data.stopId }),
      },
    });
  },

  sumAccessorialCharges: async (loadId: string) => {
    const result = await prisma.accessorialCharge.aggregate({
      where: { loadId },
      _sum: { amount: true },
    });
    return (result._sum.amount ?? 0).toString();
  },

});
