import { describe, expect, it } from '@jest/globals';
import { checkDetentionForStop } from '../detentionDetector';

describe('checkDetentionForStop', () => {
  const baseStop = {
    id: 'stop-1',
    type: 'PICKUP' as const,
    sequence: 1,
    facilityName: 'ABC Warehouse',
    city: 'Dallas',
    state: 'TX',
    arrivalTime: new Date('2026-04-10T08:00:00Z'),
    departureTime: new Date('2026-04-10T12:30:00Z'), // 4.5hr wait
  };

  it('detects detention when wait exceeds free hours', () => {
    const result = checkDetentionForStop(baseStop, 2, 75, []);
    expect(result.detected).toBe(true);
    if (result.detected) {
      expect(result.billableHours).toBe(3); // ceil(4.5 - 2) = 3
      expect(result.amount).toBe(225); // 3 * 75
    }
  });

  it('rounds up to full hour', () => {
    const stop = { ...baseStop, departureTime: new Date('2026-04-10T10:10:00Z') }; // 2hr 10min
    const result = checkDetentionForStop(stop, 2, 75, []);
    expect(result.detected).toBe(true);
    if (result.detected) {
      expect(result.billableHours).toBe(1); // ceil(2.167 - 2) = 1
      expect(result.amount).toBe(75);
    }
  });

  it('returns not detected when wait <= free hours', () => {
    const stop = { ...baseStop, departureTime: new Date('2026-04-10T09:30:00Z') }; // 1.5hr
    const result = checkDetentionForStop(stop, 2, 75, []);
    expect(result.detected).toBe(false);
  });

  it('returns not detected for DROP_HOOK stops', () => {
    const stop = { ...baseStop, type: 'DROP_HOOK' as const };
    const result = checkDetentionForStop(stop, 2, 75, []);
    expect(result.detected).toBe(false);
  });

  it('returns not detected when arrivalTime is null', () => {
    const stop = { ...baseStop, arrivalTime: null };
    const result = checkDetentionForStop(stop, 2, 75, []);
    expect(result.detected).toBe(false);
  });

  it('returns not detected when departureTime is null', () => {
    const stop = { ...baseStop, departureTime: null };
    const result = checkDetentionForStop(stop, 2, 75, []);
    expect(result.detected).toBe(false);
  });

  it('returns not detected when duplicate charge exists', () => {
    const existingCharges = [
      { stopId: 'stop-1', type: 'DETENTION' as const, isAutoGenerated: true },
    ];
    const result = checkDetentionForStop(baseStop, 2, 75, existingCharges);
    expect(result.detected).toBe(false);
  });

  it('detects when existing charge is for a different stop', () => {
    const existingCharges = [
      { stopId: 'stop-other', type: 'DETENTION' as const, isAutoGenerated: true },
    ];
    const result = checkDetentionForStop(baseStop, 2, 75, existingCharges);
    expect(result.detected).toBe(true);
  });

  it('detects when existing charge is not auto-generated', () => {
    const existingCharges = [
      { stopId: 'stop-1', type: 'DETENTION' as const, isAutoGenerated: false },
    ];
    const result = checkDetentionForStop(baseStop, 2, 75, existingCharges);
    expect(result.detected).toBe(true);
  });

  it('description includes facility name', () => {
    const result = checkDetentionForStop(baseStop, 2, 75, []);
    expect(result.detected).toBe(true);
    if (result.detected) {
      expect(result.description).toContain('ABC Warehouse');
    }
  });

  it('description falls back to city/state when no facility name', () => {
    const stop = { ...baseStop, facilityName: null };
    const result = checkDetentionForStop(stop, 2, 75, []);
    expect(result.detected).toBe(true);
    if (result.detected) {
      expect(result.description).toContain('Dallas, TX');
    }
  });
});
