import { AccessorialType, EquipmentType, LoadStatus, StopType } from '@prisma/client';
import * as Yup from 'yup';

const equipmentTypeValues = Object.values(EquipmentType);
const loadStatusValues = Object.values(LoadStatus);
const stopTypeValues = Object.values(StopType);
const accessorialTypeValues = Object.values(AccessorialType);

const optionalTrimmed = Yup.string().trim().notRequired();

const stopSchema = Yup.object({
  type: Yup.mixed<StopType>()
    .oneOf(stopTypeValues, 'type must be a valid StopType')
    .required('stop type is required'),
  sequence: Yup.number().integer().min(0).required('stop sequence is required'),
  contactId: Yup.string().uuid().notRequired(),
  placeId: Yup.string().uuid().notRequired(),
  facilityName: optionalTrimmed,
  address: optionalTrimmed,
  city: optionalTrimmed,
  state: optionalTrimmed,
  zip: optionalTrimmed,
  appointmentDate: Yup.date().notRequired(),
  appointmentTime: optionalTrimmed,
  appointmentNumber: optionalTrimmed,
  contactName: optionalTrimmed,
  contactPhone: optionalTrimmed,
  notes: optionalTrimmed,
});

const accessorialChargeSchema = Yup.object({
  type: Yup.mixed<AccessorialType>()
    .oneOf(accessorialTypeValues, 'type must be a valid AccessorialType')
    .required('accessorial type is required'),
  description: optionalTrimmed,
  amount: Yup.number().min(0, 'amount must be non-negative').required('amount is required'),
  billTo: Yup.string().oneOf(['customer', 'carrier']).notRequired(),
  isAutoGenerated: Yup.boolean().notRequired(),
});

const createBodySchema = Yup.object({
  carrierId: Yup.string().uuid().notRequired(),
  driverId: Yup.string().uuid().notRequired(),
  vehicleId: Yup.string().uuid().notRequired(),
  brokerId: Yup.string().uuid().notRequired(),
  shipperId: Yup.string().uuid().notRequired(),
  consigneeId: Yup.string().uuid().notRequired(),
  brokerRefNumber: optionalTrimmed,
  equipmentType: Yup.mixed<EquipmentType>()
    .oneOf(equipmentTypeValues, 'equipmentType must be a valid EquipmentType')
    .notRequired(),
  isHazmat: Yup.boolean().notRequired(),
  isTarp: Yup.boolean().notRequired(),
  isTeamDriver: Yup.boolean().notRequired(),
  commodity: optionalTrimmed,
  weight: Yup.number().integer().min(0).notRequired(),
  pieceCount: Yup.number().integer().min(0).notRequired(),
  loadedMiles: Yup.number().integer().min(0).notRequired(),
  deadheadMiles: Yup.number().integer().min(0).notRequired(),
  totalMiles: Yup.number().integer().min(0).notRequired(),
  customerRate: Yup.number().min(0).notRequired(),
  carrierRate: Yup.number().min(0).notRequired(),
  dispatchFee: Yup.number().min(0).notRequired(),
  partnerSplit: Yup.number().min(0).notRequired(),
  ratePerMile: Yup.number().min(0).notRequired(),
  status: Yup.mixed<LoadStatus>()
    .oneOf(loadStatusValues, 'status must be a valid LoadStatus')
    .notRequired(),
  rateConReceivedAt: Yup.date().notRequired(),
  bolUnsignedAt: Yup.date().notRequired(),
  bolSignedAt: Yup.date().notRequired(),
  dispatcherNotes: optionalTrimmed,
  driverInstructions: optionalTrimmed,
  stops: Yup.array()
    .of(stopSchema)
    .min(1, 'At least one stop is required')
    .required('stops are required'),
  accessorialCharges: Yup.array().of(accessorialChargeSchema).notRequired(),
});

const updateBodySchema = Yup.object({
  carrierId: Yup.string().uuid().notRequired(),
  driverId: Yup.string().uuid().notRequired(),
  vehicleId: Yup.string().uuid().notRequired(),
  brokerId: Yup.string().uuid().notRequired(),
  shipperId: Yup.string().uuid().notRequired(),
  consigneeId: Yup.string().uuid().notRequired(),
  brokerRefNumber: optionalTrimmed,
  equipmentType: Yup.mixed<EquipmentType>()
    .oneOf(equipmentTypeValues, 'equipmentType must be a valid EquipmentType')
    .notRequired(),
  isHazmat: Yup.boolean().notRequired(),
  isTarp: Yup.boolean().notRequired(),
  isTeamDriver: Yup.boolean().notRequired(),
  commodity: optionalTrimmed,
  weight: Yup.number().integer().min(0).notRequired(),
  pieceCount: Yup.number().integer().min(0).notRequired(),
  loadedMiles: Yup.number().integer().min(0).notRequired(),
  deadheadMiles: Yup.number().integer().min(0).notRequired(),
  totalMiles: Yup.number().integer().min(0).notRequired(),
  customerRate: Yup.number().min(0).notRequired(),
  carrierRate: Yup.number().min(0).notRequired(),
  dispatchFee: Yup.number().min(0).notRequired(),
  partnerSplit: Yup.number().min(0).notRequired(),
  ratePerMile: Yup.number().min(0).notRequired(),
  status: Yup.mixed<LoadStatus>()
    .oneOf(loadStatusValues, 'status must be a valid LoadStatus')
    .notRequired(),
  rateConReceivedAt: Yup.date().notRequired(),
  bolUnsignedAt: Yup.date().notRequired(),
  bolSignedAt: Yup.date().notRequired(),
  dispatcherNotes: optionalTrimmed,
  driverInstructions: optionalTrimmed,
  stops: Yup.array().of(stopSchema).min(1, 'At least one stop is required').notRequired(),
  accessorialCharges: Yup.array().of(accessorialChargeSchema).notRequired(),
}).test('has-any-field', 'At least one field must be provided', (value) => {
  if (value === undefined) {
    return false;
  }
  return Object.keys(value).length > 0;
});

export const createLoadValidator = Yup.object({
  body: createBodySchema,
});

export const updateLoadValidator = Yup.object({
  body: updateBodySchema,
  params: Yup.object({
    id: Yup.string().uuid('id must be a valid uuid').required('id is required'),
  }),
});

export const listLoadsValidator = Yup.object({
  query: Yup.object({
    page: Yup.number().integer().min(1).notRequired(),
    limit: Yup.number().integer().min(1).max(100).notRequired(),
    sort: Yup.string().trim().notRequired(),
    order: Yup.string().oneOf(['asc', 'desc']).notRequired(),
    status: Yup.string().trim().notRequired(),
    carrierId: Yup.string().uuid().notRequired(),
    equipmentType: Yup.mixed<EquipmentType>().oneOf(equipmentTypeValues).notRequired(),
    search: Yup.string().trim().notRequired(),
    dateFrom: Yup.date().notRequired(),
    dateTo: Yup.date().notRequired(),
  }),
});

export const loadIdParamValidator = Yup.object({
  params: Yup.object({
    id: Yup.string().uuid('id must be a valid uuid').required('id is required'),
  }),
});

export const transitionStatusValidator = Yup.object({
  params: Yup.object({
    id: Yup.string().uuid('id must be a valid uuid').required('id is required'),
  }),
  body: Yup.object({
    status: Yup.mixed<LoadStatus>()
      .oneOf(loadStatusValues, 'status must be a valid LoadStatus')
      .required('status is required'),
    notes: Yup.string().trim().notRequired(),
    overrideWarnings: Yup.boolean().notRequired(),
  }),
});

export const createCheckCallValidator = Yup.object({
  params: Yup.object({
    id: Yup.string().uuid('id must be a valid uuid').required('id is required'),
  }),
  body: Yup.object({
    location: optionalTrimmed,
    latitude: Yup.number().min(-90).max(90).notRequired(),
    longitude: Yup.number().min(-180).max(180).notRequired(),
    status: optionalTrimmed,
    eta: Yup.date().notRequired(),
    notes: optionalTrimmed,
    brokerNotified: Yup.boolean().required('brokerNotified is required'),
    brokerNotes: optionalTrimmed,
  }),
});
