import type { DocumentType } from 'features/documents/types';

// Derived from loads API contract (openapi spec + API transformers)
// Decimal fields are represented as string (API serializes Decimal as string/unknown)

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export type LoadStatus =
  | 'QUOTED'
  | 'BOOKED'
  | 'DISPATCHED'
  | 'EN_ROUTE_PICKUP'
  | 'AT_PICKUP'
  | 'IN_TRANSIT'
  | 'AT_DELIVERY'
  | 'DELIVERED'
  | 'INVOICE_PENDING'
  | 'INVOICED'
  | 'PAID'
  | 'EXCEPTION'
  | 'CANCELED'
  | 'TONU';

export type EquipmentType =
  | 'DRY_VAN'
  | 'REEFER'
  | 'FLATBED'
  | 'STEP_DECK'
  | 'BOX_TRUCK'
  | 'HOTSHOT'
  | 'POWER_ONLY';

export type StopType = 'PICKUP' | 'DELIVERY' | 'STOP_OFF' | 'DROP_HOOK' | 'LIVE_UNLOAD';

export type BoardView = 'kanban' | 'table' | 'map' | 'driver' | 'intel';

export type KanbanGroup = 'NEW' | 'BOOKED' | 'ACTIVE' | 'DELIVERED' | 'COMPLETE' | 'ISSUES';

// ---------------------------------------------------------------------------
// Stop
// ---------------------------------------------------------------------------

export interface Stop {
  id: string;
  type: StopType;
  sequence: number;
  contactId: string | null;
  placeId: string | null;
  facilityName: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  appointmentDate: string | null;
  appointmentTime: string | null;
  appointmentNumber: string | null;
  arrivalTime: string | null;
  departureTime: string | null;
  contactName: string | null;
  contactPhone: string | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface StopInput {
  type: StopType;
  sequence: number;
  contactId?: string;
  placeId?: string;
  facilityName?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  appointmentDate?: string;
  appointmentTime?: string;
  appointmentNumber?: string;
  contactName?: string;
  contactPhone?: string;
  notes?: string;
}

// ---------------------------------------------------------------------------
// Accessorial charges
// ---------------------------------------------------------------------------

export type AccessorialType = 'DETENTION' | 'LAYOVER' | 'LUMPER' | 'TARP' | 'TONU' | 'OTHER';

export interface AccessorialCharge {
  id: string;
  type: string;
  description: string | null;
  amount: string;
  billTo: string;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface AccessorialChargeInput {
  type: AccessorialType;
  description?: string;
  amount: number | string;
  billTo?: string;
  isAutoGenerated?: boolean;
}

// ---------------------------------------------------------------------------
// Load list item (flattened for table/kanban display)
// ---------------------------------------------------------------------------

export interface LoadListItem {
  id: string;
  loadNumber: string;
  status: LoadStatus;
  equipmentType: string | null;
  commodity: string | null;
  customerRate: string | null;
  carrierRate: string | null;
  totalMiles: number | null;
  ratePerMile: string | null;
  carrierId: string | null;
  carrierName: string | null;
  driverId: string | null;
  driverName: string | null;
  originCity: string | null;
  originState: string | null;
  destinationCity: string | null;
  destinationState: string | null;
  customerName: string | null;
  contactName: string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  invoiceReadiness: string;
  accessorialChargeCount: number;
  createdAt: string;
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// Load detail (full entity with relations)
// ---------------------------------------------------------------------------

export interface LoadDetail {
  id: string;
  organizationId: string;
  loadNumber: string;
  carrierId: string | null;
  driverId: string | null;
  vehicleId: string | null;
  contactId: string | null;
  customerId: string | null;
  customer: { id: string; companyName: string } | null;
  externalRefNumber: string | null;
  equipmentType: string | null;
  isHazmat: boolean;
  isTarp: boolean;
  isTeamDriver: boolean;
  commodity: string | null;
  weight: number | null;
  pieceCount: number | null;
  loadedMiles: number | null;
  deadheadMiles: number | null;
  totalMiles: number | null;
  customerRate: string | null;
  carrierRate: string | null;
  dispatchFee: string | null;
  partnerSplit: string | null;
  ratePerMile: string | null;
  status: LoadStatus;
  invoiceReadiness: string;
  rateConReceivedAt: string | null;
  bolUnsignedAt: string | null;
  bolSignedAt: string | null;
  dispatcherNotes: string | null;
  driverInstructions: string | null;
  createdAt: string;
  updatedAt: string;
  stops: Stop[];
  carrier: { id: string; name: string } | null;
  driver: { id: string; firstName: string; lastName: string } | null;
  vehicle: { id: string; unitNumber: string; type: string } | null;
  contact: {
    id: string;
    firstName: string;
    lastName: string;
    phone: string | null;
    email: string | null;
    role: string | null;
  } | null;
  statusHistory: StatusHistoryEntry[];
  checkCalls: CheckCallSummary[];
  accessorialCharges: AccessorialCharge[];
}

// ---------------------------------------------------------------------------
// Create / Update inputs (frontend -> API)
// ---------------------------------------------------------------------------

export interface CreateLoadInput {
  carrierId?: string;
  driverId?: string;
  vehicleId?: string;
  contactId?: string;
  customerId?: string;
  externalRefNumber?: string;
  equipmentType?: EquipmentType;
  isHazmat?: boolean;
  isTarp?: boolean;
  isTeamDriver?: boolean;
  commodity?: string;
  weight?: number;
  pieceCount?: number;
  loadedMiles?: number;
  deadheadMiles?: number;
  totalMiles?: number;
  customerRate?: number | string;
  carrierRate?: number | string;
  dispatchFee?: number | string;
  partnerSplit?: number | string;
  ratePerMile?: number | string;
  status?: LoadStatus;
  dispatcherNotes?: string;
  driverInstructions?: string;
  stops: StopInput[];
  accessorialCharges?: AccessorialChargeInput[];
}

export interface UpdateLoadInput {
  carrierId?: string;
  driverId?: string;
  vehicleId?: string;
  contactId?: string;
  customerId?: string;
  externalRefNumber?: string;
  equipmentType?: EquipmentType;
  isHazmat?: boolean;
  isTarp?: boolean;
  isTeamDriver?: boolean;
  commodity?: string;
  weight?: number;
  pieceCount?: number;
  loadedMiles?: number;
  deadheadMiles?: number;
  totalMiles?: number;
  customerRate?: number | string;
  carrierRate?: number | string;
  dispatchFee?: number | string;
  partnerSplit?: number | string;
  ratePerMile?: number | string;
  status?: LoadStatus;
  dispatcherNotes?: string;
  driverInstructions?: string;
  stops?: StopInput[];
  accessorialCharges?: AccessorialChargeInput[];
}

// ---------------------------------------------------------------------------
// Filters
// ---------------------------------------------------------------------------

export interface LoadFilters {
  status?: LoadStatus[];
  carrierId?: string;
  carrierName?: string;
  equipmentType?: EquipmentType;
  search?: string;
  dateFrom?: string;
  dateTo?: string;
}

// ---------------------------------------------------------------------------
// Check calls
// ---------------------------------------------------------------------------

export interface CheckCallSummary {
  id: string;
  location: string | null;
  status: string | null;
  eta: string | null;
  notes: string | null;
  createdAt: string;
}

export interface CheckCall {
  id: string;
  loadId: string;
  calledByUserId: string | null;
  calledByName: string | null;
  location: string | null;
  latitude: string | null;
  longitude: string | null;
  status: string | null;
  eta: string | null;
  brokerNotified: boolean;
  brokerNotes: string | null;
  notes: string | null;
  createdAt: string;
}

export interface CreateCheckCallInput {
  location?: string;
  latitude?: number;
  longitude?: number;
  status?: string;
  eta?: string;
  notes?: string;
  brokerNotified: boolean;
  brokerNotes?: string;
}

// ---------------------------------------------------------------------------
// Type guard — distinguishes LoadDetail from LoadListItem in the shared entity adapter
// ---------------------------------------------------------------------------

export const isLoadDetail = (
  entity: LoadListItem | LoadDetail,
): entity is LoadDetail => Array.isArray((entity as LoadDetail).stops);

// ---------------------------------------------------------------------------
// Formatted load summary (pre-computed display values for LoadSummaryBar)
// ---------------------------------------------------------------------------

export interface SummaryStopInfo {
  facilityName: string;
  address: string;
  schedule: string;
  cityState: string;
  dateTime: string;
  isCompleted: boolean;
}

export interface FormattedLoadSummary {
  pickup: SummaryStopInfo;
  delivery: SummaryStopInfo;
  load: {
    routeLabel: string;
    miles: string;
    cargo: string;
    rate: string;
    ratePerMile: string;
  };
  driver: {
    name: string;
    carrier: string;
    vehicle: string;
    equipment: string;
  };
}

export interface FormattedLoadDetail extends LoadDetail {
  summary: FormattedLoadSummary;
}

// ---------------------------------------------------------------------------
// Status history
// ---------------------------------------------------------------------------

export interface StatusHistoryEntry {
  id: string;
  loadId: string;
  fromStatus: string | null;
  toStatus: string;
  changedByUserId: string | null;
  changedByName: string | null;
  notes: string | null;
  createdAt: string;
}

// ---------------------------------------------------------------------------
// Status transition
// ---------------------------------------------------------------------------

export interface TransitionStatusInput {
  status: LoadStatus;
  notes?: string;
  overrideWarnings?: boolean;
}

export interface StatusTransitionWarning {
  code: string;
  message: string;
  detail?: string;
}

export interface StatusTransitionError {
  code: string;
  message: string;
}

export interface StatusTransitionResponse {
  success: boolean;
  load?: LoadDetail;
  warnings?: StatusTransitionWarning[];
  error?: StatusTransitionError;
}

// ---------------------------------------------------------------------------
// Create Load — modal and sidebar types
// ---------------------------------------------------------------------------

export interface LoadTemplate {
  key: string;
  label: string;
  description: string;
  placeIds: string[];
  rate?: number;
  brokerRef?: string;
}

export interface SelectedDriverInfo {
  id: string;
  name: string;
  type: 'owner_operator' | 'company';
  minRpm?: number;
  mpg?: number;
  cpm?: number;
  minEarnings?: number;
}

export interface CommoditySummary {
  id: string;
  stopIndex: number;
  description: string;
  weight: string;
}

export interface IntelPrefill {
  originCity?: string;
  originState?: string;
  destinationCity?: string;
  destinationState?: string;
  rate?: number | null;
  miles?: number | null;
  equipmentType?: string;
  brokerName?: string | null;
  pickupDate?: string | null;
  minBookRate?: number | null;
}

// ---------------------------------------------------------------------------
// Create Load — queued document (collected before entity exists)
// ---------------------------------------------------------------------------

export interface QueuedDocument {
  clientId: string;
  file: File;
  documentType: DocumentType;
}

// ---------------------------------------------------------------------------
// Notification types
// ---------------------------------------------------------------------------

export interface NotificationOverride {
  id: string;
  loadId: string;
  trigger: string;
  channel: string;
  enabled: boolean;
  recipientEmail: string | null;
  recipientPhone: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface NotificationLogEntry {
  id: string;
  loadId: string;
  trigger: string;
  channel: string;
  recipientEmail: string | null;
  recipientPhone: string | null;
  subject: string | null;
  status: string;
  errorMessage: string | null;
  createdAt: string;
}

// ---------------------------------------------------------------------------
// Intel pre-fill
// ---------------------------------------------------------------------------

export interface IntelLocationState {
  intelPrefill?: IntelPrefill;
  intelLoadId?: string;
  backhaulData?: {
    route: string;
    rate: number | null;
    brokerName: string | null;
    pickupDate: string | null;
  };
}

// ---------------------------------------------------------------------------
// Financial summary — emitted from CreateLoadForm for the KPI summary bar
// ---------------------------------------------------------------------------

export interface FinancialSummary {
  customerRate: number;
  grossMargin: number;
  marginPct: number;
  ratePerMile: number;
  totalMiles: number;
  minBookRate: number | null;
  avgCostPerMile: number | null;
  carrierPay: number;
}
