// Derived from loads API contract (openapi spec + API transformers)
// Decimal fields are represented as string (API serializes Decimal as string/unknown)

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export type LoadStatus =
  | 'QUOTED'
  | 'BOOKED'
  | 'DISPATCHED'
  | 'EN_ROUTE_PICKUP'
  | 'AT_PICKUP'
  | 'IN_TRANSIT'
  | 'AT_DELIVERY'
  | 'DELIVERED'
  | 'INVOICE_PENDING'
  | 'INVOICED'
  | 'PAID'
  | 'EXCEPTION'
  | 'CANCELED'
  | 'TONU';

export type EquipmentType =
  | 'DRY_VAN'
  | 'REEFER'
  | 'FLATBED'
  | 'STEP_DECK'
  | 'BOX_TRUCK'
  | 'HOTSHOT'
  | 'POWER_ONLY';

export type StopType = 'PICKUP' | 'DELIVERY' | 'STOP_OFF' | 'DROP_HOOK' | 'LIVE_UNLOAD';

export type BoardView = 'kanban' | 'table';

export type KanbanGroup = 'NEW' | 'BOOKED' | 'ACTIVE' | 'DELIVERED' | 'COMPLETE' | 'ISSUES';

// ---------------------------------------------------------------------------
// Stop
// ---------------------------------------------------------------------------

export interface Stop {
  id: string;
  type: StopType;
  sequence: number;
  contactId: string | null;
  placeId: string | null;
  facilityName: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  appointmentDate: string | null;
  appointmentTime: string | null;
  appointmentNumber: string | null;
  arrivalTime: string | null;
  departureTime: string | null;
  contactName: string | null;
  contactPhone: string | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface StopInput {
  type: StopType;
  sequence: number;
  contactId?: string;
  placeId?: string;
  facilityName?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  appointmentDate?: string;
  appointmentTime?: string;
  appointmentNumber?: string;
  contactName?: string;
  contactPhone?: string;
  notes?: string;
}

// ---------------------------------------------------------------------------
// Accessorial charges
// ---------------------------------------------------------------------------

export type AccessorialType =
  | 'DETENTION'
  | 'LAYOVER'
  | 'LUMPER'
  | 'TARP'
  | 'TONU'
  | 'OTHER';

export interface AccessorialCharge {
  id: string;
  type: string;
  description: string | null;
  amount: string;
  billTo: string;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface AccessorialChargeInput {
  type: AccessorialType;
  description?: string;
  amount: number | string;
  billTo?: string;
  isAutoGenerated?: boolean;
}

// ---------------------------------------------------------------------------
// Load list item (flattened for table/kanban display)
// ---------------------------------------------------------------------------

export interface LoadListItem {
  id: string;
  loadNumber: string;
  status: LoadStatus;
  equipmentType: string | null;
  commodity: string | null;
  customerRate: string | null;
  carrierRate: string | null;
  totalMiles: number | null;
  ratePerMile: string | null;
  carrierId: string | null;
  carrierName: string | null;
  driverId: string | null;
  driverName: string | null;
  originCity: string | null;
  originState: string | null;
  destinationCity: string | null;
  destinationState: string | null;
  accessorialChargeCount: number;
  createdAt: string;
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// Load detail (full entity with relations)
// ---------------------------------------------------------------------------

export interface LoadDetail {
  id: string;
  organizationId: string;
  loadNumber: string;
  carrierId: string | null;
  driverId: string | null;
  vehicleId: string | null;
  brokerId: string | null;
  shipperId: string | null;
  consigneeId: string | null;
  brokerRefNumber: string | null;
  equipmentType: string | null;
  isHazmat: boolean;
  isTarp: boolean;
  isTeamDriver: boolean;
  commodity: string | null;
  weight: number | null;
  pieceCount: number | null;
  loadedMiles: number | null;
  deadheadMiles: number | null;
  totalMiles: number | null;
  customerRate: string | null;
  carrierRate: string | null;
  dispatchFee: string | null;
  partnerSplit: string | null;
  ratePerMile: string | null;
  status: LoadStatus;
  rateConReceivedAt: string | null;
  bolUnsignedAt: string | null;
  bolSignedAt: string | null;
  dispatcherNotes: string | null;
  driverInstructions: string | null;
  createdAt: string;
  updatedAt: string;
  stops: Stop[];
  carrier: { id: string; name: string } | null;
  driver: { id: string; firstName: string; lastName: string } | null;
  vehicle: { id: string; unitNumber: string; type: string } | null;
  broker: { id: string; companyName: string } | null;
  shipper: { id: string; companyName: string } | null;
  consignee: { id: string; companyName: string } | null;
  statusHistory: StatusHistoryEntry[];
  checkCalls: CheckCallSummary[];
  accessorialCharges: AccessorialCharge[];
}

// ---------------------------------------------------------------------------
// Create / Update inputs (frontend -> API)
// ---------------------------------------------------------------------------

export interface CreateLoadInput {
  carrierId?: string;
  driverId?: string;
  vehicleId?: string;
  brokerId?: string;
  shipperId?: string;
  consigneeId?: string;
  brokerRefNumber?: string;
  equipmentType?: EquipmentType;
  isHazmat?: boolean;
  isTarp?: boolean;
  isTeamDriver?: boolean;
  commodity?: string;
  weight?: number;
  pieceCount?: number;
  loadedMiles?: number;
  deadheadMiles?: number;
  totalMiles?: number;
  customerRate?: number | string;
  carrierRate?: number | string;
  dispatchFee?: number | string;
  partnerSplit?: number | string;
  ratePerMile?: number | string;
  status?: LoadStatus;
  dispatcherNotes?: string;
  driverInstructions?: string;
  stops: StopInput[];
  accessorialCharges?: AccessorialChargeInput[];
}

export interface UpdateLoadInput {
  carrierId?: string;
  driverId?: string;
  vehicleId?: string;
  brokerId?: string;
  shipperId?: string;
  consigneeId?: string;
  brokerRefNumber?: string;
  equipmentType?: EquipmentType;
  isHazmat?: boolean;
  isTarp?: boolean;
  isTeamDriver?: boolean;
  commodity?: string;
  weight?: number;
  pieceCount?: number;
  loadedMiles?: number;
  deadheadMiles?: number;
  totalMiles?: number;
  customerRate?: number | string;
  carrierRate?: number | string;
  dispatchFee?: number | string;
  partnerSplit?: number | string;
  ratePerMile?: number | string;
  status?: LoadStatus;
  dispatcherNotes?: string;
  driverInstructions?: string;
  stops?: StopInput[];
  accessorialCharges?: AccessorialChargeInput[];
}

// ---------------------------------------------------------------------------
// Filters
// ---------------------------------------------------------------------------

export interface LoadFilters {
  status?: LoadStatus[];
  carrierId?: string;
  equipmentType?: EquipmentType;
  search?: string;
  dateFrom?: string;
  dateTo?: string;
}

// ---------------------------------------------------------------------------
// Check calls
// ---------------------------------------------------------------------------

export interface CheckCallSummary {
  id: string;
  location: string | null;
  status: string | null;
  eta: string | null;
  notes: string | null;
  createdAt: string;
}

export interface CheckCall {
  id: string;
  loadId: string;
  calledByUserId: string | null;
  calledByName: string | null;
  location: string | null;
  latitude: string | null;
  longitude: string | null;
  status: string | null;
  eta: string | null;
  brokerNotified: boolean;
  brokerNotes: string | null;
  notes: string | null;
  createdAt: string;
}

export interface CreateCheckCallInput {
  location?: string;
  latitude?: number;
  longitude?: number;
  status?: string;
  eta?: string;
  notes?: string;
  brokerNotified: boolean;
  brokerNotes?: string;
}

// ---------------------------------------------------------------------------
// Status history
// ---------------------------------------------------------------------------

export interface StatusHistoryEntry {
  id: string;
  loadId: string;
  fromStatus: string | null;
  toStatus: string;
  changedByUserId: string | null;
  changedByName: string | null;
  notes: string | null;
  createdAt: string;
}

// ---------------------------------------------------------------------------
// Status transition
// ---------------------------------------------------------------------------

export interface TransitionStatusInput {
  targetStatus: LoadStatus;
  notes?: string;
  overrideWarnings?: boolean;
}

export interface StatusTransitionWarning {
  code: string;
  message: string;
  detail?: string;
}

export interface StatusTransitionError {
  code: string;
  message: string;
}

export interface StatusTransitionResponse {
  success: boolean;
  load?: LoadDetail;
  warnings?: StatusTransitionWarning[];
  error?: StatusTransitionError;
}
