import { describe, expect, it } from '@jest/globals';
import Decimal from 'decimal.js';
import { toLoadDetailResponse, toLoadListItemResponse } from '../loadTransformer';
import type { LoadListItem, LoadWithRelations } from '../../../types/loadTypes';

const buildLoad = (overrides?: Partial<LoadWithRelations>): LoadWithRelations => {
  const base: LoadWithRelations = {
    id: 'load-1',
    organizationId: 'org-1',
    loadNumber: 'L-1001',
    carrierId: null,
    driverId: null,
    vehicleId: null,
    contactId: null,
    customerId: null,
    dispatcherUserId: null,
    externalRefNumber: null,
    equipmentType: null,
    isTeamDriver: false,
    loadedMiles: null,
    deadheadMiles: null,
    totalMiles: null,
    customerRate: null,
    carrierRate: null,
    dispatchFee: null,
    partnerSplit: null,
    ratePerMile: null,
    ratePerTotalMile: null,
    carrierPayout: null,
    companyMargin: null,
    driverPay: null,
    estimatedHours: null,
    estimatedCost: null,
    dispatcherComm: null,
    status: 'BOOKED',
    invoiceReadiness: 'NOT_READY',
    rateConReceivedAt: null,
    bolUnsignedAt: null,
    bolSignedAt: null,
    dispatcherNotes: null,
    driverInstructions: null,
    scrapedLoadId: null,
    plannedNextLoadRef: null,
    createdByUserId: null,
    updatedByUserId: null,
    createdAt: new Date('2026-01-01T00:00:00.000Z'),
    updatedAt: new Date('2026-01-01T00:00:00.000Z'),
    deletedAt: null,
    stops: [],
    carrier: null,
    driver: null,
    vehicle: null,
    contact: null,
    customer: null,
    statusHistory: [],
    checkCalls: [],
    accessorialCharges: [],
  };

  return { ...base, ...overrides };
};

const buildListItem = (overrides?: Partial<LoadListItem>): LoadListItem => {
  const base: LoadListItem = {
    id: 'load-1',
    organizationId: 'org-1',
    loadNumber: 'L-1001',
    carrierId: null,
    driverId: null,
    vehicleId: null,
    contactId: null,
    customerId: null,
    dispatcherUserId: null,
    externalRefNumber: null,
    equipmentType: null,
    isTeamDriver: false,
    loadedMiles: null,
    deadheadMiles: null,
    totalMiles: null,
    customerRate: null,
    carrierRate: null,
    dispatchFee: null,
    partnerSplit: null,
    ratePerMile: null,
    ratePerTotalMile: null,
    carrierPayout: null,
    companyMargin: null,
    driverPay: null,
    estimatedHours: null,
    estimatedCost: null,
    dispatcherComm: null,
    status: 'BOOKED',
    invoiceReadiness: 'NOT_READY',
    rateConReceivedAt: null,
    bolUnsignedAt: null,
    bolSignedAt: null,
    dispatcherNotes: null,
    driverInstructions: null,
    scrapedLoadId: null,
    plannedNextLoadRef: null,
    createdByUserId: null,
    updatedByUserId: null,
    createdAt: new Date('2026-01-01T00:00:00.000Z'),
    updatedAt: new Date('2026-01-01T00:00:00.000Z'),
    deletedAt: null,
    stops: [],
    carrier: null,
    driver: null,
    contact: null,
    customer: null,
    _count: { accessorialCharges: 0 },
  };

  return { ...base, ...overrides };
};

const makeAccessorial = (amount: string) => ({
  id: `acc-${amount}`,
  loadId: 'load-1',
  documentId: null,
  type: 'FUEL_SURCHARGE' as const,
  description: null,
  amount: new Decimal(amount),
  billTo: 'CUSTOMER',
  isAutoGenerated: false,
  approvalStatus: 'NONE' as const,
  approvalSource: null,
  approvalNotes: null,
  stopId: null,
  createdAt: new Date('2026-01-01T00:00:00.000Z'),
  updatedAt: new Date('2026-01-01T00:00:00.000Z'),
});

// ---------------------------------------------------------------------------
// toLoadDetailResponse — derived financial fields
// ---------------------------------------------------------------------------

describe('toLoadDetailResponse', () => {
  describe('carrierRpm', () => {
    it('computes carrierRpm as carrierPayout / loadedMiles', () => {
      const load = buildLoad({
        carrierPayout: new Decimal('2520.00'),
        loadedMiles: 800,
      });

      const result = toLoadDetailResponse(load);

      expect(result.carrierRpm).toBe('3.15');
    });

    it('returns null when carrierPayout is null', () => {
      const load = buildLoad({
        carrierPayout: null,
        loadedMiles: 800,
      });

      const result = toLoadDetailResponse(load);

      expect(result.carrierRpm).toBeNull();
    });

    it('returns null when loadedMiles is null', () => {
      const load = buildLoad({
        carrierPayout: new Decimal('2520.00'),
        loadedMiles: null,
      });

      const result = toLoadDetailResponse(load);

      expect(result.carrierRpm).toBeNull();
    });

    it('returns null when loadedMiles is 0', () => {
      const load = buildLoad({
        carrierPayout: new Decimal('2520.00'),
        loadedMiles: 0,
      });

      const result = toLoadDetailResponse(load);

      expect(result.carrierRpm).toBeNull();
    });
  });

  describe('companyNet', () => {
    it('computes companyNet as companyMargin - dispatcherComm', () => {
      const load = buildLoad({
        companyMargin: new Decimal('280.00'),
        dispatcherComm: new Decimal('56.00'),
      });

      const result = toLoadDetailResponse(load);

      expect(result.companyNet).toBe('224.00');
    });

    it('returns null when dispatcherComm is null', () => {
      const load = buildLoad({
        companyMargin: new Decimal('280.00'),
        dispatcherComm: null,
      });

      const result = toLoadDetailResponse(load);

      expect(result.companyNet).toBeNull();
    });

    it('returns null when companyMargin is null', () => {
      const load = buildLoad({
        companyMargin: null,
        dispatcherComm: new Decimal('56.00'),
      });

      const result = toLoadDetailResponse(load);

      expect(result.companyNet).toBeNull();
    });
  });

  describe('marginPercent', () => {
    it('computes marginPercent as companyMargin / customerRate * 100 with no accessorials', () => {
      const load = buildLoad({
        companyMargin: new Decimal('280.00'),
        customerRate: new Decimal('2800.00'),
        accessorialCharges: [],
      });

      const result = toLoadDetailResponse(load);

      expect(result.marginPercent).toBe('10.00');
    });

    it('computes marginPercent including accessorials in gross', () => {
      const load = buildLoad({
        companyMargin: new Decimal('280.00'),
        customerRate: new Decimal('2800.00'),
        accessorialCharges: [makeAccessorial('200.00')],
      });

      // gross = 2800 + 200 = 3000, marginPercent = 280 / 3000 * 100 = 9.3333... → '9.33'
      const result = toLoadDetailResponse(load);

      expect(result.marginPercent).toBe('9.33');
    });

    it('returns null when companyMargin is null', () => {
      const load = buildLoad({
        companyMargin: null,
        customerRate: new Decimal('2800.00'),
      });

      const result = toLoadDetailResponse(load);

      expect(result.marginPercent).toBeNull();
    });

    it('returns null when customerRate is null', () => {
      const load = buildLoad({
        companyMargin: new Decimal('280.00'),
        customerRate: null,
      });

      const result = toLoadDetailResponse(load);

      expect(result.marginPercent).toBeNull();
    });
  });

  describe('estimatedNetEarnings', () => {
    it('computes estimatedNetEarnings as carrierPayout - estimatedCost', () => {
      const load = buildLoad({
        carrierPayout: new Decimal('2520.00'),
        estimatedCost: new Decimal('800.00'),
      });

      const result = toLoadDetailResponse(load);

      expect(result.estimatedNetEarnings).toBe('1720.00');
    });

    it('returns null when estimatedCost is null', () => {
      const load = buildLoad({
        carrierPayout: new Decimal('2520.00'),
        estimatedCost: null,
      });

      const result = toLoadDetailResponse(load);

      expect(result.estimatedNetEarnings).toBeNull();
    });

    it('returns null when carrierPayout is null', () => {
      const load = buildLoad({
        carrierPayout: null,
        estimatedCost: new Decimal('800.00'),
      });

      const result = toLoadDetailResponse(load);

      expect(result.estimatedNetEarnings).toBeNull();
    });
  });
});

// ---------------------------------------------------------------------------
// toLoadListItemResponse — stored and derived financial fields
// ---------------------------------------------------------------------------

describe('toLoadListItemResponse', () => {
  it('maps companyMargin and carrierPayout as strings', () => {
    const load = buildListItem({
      companyMargin: new Decimal('280.00'),
      carrierPayout: new Decimal('2520.00'),
    });

    const result = toLoadListItemResponse(load);

    expect(result.companyMargin).toBe('280');
    expect(result.carrierPayout).toBe('2520');
  });

  it('computes companyNet as companyMargin - dispatcherComm', () => {
    const load = buildListItem({
      companyMargin: new Decimal('280.00'),
      dispatcherComm: new Decimal('56.00'),
    });

    const result = toLoadListItemResponse(load);

    expect(result.companyNet).toBe('224.00');
  });

  it('returns null companyNet when dispatcherComm is null', () => {
    const load = buildListItem({
      companyMargin: new Decimal('280.00'),
      dispatcherComm: null,
    });

    const result = toLoadListItemResponse(load);

    expect(result.companyNet).toBeNull();
  });

  it('returns null companyMargin and carrierPayout when fields are null', () => {
    const load = buildListItem({
      companyMargin: null,
      carrierPayout: null,
    });

    const result = toLoadListItemResponse(load);

    expect(result.companyMargin).toBeNull();
    expect(result.carrierPayout).toBeNull();
  });
});
