import { describe, expect, it } from '@jest/globals';
import Decimal from 'decimal.js';
import { toLoadDetailResponse, toLoadListItemResponse } from '../loadTransformer';
import type { LoadListItem, LoadWithRelations } from '../../../types/loadTypes';

const buildLoad = (overrides?: Partial<LoadWithRelations>): LoadWithRelations => {
  const base: LoadWithRelations = {
    id: 'load-1',
    organizationId: 'org-1',
    loadNumber: 'L-1001',
    carrierId: null,
    driverId: null,
    vehicleId: null,
    contactId: null,
    customerId: null,
    dispatcherUserId: null,
    externalRefNumber: null,
    equipmentType: null,
    isTeamDriver: false,
    loadedMiles: null,
    deadheadMiles: null,
    totalMiles: null,
    customerRate: null,
    carrierRate: null,
    dispatchFee: null,
    partnerSplit: null,
    ratePerMile: null,
    ratePerTotalMile: null,
    carrierPayout: null,
    companyMargin: null,
    driverPay: null,
    estimatedHours: null,
    estimatedCost: null,
    dispatcherComm: null,
    version: 0,
    status: 'BOOKED',
    invoiceReadiness: 'NOT_READY',
    rateConReceivedAt: null,
    bolUnsignedAt: null,
    bolSignedAt: null,
    dispatcherNotes: null,
    driverInstructions: null,
    scrapedLoadId: null,
    plannedNextLoadRef: null,
    createdByUserId: null,
    updatedByUserId: null,
    onboardingOverride: false,
    onboardingOverrideReason: null,
    dispatchFeeOverrideType: null,
    dispatchFeeOverrideAmount: null,
    createdAt: new Date('2026-01-01T00:00:00.000Z'),
    updatedAt: new Date('2026-01-01T00:00:00.000Z'),
    deletedAt: null,
    stops: [],
    carrier: null,
    driver: null,
    vehicle: null,
    contact: null,
    customer: null,
    statusHistory: [],
    checkCalls: [],
    accessorialCharges: [],
  };

  return { ...base, ...overrides };
};

const buildListItem = (overrides?: Partial<LoadListItem>): LoadListItem => {
  const base: LoadListItem = {
    id: 'load-1',
    organizationId: 'org-1',
    loadNumber: 'L-1001',
    carrierId: null,
    driverId: null,
    vehicleId: null,
    contactId: null,
    customerId: null,
    dispatcherUserId: null,
    externalRefNumber: null,
    equipmentType: null,
    isTeamDriver: false,
    loadedMiles: null,
    deadheadMiles: null,
    totalMiles: null,
    customerRate: null,
    carrierRate: null,
    dispatchFee: null,
    partnerSplit: null,
    ratePerMile: null,
    ratePerTotalMile: null,
    carrierPayout: null,
    companyMargin: null,
    driverPay: null,
    estimatedHours: null,
    estimatedCost: null,
    dispatcherComm: null,
    version: 0,
    status: 'BOOKED',
    invoiceReadiness: 'NOT_READY',
    rateConReceivedAt: null,
    bolUnsignedAt: null,
    bolSignedAt: null,
    dispatcherNotes: null,
    driverInstructions: null,
    scrapedLoadId: null,
    plannedNextLoadRef: null,
    createdByUserId: null,
    updatedByUserId: null,
    onboardingOverride: false,
    onboardingOverrideReason: null,
    dispatchFeeOverrideType: null,
    dispatchFeeOverrideAmount: null,
    createdAt: new Date('2026-01-01T00:00:00.000Z'),
    updatedAt: new Date('2026-01-01T00:00:00.000Z'),
    deletedAt: null,
    stops: [],
    carrier: null,
    driver: null,
    contact: null,
    customer: null,
    _count: { accessorialCharges: 0 },
  };

  return { ...base, ...overrides };
};

const makeDriver = (overrides?: Partial<LoadWithRelations['driver'] & object>) => ({
  id: 'd-1',
  carrierId: 'c-1',
  firstName: 'John',
  lastName: 'Doe',
  phone: null,
  email: null,
  licenseType: 'CDL_A' as const,
  licenseNumber: null,
  licenseState: null,
  licenseExpiry: null,
  endorsements: null,
  availableHours: null,
  currentCity: null,
  currentState: null,
  currentLatitude: null,
  currentLongitude: null,
  homeBaseCity: null,
  homeBaseState: null,
  maxDaysOut: 5,
  preferredLanes: null,
  weeklySchedule: null,
  freightPreferences: null,
  noGoZones: null,
  isAvailable: true,
  status: 'ACTIVE' as const,
  timezone: null,
  notes: null,
  payType: 'PERCENTAGE' as const,
  payRate: new Decimal('0'),
  createdAt: new Date('2026-01-01T00:00:00.000Z'),
  updatedAt: new Date('2026-01-01T00:00:00.000Z'),
  deletedAt: null,
  ...overrides,
});

const makeCarrierListItem = (overrides?: Partial<LoadListItem['carrier'] & object>) => ({
  id: 'c-1',
  name: 'FastTruck',
  ...overrides,
});

const makeDriverListItem = (overrides?: Partial<LoadListItem['driver'] & object>) => ({
  id: 'd-1',
  firstName: 'John',
  lastName: 'Doe',
  ...overrides,
});

const makeAccessorial = (amount: string) => ({
  id: `acc-${amount}`,
  loadId: 'load-1',
  documentId: null,
  type: 'FUEL_SURCHARGE' as const,
  description: null,
  amount: new Decimal(amount),
  billTo: 'CUSTOMER',
  isAutoGenerated: false,
  approvalStatus: 'NONE' as const,
  approvalSource: null,
  approvalNotes: null,
  stopId: null,
  createdAt: new Date('2026-01-01T00:00:00.000Z'),
  updatedAt: new Date('2026-01-01T00:00:00.000Z'),
});

// ---------------------------------------------------------------------------
// toLoadDetailResponse — derived financial fields
// ---------------------------------------------------------------------------

describe('toLoadDetailResponse', () => {
  describe('carrierRpm', () => {
    it('computes carrierRpm as carrierPayout / loadedMiles', () => {
      const load = buildLoad({
        carrierPayout: new Decimal('2520.00'),
        loadedMiles: 800,
      });

      const result = toLoadDetailResponse(load);

      expect(result.financials.carrierRpm).toBe('3.15');
    });

    it('returns null when carrierPayout is null', () => {
      const load = buildLoad({
        carrierPayout: null,
        loadedMiles: 800,
      });

      const result = toLoadDetailResponse(load);

      expect(result.financials.carrierRpm).toBeNull();
    });

    it('returns null when loadedMiles is null', () => {
      const load = buildLoad({
        carrierPayout: new Decimal('2520.00'),
        loadedMiles: null,
      });

      const result = toLoadDetailResponse(load);

      expect(result.financials.carrierRpm).toBeNull();
    });

    it('returns null when loadedMiles is 0', () => {
      const load = buildLoad({
        carrierPayout: new Decimal('2520.00'),
        loadedMiles: 0,
      });

      const result = toLoadDetailResponse(load);

      expect(result.financials.carrierRpm).toBeNull();
    });
  });

  describe('companyNet', () => {
    it('computes companyNet as companyMargin - dispatcherComm', () => {
      const load = buildLoad({
        companyMargin: new Decimal('280.00'),
        dispatcherComm: new Decimal('56.00'),
      });

      const result = toLoadDetailResponse(load);

      expect(result.financials.companyNet).toBe('224.00');
    });

    it('returns null when dispatcherComm is null', () => {
      const load = buildLoad({
        companyMargin: new Decimal('280.00'),
        dispatcherComm: null,
      });

      const result = toLoadDetailResponse(load);

      expect(result.financials.companyNet).toBeNull();
    });

    it('returns null when companyMargin is null', () => {
      const load = buildLoad({
        companyMargin: null,
        dispatcherComm: new Decimal('56.00'),
      });

      const result = toLoadDetailResponse(load);

      expect(result.financials.companyNet).toBeNull();
    });
  });

  describe('marginPercent', () => {
    it('computes marginPercent as companyMargin / customerRate * 100 with no accessorials', () => {
      const load = buildLoad({
        companyMargin: new Decimal('280.00'),
        customerRate: new Decimal('2800.00'),
        accessorialCharges: [],
      });

      const result = toLoadDetailResponse(load);

      expect(result.financials.marginPercent).toBe('10.00');
    });

    it('computes marginPercent including accessorials in gross', () => {
      const load = buildLoad({
        companyMargin: new Decimal('280.00'),
        customerRate: new Decimal('2800.00'),
        accessorialCharges: [makeAccessorial('200.00')],
      });

      // gross = 2800 + 200 = 3000, marginPercent = 280 / 3000 * 100 = 9.3333... → '9.33'
      const result = toLoadDetailResponse(load);

      expect(result.financials.marginPercent).toBe('9.33');
    });

    it('returns null when companyMargin is null', () => {
      const load = buildLoad({
        companyMargin: null,
        customerRate: new Decimal('2800.00'),
      });

      const result = toLoadDetailResponse(load);

      expect(result.financials.marginPercent).toBeNull();
    });

    it('returns null when customerRate is null', () => {
      const load = buildLoad({
        companyMargin: new Decimal('280.00'),
        customerRate: null,
      });

      const result = toLoadDetailResponse(load);

      expect(result.financials.marginPercent).toBeNull();
    });
  });

  describe('estimatedNetEarnings', () => {
    it('computes estimatedNetEarnings as carrierPayout - estimatedCost', () => {
      const load = buildLoad({
        carrierPayout: new Decimal('2520.00'),
        estimatedCost: new Decimal('800.00'),
      });

      const result = toLoadDetailResponse(load);

      expect(result.financials.estimatedNetEarnings).toBe('1720.00');
    });

    it('returns null when estimatedCost is null', () => {
      const load = buildLoad({
        carrierPayout: new Decimal('2520.00'),
        estimatedCost: null,
      });

      const result = toLoadDetailResponse(load);

      expect(result.financials.estimatedNetEarnings).toBeNull();
    });

    it('returns null when carrierPayout is null', () => {
      const load = buildLoad({
        carrierPayout: null,
        estimatedCost: new Decimal('800.00'),
      });

      const result = toLoadDetailResponse(load);

      expect(result.financials.estimatedNetEarnings).toBeNull();
    });
  });

  describe('grouped structure', () => {
    it('groups route fields correctly', () => {
      const load = buildLoad({
        loadedMiles: 500,
        deadheadMiles: 50,
        totalMiles: 550,
        estimatedHours: new Decimal('8.5'),
      });

      const result = toLoadDetailResponse(load);

      expect(result.route.loadedMiles).toBe(500);
      expect(result.route.deadheadMiles).toBe(50);
      expect(result.route.totalMiles).toBe(550);
      expect(result.route.estimatedHours).toBe('8.5');
      expect(result.route.stops).toEqual([]);
    });

    it('groups assignment fields correctly', () => {
      const load = buildLoad({
        isTeamDriver: true,
        carrier: null,
        driver: makeDriver(),
        vehicle: null,
      });

      const result = toLoadDetailResponse(load);

      expect(result.assignment.isTeamDriver).toBe(true);
      expect(result.assignment.driver).toEqual({
        id: 'd-1',
        firstName: 'John',
        lastName: 'Doe',
        phone: null,
        currentLatitude: null,
        currentLongitude: null,
      });
      expect(result.assignment.carrier).toBeNull();
      expect(result.assignment.vehicle).toBeNull();
    });

    it('groups tracking fields correctly', () => {
      const load = buildLoad({
        invoiceReadiness: 'READY',
        rateConReceivedAt: new Date('2026-02-01T00:00:00.000Z'),
        bolUnsignedAt: null,
        bolSignedAt: null,
      });

      const result = toLoadDetailResponse(load);

      expect(result.tracking.invoiceReadiness).toBe('READY');
      expect(result.tracking.rateConReceivedAt).toBe('2026-02-01T00:00:00.000Z');
      expect(result.tracking.bolUnsignedAt).toBeNull();
    });

    it('groups activity fields correctly', () => {
      const result = toLoadDetailResponse(buildLoad());

      expect(result.activity.statusHistory).toEqual([]);
      expect(result.activity.checkCalls).toEqual([]);
      expect(result.activity.accessorialCharges).toEqual([]);
    });
  });
});

// ---------------------------------------------------------------------------
// toLoadListItemResponse — stored and derived financial fields
// ---------------------------------------------------------------------------

describe('toLoadListItemResponse', () => {
  it('maps companyMargin and carrierPayout as strings', () => {
    const load = buildListItem({
      companyMargin: new Decimal('280.00'),
      carrierPayout: new Decimal('2520.00'),
    });

    const result = toLoadListItemResponse(load);

    expect(result.financials.companyMargin).toBe('280');
    expect(result.financials.carrierPayout).toBe('2520');
  });

  it('computes companyNet as companyMargin - dispatcherComm', () => {
    const load = buildListItem({
      companyMargin: new Decimal('280.00'),
      dispatcherComm: new Decimal('56.00'),
    });

    const result = toLoadListItemResponse(load);

    expect(result.financials.companyNet).toBe('224.00');
  });

  it('returns null companyNet when dispatcherComm is null', () => {
    const load = buildListItem({
      companyMargin: new Decimal('280.00'),
      dispatcherComm: null,
    });

    const result = toLoadListItemResponse(load);

    expect(result.financials.companyNet).toBeNull();
  });

  it('returns null companyMargin and carrierPayout when fields are null', () => {
    const load = buildListItem({
      companyMargin: null,
      carrierPayout: null,
    });

    const result = toLoadListItemResponse(load);

    expect(result.financials.companyMargin).toBeNull();
    expect(result.financials.carrierPayout).toBeNull();
  });

  it('groups route fields correctly', () => {
    const result = toLoadListItemResponse(buildListItem({ totalMiles: 500 }));

    expect(result.route.totalMiles).toBe(500);
    expect(result.route.stops).toEqual([]);
  });

  it('groups assignment fields correctly', () => {
    const load = buildListItem({
      carrierId: 'c-1',
      carrier: makeCarrierListItem(),
      driverId: 'd-1',
      driver: makeDriverListItem(),
    });

    const result = toLoadListItemResponse(load);

    expect(result.assignment.carrier).toEqual({ id: 'c-1', name: 'FastTruck' });
    expect(result.assignment.driver).toEqual({
      id: 'd-1',
      firstName: 'John',
      lastName: 'Doe',
    });
  });
});
