import type { Request } from 'express';
import type { CreateAccessorialInput } from '../../types/accessorialTypes';

export const createAccessorialMapper = (req: Request): CreateAccessorialInput => ({
  organizationId: req.organizationId ?? '',
  loadId: req.params['loadId'] ?? '',
  type: req.body.type,
  amount: req.body.amount,
  description: req.body.description,
  billTo: req.body.billTo,
  isAutoGenerated: req.body.isAutoGenerated,
});
