import type { Request } from 'express';
import type { CreateAccessorialInput } from '../../types/accessorialTypes';
import { UnauthorizedError } from '@/shared/errors';

export const createAccessorialMapper = (req: Request): CreateAccessorialInput => {
  const organizationId = req.organizationId;
  const loadId = req.params['loadId'];

  if (organizationId === undefined || loadId === undefined) {
    throw new UnauthorizedError('Authentication required');
  }

  return {
    organizationId,
    loadId,
    type: req.body.type,
    amount: req.body.amount,
    description: req.body.description,
    billTo: req.body.billTo,
    isAutoGenerated: req.body.isAutoGenerated,
  };
};
