// Auto-generated from contract.yaml — DO NOT EDIT MANUALLY

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export enum SchedulingType {
  APPOINTMENT = 'APPOINTMENT',
  FCFS = 'FCFS',
  NOTIFICATION = 'NOTIFICATION',
  OPEN = 'OPEN',
  DROP_HOOK = 'DROP_HOOK',
}

export enum StopType {
  PICKUP = 'PICKUP',
  DELIVERY = 'DELIVERY',
  STOP_OFF = 'STOP_OFF',
  DROP_HOOK = 'DROP_HOOK',
  LIVE_UNLOAD = 'LIVE_UNLOAD',
}

export enum LoadStatus {
  QUOTED = 'QUOTED',
  BOOKED = 'BOOKED',
  DISPATCHED = 'DISPATCHED',
  EN_ROUTE_PICKUP = 'EN_ROUTE_PICKUP',
  AT_PICKUP = 'AT_PICKUP',
  IN_TRANSIT = 'IN_TRANSIT',
  AT_DELIVERY = 'AT_DELIVERY',
  DELIVERED = 'DELIVERED',
  INVOICE_PENDING = 'INVOICE_PENDING',
  INVOICED = 'INVOICED',
  PAID = 'PAID',
  EXCEPTION = 'EXCEPTION',
  CANCELED = 'CANCELED',
  TONU = 'TONU',
}

export enum AccessorialType {
  DETENTION = 'DETENTION',
  LUMPER = 'LUMPER',
  TONU = 'TONU',
  LAYOVER = 'LAYOVER',
  DRIVER_ASSIST = 'DRIVER_ASSIST',
  FUEL_SURCHARGE = 'FUEL_SURCHARGE',
  TARP = 'TARP',
  TOLL = 'TOLL',
  OTHER = 'OTHER',
}

export enum ApprovalStatus {
  NONE = 'NONE',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  DISPUTED = 'DISPUTED',
}

export enum DispatchGateWarningCode {
  APPOINTMENT_NUMBER_MISSING = 'APPOINTMENT_NUMBER_MISSING',
  TRANSITION_WARNING = 'TRANSITION_WARNING',
}

// ---------------------------------------------------------------------------
// Scheduling type field requirements
// ---------------------------------------------------------------------------

export const SCHEDULING_TYPE_REQUIRED_FIELDS: Record<SchedulingType, string[]> = {
  [SchedulingType.APPOINTMENT]: ['appointmentStart'],
  [SchedulingType.FCFS]: ['targetDate'],
  [SchedulingType.NOTIFICATION]: ['notificationHours'],
  [SchedulingType.OPEN]: [],
  [SchedulingType.DROP_HOOK]: [],
};

// ---------------------------------------------------------------------------
// Stop types
// ---------------------------------------------------------------------------

export interface StopInput {
  type: StopType;
  sequence: number;
  contactId?: string;
  placeId?: string;
  facilityName?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  schedulingType?: SchedulingType;
  appointmentStart?: string | null;
  appointmentEnd?: string | null;
  targetDate?: string | null;
  notificationHours?: number | null;
  appointmentNumber?: string;
  contactName?: string;
  contactPhone?: string;
  commodity?: string;
  weight?: number;
  pieceCount?: number;
  isHazmat?: boolean;
  isTarp?: boolean;
  isTempControlled?: boolean;
  notes?: string;
}

export interface UpdateStopInput {
  type?: StopType;
  sequence?: number;
  facilityName?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  schedulingType?: SchedulingType;
  appointmentStart?: string | null;
  appointmentEnd?: string | null;
  targetDate?: string | null;
  notificationHours?: number | null;
  appointmentNumber?: string;
  arrivalTime?: string;
  departureTime?: string;
  contactName?: string;
  contactPhone?: string;
  commodity?: string;
  weight?: number;
  pieceCount?: number;
  isHazmat?: boolean;
  isTarp?: boolean;
  isTempControlled?: boolean;
  notes?: string;
}

// ---------------------------------------------------------------------------
// Status transition types
// ---------------------------------------------------------------------------

export interface TransitionStatusRequest {
  status: LoadStatus;
  notes?: string;
  overrideWarnings?: boolean;
}

export interface StatusTransitionWarning {
  code: DispatchGateWarningCode;
  message: string;
  detail?: string;
}

export interface StatusTransitionResponse {
  success: boolean;
  load?: Record<string, unknown>;
  warnings?: StatusTransitionWarning[];
  error?: {
    code: string;
    message: string;
  };
}

// ---------------------------------------------------------------------------
// Detention types
// ---------------------------------------------------------------------------

export interface AutoGeneratedDetentionCharge {
  type: 'DETENTION';
  amount: number;
  billTo: 'customer';
  approvalStatus: 'PENDING';
  isAutoGenerated: true;
  stopId: string;
  description: string;
}

export interface DetentionDetectedEventPayload {
  loadId: string;
  organizationId: string;
  loadNumber: string;
  stopId: string;
  stopSequence: number;
  facilityName: string | null;
  city: string | null;
  state: string | null;
  waitHours: number;
  billableHours: number;
  rate: number;
  amount: number;
}

export interface DetentionDetectedEvent {
  type: 'load.detention.detected';
  occurredAt: string;
  payload: DetentionDetectedEventPayload;
}

// ---------------------------------------------------------------------------
// Accessorial charge input
// ---------------------------------------------------------------------------

export interface AccessorialChargeInput {
  type: AccessorialType;
  description?: string;
  amount: number;
  billTo?: 'customer' | 'carrier';
  isAutoGenerated?: boolean;
}

// ---------------------------------------------------------------------------
// Error response
// ---------------------------------------------------------------------------

export interface ErrorResponse {
  errors: {
    message: string;
    field?: string;
  }[];
}
