import type { Driver, PaginationMeta } from 'features/carrier/types';

const CARRIER_ID_1 = 'c1a2b3c4-d5e6-7890-abcd-ef1234567890';
const CARRIER_ID_2 = 'c2b3c4d5-e6f7-8901-bcde-f12345678901';
const CARRIER_ID_3 = 'c3c4d5e6-f7a8-9012-cdef-123456789012';

export const MOCK_DRIVERS: Driver[] = [
  {
    id: 'd1a1a1a1-b2b2-c3c3-d4d4-e5e5e5e5e5e5',
    carrierId: CARRIER_ID_1,
    firstName: 'Marcus',
    lastName: 'Johnson',
    email: 'marcus.johnson@example.com',
    phone: '(214) 555-0142',
    licenseType: 'CDL_A',
    licenseNumber: 'TX-CDL-8834210',
    licenseState: 'TX',
    licenseExpiry: '2027-09-15T00:00:00.000Z',
    endorsements: ['H', 'N'],
    isAvailable: true,
    status: 'active',
    homeBaseCity: 'Dallas',
    homeBaseState: 'TX',
    availableHours: '62.0',
    currentCity: 'Dallas',
    currentState: 'TX',
    currentLatitude: null,
    currentLongitude: null,
    maxDaysOut: 14,
    preferredLanes: [
      { originState: 'TX', destState: 'CA', originCity: 'Dallas', destCity: 'Los Angeles' },
      { originState: 'TX', destState: 'IL', originCity: null, destCity: 'Chicago' },
    ],
    noGoZones: [{ state: 'NY', city: 'New York City' }],
    payType: 'PERCENTAGE',
    payRate: '28.00',
    notes: 'Experienced OTR driver. Prefers long hauls.',
    createdAt: '2026-01-10T14:30:00.000Z',
    updatedAt: '2026-03-04T09:15:00.000Z',
    deletedAt: null,
  },
  {
    id: 'd2a2a2a2-b3b3-c4c4-d5d5-e6e6e6e6e6e6',
    carrierId: CARRIER_ID_1,
    firstName: 'Sarah',
    lastName: 'Mitchell',
    email: 'sarah.mitchell@example.com',
    phone: '(404) 555-0278',
    licenseType: 'CDL_A',
    licenseNumber: 'GA-CDL-5521087',
    licenseState: 'GA',
    licenseExpiry: '2027-03-22T00:00:00.000Z',
    endorsements: null,
    isAvailable: false,
    status: 'on_load',
    homeBaseCity: 'Atlanta',
    homeBaseState: 'GA',
    availableHours: '34.5',
    currentCity: 'Nashville',
    currentState: 'TN',
    currentLatitude: null,
    currentLongitude: null,
    maxDaysOut: 10,
    preferredLanes: [
      { originState: 'GA', destState: 'FL', originCity: 'Atlanta', destCity: null },
      { originState: 'GA', destState: 'NC', originCity: null, destCity: null },
    ],
    noGoZones: [],
    payType: 'PER_MILE',
    payRate: '0.65',
    notes: null,
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-03-03T16:45:00.000Z',
    deletedAt: null,
  },
  {
    id: 'd3a3a3a3-b4b4-c5c5-d6d6-e7e7e7e7e7e7',
    carrierId: CARRIER_ID_2,
    firstName: 'James',
    lastName: 'Rivera',
    email: 'j.rivera@example.com',
    phone: '(312) 555-0391',
    licenseType: 'CDL_A',
    licenseNumber: 'IL-CDL-7743902',
    licenseState: 'IL',
    licenseExpiry: '2026-11-30T00:00:00.000Z',
    endorsements: ['H', 'X'],
    isAvailable: true,
    status: 'active',
    homeBaseCity: 'Chicago',
    homeBaseState: 'IL',
    availableHours: '70.0',
    currentCity: 'Chicago',
    currentState: 'IL',
    currentLatitude: null,
    currentLongitude: null,
    maxDaysOut: 21,
    preferredLanes: [
      { originState: 'IL', destState: 'TX', originCity: 'Chicago', destCity: 'Houston' },
    ],
    noGoZones: [
      { state: 'MT', city: null },
      { state: 'WY', city: null },
    ],
    payType: null,
    payRate: null,
    notes: 'Hazmat endorsed. Clean inspection record.',
    createdAt: '2026-02-01T08:20:00.000Z',
    updatedAt: '2026-03-04T00:00:00.000Z',
    deletedAt: null,
  },
  {
    id: 'd4a4a4a4-b5b5-c6c6-d7d7-e8e8e8e8e8e8',
    carrierId: CARRIER_ID_2,
    firstName: 'Robert',
    lastName: 'Chen',
    email: null,
    phone: '(916) 555-0455',
    licenseType: 'CDL_B',
    licenseNumber: 'CA-CDL-3310458',
    licenseState: 'CA',
    licenseExpiry: '2026-08-10T00:00:00.000Z',
    endorsements: null,
    isAvailable: true,
    status: 'active',
    homeBaseCity: 'Sacramento',
    homeBaseState: 'CA',
    availableHours: '55.5',
    currentCity: 'Reno',
    currentState: 'NV',
    currentLatitude: null,
    currentLongitude: null,
    maxDaysOut: 7,
    preferredLanes: [],
    noGoZones: [],
    payType: 'FLAT_RATE',
    payRate: '1200.00',
    notes: null,
    createdAt: '2026-02-10T12:00:00.000Z',
    updatedAt: '2026-03-02T18:30:00.000Z',
    deletedAt: null,
  },
  {
    id: 'd5a5a5a5-b6b6-c7c7-d8d8-e9e9e9e9e9e9',
    carrierId: CARRIER_ID_3,
    firstName: 'Angela',
    lastName: 'Washington',
    email: 'a.washington@example.com',
    phone: '(901) 555-0512',
    licenseType: 'CDL_A',
    licenseNumber: 'TN-CDL-6629134',
    licenseState: 'TN',
    licenseExpiry: '2028-01-20T00:00:00.000Z',
    endorsements: ['T'],
    isAvailable: false,
    status: 'inactive',
    homeBaseCity: 'Memphis',
    homeBaseState: 'TN',
    availableHours: null,
    currentCity: null,
    currentState: null,
    currentLatitude: null,
    currentLongitude: null,
    maxDaysOut: null,
    preferredLanes: [
      { originState: 'TN', destState: 'TX', originCity: 'Memphis', destCity: 'Dallas' },
      { originState: 'TN', destState: 'GA', originCity: 'Memphis', destCity: 'Atlanta' },
      { originState: 'AR', destState: 'MO', originCity: null, destCity: null },
    ],
    noGoZones: [{ state: 'CO', city: 'Denver' }],
    payType: null,
    payRate: null,
    notes: 'On personal leave until April.',
    createdAt: '2026-01-20T09:00:00.000Z',
    updatedAt: '2026-02-28T11:00:00.000Z',
    deletedAt: null,
  },
  {
    id: 'd6a6a6a6-b7b7-c8c8-d9d9-eaeaeaeaeaea',
    carrierId: CARRIER_ID_3,
    firstName: 'Travis',
    lastName: 'Coleman',
    email: 'travis.coleman@example.com',
    phone: '(602) 555-0634',
    licenseType: 'CDL_A',
    licenseNumber: 'AZ-CDL-9917265',
    licenseState: 'AZ',
    licenseExpiry: '2027-06-05T00:00:00.000Z',
    endorsements: null,
    isAvailable: true,
    status: 'active',
    homeBaseCity: 'Phoenix',
    homeBaseState: 'AZ',
    availableHours: '48.0',
    currentCity: 'Tucson',
    currentState: 'AZ',
    currentLatitude: null,
    currentLongitude: null,
    maxDaysOut: 12,
    preferredLanes: [
      { originState: 'AZ', destState: 'CA', originCity: 'Phoenix', destCity: null },
    ],
    noGoZones: [
      { state: 'OR', city: 'Portland' },
      { state: 'WA', city: 'Seattle' },
    ],
    payType: 'PER_HOUR',
    payRate: '22.00',
    notes: null,
    createdAt: '2026-02-05T15:45:00.000Z',
    updatedAt: '2026-03-04T07:20:00.000Z',
    deletedAt: null,
  },
];

export const MOCK_DRIVER_DETAIL: Driver = MOCK_DRIVERS[0];

export const MOCK_DRIVERS_META: PaginationMeta = {
  page: 1,
  limit: 25,
  total: 6,
  totalPages: 1,
  hasMore: false,
};
