import type { AccessorialCharge } from '@prisma/client';

export interface AccessorialResponse {
  id: string;
  loadId: string;
  type: string;
  description: string | null;
  amount: string;
  billTo: string;
  isAutoGenerated: boolean;
  approvalStatus: string;
  approvalSource: string | null;
  approvalNotes: string | null;
  documentId: string | null;
  createdAt: string;
  updatedAt: string;
}

export const toAccessorialResponse = (charge: AccessorialCharge): AccessorialResponse => ({
  id: charge.id,
  loadId: charge.loadId,
  type: charge.type,
  description: charge.description,
  amount: String(charge.amount),
  billTo: charge.billTo,
  isAutoGenerated: charge.isAutoGenerated,
  approvalStatus: charge.approvalStatus,
  approvalSource: charge.approvalSource,
  approvalNotes: charge.approvalNotes,
  documentId: charge.documentId,
  createdAt: charge.createdAt.toISOString(),
  updatedAt: charge.updatedAt.toISOString(),
});

export const toAccessorialListResponse = (charges: AccessorialCharge[]): AccessorialResponse[] =>
  charges.map(toAccessorialResponse);
