import { Decimal } from 'decimal.js';
import type { InvoiceReadiness } from '../../services/derivedFinancials';
import type { PaginationMeta } from '@/shared/responseEnvelope';
import { computeCommoditySummary } from '@/shared/utils/computeCommoditySummary';
import {
  computeLoadFinancials,
  computeInvoiceReadiness,
  sumAccessorials,
} from '../../services/derivedFinancials';
import type { LoadFinancialsResult } from '@/shared/financials';
import type {
  LoadListItem,
  LoadWithRelations,
  LoadDetailResponse,
  LoadListItemResponse,
  StopResponse,
  AccessorialChargeResponse,
  CheckCallResponse,
  StatusHistoryResponse,
} from '../../types/loadTypes';

const ROUNDING = Decimal.ROUND_HALF_EVEN;

// ---------------------------------------------------------------------------
// Derived-financials helpers (US-11)
//
// Note on dispatchFeeAmount semantics: when load.dispatchFeeType=PERCENTAGE,
// Load.dispatchFeeAmount holds a percent value (e.g. "10" for 10%) — NOT
// dollars. When dispatchFeeType=FLAT, it holds dollars. The compute fn does
// the right math; the response just echoes the persisted input.
// ---------------------------------------------------------------------------

interface NullFinancials {
  dispatchFee: string | null;
  partnerSplit: string | null;
  ratePerMile: string | null;
  ratePerTotalMile: string | null;
  carrierPayout: string | null;
  companyMargin: string | null;
  driverPay: string | null;
  estimatedCost: string | null;
  dispatcherComm: string | null;
}

const NULL_FINANCIALS: NullFinancials = {
  dispatchFee: null,
  partnerSplit: null,
  ratePerMile: null,
  ratePerTotalMile: null,
  carrierPayout: null,
  companyMargin: null,
  driverPay: null,
  estimatedCost: null,
  dispatcherComm: null,
};

/**
 * Attempts to compute financials from the Load row's snapshot inputs. If
 * customerRate is null the load isn't priced yet — return all-nulls (matches
 * the pre-US-11 persisted-column behavior before calculateAndPersistFinancials
 * ran).
 */
const tryComputeFinancials = (load: LoadWithRelations): LoadFinancialsResult | null => {
  if (load.customerRate === null) {
    return null;
  }
  const accessorialsSum = sumAccessorials(load.accessorialCharges);
  return computeLoadFinancials(load, accessorialsSum);
};

const toCoord = (val: unknown): number | null => {
  if (val === null || val === undefined) return null;
  const num = Number(val);
  return Number.isFinite(num) ? num : null;
};

const toStopResponse = (stop: LoadWithRelations['stops'][number]): StopResponse => ({
  id: stop.id,
  type: stop.type,
  sequence: stop.sequence,
  contactId: stop.contactId,
  placeId: stop.placeId,
  resolutionStatus: stop.resolutionStatus,
  facilityName: stop.facilityName,
  address: stop.address,
  city: stop.city,
  state: stop.state,
  zip: stop.zip,
  lat: toCoord(stop.place?.latitude),
  lng: toCoord(stop.place?.longitude),
  schedulingType: stop.schedulingType,
  appointmentStart: stop.appointmentStart.toISOString(),
  appointmentEnd: stop.appointmentEnd?.toISOString() ?? null,
  notificationHours: stop.notificationHours,
  notifiedAt: stop.notifiedAt?.toISOString() ?? null,
  appointmentNumber: stop.appointmentNumber,
  arrivalTime: stop.arrivalTime?.toISOString() ?? null,
  departureTime: stop.departureTime?.toISOString() ?? null,
  contactName: stop.contactName,
  contactPhone: stop.contactPhone,
  commodity: stop.commodity,
  weight: stop.weight,
  pieceCount: stop.pieceCount,
  isHazmat: stop.isHazmat,
  isTarp: stop.isTarp,
  isTempControlled: stop.isTempControlled,
  notes: stop.notes,
  callByTime: stop.callByTime,
  trailerNumber: stop.trailerNumber,
  yardLocation: stop.yardLocation,
  createdAt: stop.createdAt.toISOString(),
  updatedAt: stop.updatedAt.toISOString(),
});

const toAccessorialChargeResponse = (
  charge: LoadWithRelations['accessorialCharges'][number],
): AccessorialChargeResponse => ({
  id: charge.id,
  type: charge.type,
  description: charge.description,
  amount: String(charge.amount),
  billTo: charge.billTo,
  approvalStatus: charge.approvalStatus,
  stopId: charge.stopId,
  isAutoGenerated: charge.isAutoGenerated,
  createdAt: charge.createdAt.toISOString(),
  updatedAt: charge.updatedAt.toISOString(),
});

const pickLatestDriverPosition = (
  load: LoadWithRelations,
): { latitude: number | null; longitude: number | null } => {
  const driverLat = toCoord(load.driver?.currentLatitude);
  const driverLng = toCoord(load.driver?.currentLongitude);
  if (driverLat !== null && driverLng !== null) {
    return { latitude: driverLat, longitude: driverLng };
  }

  const latestWithCoords = load.checkCalls.find(
    (call) => call.latitude !== null && call.longitude !== null,
  );
  if (latestWithCoords === undefined) {
    return { latitude: null, longitude: null };
  }
  return {
    latitude: toCoord(latestWithCoords.latitude),
    longitude: toCoord(latestWithCoords.longitude),
  };
};

const toCheckCallResponse = (call: LoadWithRelations['checkCalls'][number]): CheckCallResponse => ({
  id: call.id,
  location: call.location,
  latitude: toCoord(call.latitude),
  longitude: toCoord(call.longitude),
  status: call.status,
  eta: call.eta?.toISOString() ?? null,
  notes: call.notes,
  brokerNotified: call.brokerNotified,
  brokerNotes: call.brokerNotes,
  calledByUserId: call.calledByUserId,
  calledByName: call.calledBy ? `${call.calledBy.firstName} ${call.calledBy.lastName}` : null,
  createdAt: call.createdAt.toISOString(),
});

const toStatusHistoryResponse = (
  entry: LoadWithRelations['statusHistory'][number],
): StatusHistoryResponse => ({
  id: entry.id,
  fromStatus: entry.fromStatus,
  toStatus: entry.toStatus,
  notes: entry.notes,
  changedByUserId: entry.changedByUserId,
  changedByName: entry.changedBy
    ? `${entry.changedBy.firstName} ${entry.changedBy.lastName}`
    : null,
  createdAt: entry.createdAt.toISOString(),
});

/**
 * Computes the read-time derived fields (carrierRpm, companyNet, marginPercent,
 * estimatedNetEarnings) from a computed financials snapshot. These are second-
 * order values that the API exposes for the UI but doesn't persist.
 */
const buildDerivedFinancials = (
  financials: LoadFinancialsResult | null,
  load: LoadWithRelations,
) => {
  if (financials === null) {
    return {
      carrierRpm: null,
      companyNet: null,
      marginPercent: null,
      estimatedNetEarnings: null,
    };
  }

  const carrierPayout = new Decimal(financials.carrierPayout);
  const companyMargin = new Decimal(financials.companyMargin);

  const carrierRpm =
    load.loadedMiles !== null && load.loadedMiles !== 0
      ? carrierPayout.dividedBy(load.loadedMiles).toDecimalPlaces(2, ROUNDING).toFixed(2)
      : null;

  const companyNet =
    financials.dispatcherComm !== null
      ? companyMargin
          .minus(new Decimal(financials.dispatcherComm))
          .toDecimalPlaces(2, ROUNDING)
          .toFixed(2)
      : null;

  const marginPercent = (() => {
    if (load.customerRate === null) return null;
    const accessorialsSum = sumAccessorials(load.accessorialCharges);
    const gross = new Decimal(String(load.customerRate)).plus(accessorialsSum);
    if (gross.isZero()) return null;
    return companyMargin
      .dividedBy(gross)
      .times(100)
      .toDecimalPlaces(2, ROUNDING)
      .toFixed(2);
  })();

  const estimatedNetEarnings =
    financials.estimatedCost !== null
      ? carrierPayout
          .minus(new Decimal(financials.estimatedCost))
          .toDecimalPlaces(2, ROUNDING)
          .toFixed(2)
      : null;

  return { carrierRpm, companyNet, marginPercent, estimatedNetEarnings };
};

/**
 * Picks the 10 cache-equivalent fields off the computed financials, or returns
 * all-nulls when financials couldn't be computed (e.g., customerRate missing).
 */
const pickPersistedShape = (financials: LoadFinancialsResult | null): NullFinancials => {
  if (financials === null) return NULL_FINANCIALS;
  return {
    dispatchFee: financials.dispatchFee,
    partnerSplit: financials.partnerSplit,
    ratePerMile: financials.ratePerMile,
    ratePerTotalMile: financials.ratePerTotalMile,
    carrierPayout: financials.carrierPayout,
    companyMargin: financials.companyMargin,
    driverPay: financials.driverPay,
    estimatedCost: financials.estimatedCost,
    dispatcherComm: financials.dispatcherComm,
  };
};

/**
 * Derives invoiceReadiness on-read (US-11). Mirrors the prior subscriber
 * semantics: an invoice's existence is the strongest signal, otherwise the
 * pure rule in computeInvoiceReadiness runs against the load's documents.
 */
/**
 * Wraps the pure computeInvoiceReadiness rule with the INVOICE_CREATED
 * short-circuit (mirrors prior invoiceReadinessSubscriber semantics — once
 * an invoice exists, readiness is INVOICE_CREATED regardless of doc state).
 */
const deriveInvoiceReadiness = (
  load: LoadWithRelations | LoadListItem,
  documents: { type: string }[],
): InvoiceReadiness => {
  const hasInvoice =
    '_count' in load &&
    load._count !== undefined &&
    'invoices' in load._count &&
    load._count.invoices > 0;
  if (hasInvoice) {
    return 'INVOICE_CREATED';
  }
  return computeInvoiceReadiness(load, documents);
};

export interface LoadDetailTransformerExtras {
  // Optional documents per load — when provided, drives the
  // computeInvoiceReadiness output. Detail callers that load documents (e.g.
  // the load detail GET) should pass them in. Callers that don't will see
  // NOT_READY for non-DELIVERED loads and AWAITING_DOCUMENTS for delivered.
  // Accepts the slim shape used by repo.listDocuments (where `type` is widened
  // to string) as well as full Document rows.
  documents?: { type: string }[];
}

export const toLoadDetailResponse = (
  load: LoadWithRelations,
  extras: LoadDetailTransformerExtras = {},
): LoadDetailResponse => {
  const cargo = computeCommoditySummary(load.stops);
  const financials = tryComputeFinancials(load);
  const derived = buildDerivedFinancials(financials, load);
  const persistedShape = pickPersistedShape(financials);
  const documents = extras.documents ?? [];
  const invoiceReadiness = deriveInvoiceReadiness(load, documents);

  return {
    id: load.id,
    status: load.status,
    version: load.version,
    organizationId: load.organizationId,
    loadNumber: load.loadNumber,
    externalRefNumber: load.externalRefNumber,
    equipmentType: load.equipmentType,
    dispatcherNotes: load.dispatcherNotes,
    driverInstructions: load.driverInstructions,
    createdAt: load.createdAt.toISOString(),
    updatedAt: load.updatedAt.toISOString(),

    route: {
      loadedMiles: load.loadedMiles,
      deadheadMiles: load.deadheadMiles,
      totalMiles: load.totalMiles,
      estimatedHours: load.estimatedHours !== null ? String(load.estimatedHours) : null,
      stops: load.stops.map(toStopResponse),
    },

    cargo: {
      commodity: cargo.commodity,
      weight: cargo.weight,
      pieceCount: cargo.pieceCount,
      isHazmat: cargo.isHazmat,
      isTarp: cargo.isTarp,
      isTempControlled: load.stops.some((stop) => stop.isTempControlled),
    },

    financials: {
      customerRate: load.customerRate !== null ? String(load.customerRate) : null,
      carrierRate: load.carrierRate !== null ? String(load.carrierRate) : null,
      // The 10 cache-equivalent output fields are now derived per request via
      // computeLoadFinancials (US-11). Field names are unchanged for UI parity.
      ...persistedShape,
      dispatchFeeType: load.dispatchFeeType,
      dispatchFeeAmount:
        load.dispatchFeeAmount !== null ? String(load.dispatchFeeAmount) : null,
      partnerSplitPercent:
        load.partnerSplitPercent !== null ? String(load.partnerSplitPercent) : null,
      driverPayType: load.driverPayType,
      driverPayRate: load.driverPayRate !== null ? String(load.driverPayRate) : null,
      dispatcherCommissionType: load.dispatcherCommissionType,
      dispatcherCommissionRate:
        load.dispatcherCommissionRate !== null ? String(load.dispatcherCommissionRate) : null,
      feeIncludesAccessorials: load.feeIncludesAccessorials,
      payFromNet: load.payFromNet,
      ...derived,
    },

    assignment: {
      carrier:
        load.carrier !== null
          ? {
              id: load.carrier.id,
              name: load.carrier.name,
              type: load.carrier.type,
              dispatchFeePercent: String(load.carrier.dispatchFeePercent),
              partnerSplitPercent: String(load.carrier.partnerSplitPercent),
              feeIncludesAccessorials: load.carrier.feeIncludesAccessorials,
              payFromNet: load.carrier.payFromNet,
            }
          : null,
      driver:
        load.driver !== null
          ? (() => {
              const position = pickLatestDriverPosition(load);
              return {
                id: load.driver.id,
                firstName: load.driver.firstName,
                lastName: load.driver.lastName,
                phone: load.driver.phone ?? null,
                currentLatitude: position.latitude,
                currentLongitude: position.longitude,
              };
            })()
          : null,
      vehicle:
        load.vehicle !== null
          ? { id: load.vehicle.id, unitNumber: load.vehicle.unitNumber, type: load.vehicle.type }
          : null,
      dispatcher:
        load.dispatcher !== null
          ? {
              id: load.dispatcher.id,
              firstName: load.dispatcher.firstName,
              lastName: load.dispatcher.lastName,
            }
          : null,
      isTeamDriver: load.isTeamDriver,
    },

    customer:
      load.customer !== null
        ? { id: load.customer.id, companyName: load.customer.companyName }
        : null,

    contact:
      load.contact !== null
        ? {
            id: load.contact.id,
            firstName: load.contact.firstName,
            lastName: load.contact.lastName,
            role: load.contact.role ?? null,
            phone: load.contact.phone ?? null,
            email: load.contact.email ?? null,
          }
        : null,

    tracking: {
      // invoiceReadiness is computed on-read (US-11). Persisted column was
      // never populated in production (US-08 discovery).
      invoiceReadiness,
      rateConReceivedAt: load.rateConReceivedAt?.toISOString() ?? null,
      bolUnsignedAt: load.bolUnsignedAt?.toISOString() ?? null,
      bolSignedAt: load.bolSignedAt?.toISOString() ?? null,
    },

    activity: {
      statusHistory: load.statusHistory.map(toStatusHistoryResponse),
      checkCalls: load.checkCalls.map(toCheckCallResponse),
      accessorialCharges: load.accessorialCharges.map(toAccessorialChargeResponse),
    },
  };
};

// ---------------------------------------------------------------------------
// List item response — structural subset of detail
// ---------------------------------------------------------------------------

/**
 * List variant of tryComputeFinancials — LoadListItem includes only the slim
 * accessorialCharges amount projection but otherwise has the same snapshot
 * shape as a full Load row.
 */
const tryComputeListFinancials = (load: LoadListItem): LoadFinancialsResult | null => {
  if (load.customerRate === null) {
    return null;
  }
  // LoadListItem.accessorialCharges is the slim { amount } projection, which
  // computeLoadFinancials only needs via sumAccessorials.
  const accessorialsSum = sumAccessorials(load.accessorialCharges);
  // LoadListItem extends Load — every snapshot input column is present on
  // the row (customerRate, dispatchFeeType, carrierType, etc.). The compute
  // fn never reads the 10 output cache columns.
  return computeLoadFinancials(load, accessorialsSum);
};

export const toLoadListItemResponse = (load: LoadListItem): LoadListItemResponse => {
  const cargo = computeCommoditySummary(load.stops);
  const financials = tryComputeListFinancials(load);
  const persisted = pickPersistedShape(financials);

  const companyMargin = financials !== null ? new Decimal(financials.companyMargin) : null;
  const dispatcherCommStr = financials?.dispatcherComm ?? null;

  const companyNet =
    companyMargin !== null && dispatcherCommStr !== null
      ? companyMargin
          .minus(new Decimal(dispatcherCommStr))
          .toDecimalPlaces(2, ROUNDING)
          .toFixed(2)
      : null;

  // List endpoints don't currently fetch documents per load — readiness is
  // computed from status + invoice presence only (DELIVERED/INVOICE_PENDING
  // without docs → AWAITING_DOCUMENTS). Matches reality without an N+1 fetch.
  const invoiceReadiness = deriveInvoiceReadiness(load, []);

  return {
    id: load.id,
    loadNumber: load.loadNumber,
    status: load.status,
    equipmentType: load.equipmentType,
    invoiceReadiness,
    accessorialChargeCount: load._count.accessorialCharges,
    createdAt: load.createdAt.toISOString(),
    updatedAt: load.updatedAt.toISOString(),

    route: {
      totalMiles: load.totalMiles,
      stops: load.stops.map(toStopResponse),
    },

    cargo: {
      commodity: cargo.commodity ?? null,
      weight: cargo.weight ?? null,
      pieceCount: cargo.pieceCount ?? null,
      isHazmat: cargo.isHazmat,
      isTarp: cargo.isTarp,
    },

    financials: {
      customerRate: load.customerRate !== null ? String(load.customerRate) : null,
      carrierRate: load.carrierRate !== null ? String(load.carrierRate) : null,
      ratePerMile: persisted.ratePerMile,
      ratePerTotalMile: persisted.ratePerTotalMile,
      companyMargin: persisted.companyMargin,
      carrierPayout: persisted.carrierPayout,
      companyNet,
    },

    assignment: {
      carrier:
        load.carrier !== null ? { id: load.carrier.id, name: load.carrier.name } : null,
      driver:
        load.driver !== null
          ? {
              id: load.driver.id,
              firstName: load.driver.firstName,
              lastName: load.driver.lastName,
            }
          : null,
      dispatcher:
        load.dispatcher !== null
          ? {
              id: load.dispatcher.id,
              firstName: load.dispatcher.firstName,
              lastName: load.dispatcher.lastName,
            }
          : null,
    },

    customer:
      load.customer !== null
        ? { id: load.customer.id, companyName: load.customer.companyName }
        : null,

    contact:
      load.contact !== null
        ? {
            id: load.contact.id,
            firstName: load.contact.firstName,
            lastName: load.contact.lastName,
            email: load.contact.email ?? null,
            phone: load.contact.phone ?? null,
          }
        : null,
  };
};

export const toLoadListEnvelope = (
  loads: LoadListItem[],
  meta: PaginationMeta,
): { data: LoadListItemResponse[]; meta: PaginationMeta } => ({
  data: loads.map(toLoadListItemResponse),
  meta,
});
