import { Decimal } from 'decimal.js';
import type { PaginationMeta } from '@/shared/responseEnvelope';
import { computeCommoditySummary } from '@/shared/utils/computeCommoditySummary';
import type {
  LoadListItem,
  LoadWithRelations,
  LoadDetailResponse,
  LoadListItemResponse,
  StopResponse,
  AccessorialChargeResponse,
  CheckCallResponse,
  StatusHistoryResponse,
} from '../../types/loadTypes';

const ROUNDING = Decimal.ROUND_HALF_EVEN;

const toCoord = (val: unknown): number | null => {
  if (val === null || val === undefined) return null;
  const num = Number(val);
  return Number.isFinite(num) ? num : null;
};

const toStopResponse = (stop: LoadWithRelations['stops'][number]): StopResponse => ({
  id: stop.id,
  type: stop.type,
  sequence: stop.sequence,
  contactId: stop.contactId,
  placeId: stop.placeId,
  facilityName: stop.facilityName,
  address: stop.address,
  city: stop.city,
  state: stop.state,
  zip: stop.zip,
  schedulingType: stop.schedulingType,
  appointmentStart: stop.appointmentStart?.toISOString() ?? null,
  appointmentEnd: stop.appointmentEnd?.toISOString() ?? null,
  targetDate: stop.targetDate?.toISOString() ?? null,
  notificationHours: stop.notificationHours,
  notifiedAt: stop.notifiedAt?.toISOString() ?? null,
  appointmentNumber: stop.appointmentNumber,
  arrivalTime: stop.arrivalTime?.toISOString() ?? null,
  departureTime: stop.departureTime?.toISOString() ?? null,
  contactName: stop.contactName,
  contactPhone: stop.contactPhone,
  commodity: stop.commodity,
  weight: stop.weight,
  pieceCount: stop.pieceCount,
  isHazmat: stop.isHazmat,
  isTarp: stop.isTarp,
  isTempControlled: stop.isTempControlled,
  notes: stop.notes,
  facilityOpenTime: stop.facilityOpenTime,
  facilityCloseTime: stop.facilityCloseTime,
  callByTime: stop.callByTime,
  trailerNumber: stop.trailerNumber,
  yardLocation: stop.yardLocation,
  createdAt: stop.createdAt.toISOString(),
  updatedAt: stop.updatedAt.toISOString(),
});

const toAccessorialChargeResponse = (
  charge: LoadWithRelations['accessorialCharges'][number],
): AccessorialChargeResponse => ({
  id: charge.id,
  type: charge.type,
  description: charge.description,
  amount: String(charge.amount),
  billTo: charge.billTo,
  approvalStatus: charge.approvalStatus,
  stopId: charge.stopId,
  isAutoGenerated: charge.isAutoGenerated,
  createdAt: charge.createdAt.toISOString(),
  updatedAt: charge.updatedAt.toISOString(),
});

const toCheckCallResponse = (call: LoadWithRelations['checkCalls'][number]): CheckCallResponse => ({
  id: call.id,
  location: call.location,
  latitude: toCoord(call.latitude),
  longitude: toCoord(call.longitude),
  status: call.status,
  eta: call.eta?.toISOString() ?? null,
  notes: call.notes,
  brokerNotified: call.brokerNotified,
  brokerNotes: call.brokerNotes,
  calledByUserId: call.calledByUserId,
  calledByName: call.calledBy ? `${call.calledBy.firstName} ${call.calledBy.lastName}` : null,
  createdAt: call.createdAt.toISOString(),
});

const toStatusHistoryResponse = (
  entry: LoadWithRelations['statusHistory'][number],
): StatusHistoryResponse => ({
  id: entry.id,
  fromStatus: entry.fromStatus,
  toStatus: entry.toStatus,
  notes: entry.notes,
  changedByUserId: entry.changedByUserId,
  changedByName: entry.changedBy
    ? `${entry.changedBy.firstName} ${entry.changedBy.lastName}`
    : null,
  createdAt: entry.createdAt.toISOString(),
});

const computeDerivedFinancials = (load: LoadWithRelations) => {
  const carrierRpm =
    load.carrierPayout !== null && load.loadedMiles !== null && load.loadedMiles !== 0
      ? new Decimal(String(load.carrierPayout))
          .dividedBy(load.loadedMiles)
          .toDecimalPlaces(2, ROUNDING)
          .toFixed(2)
      : null;

  const companyNet =
    load.companyMargin !== null && load.dispatcherComm !== null
      ? new Decimal(String(load.companyMargin))
          .minus(new Decimal(String(load.dispatcherComm)))
          .toDecimalPlaces(2, ROUNDING)
          .toFixed(2)
      : null;

  const marginPercent = (() => {
    if (load.companyMargin === null || load.customerRate === null) return null;
    const accessorialsSum = load.accessorialCharges.reduce(
      (sum, charge) => sum.plus(new Decimal(String(charge.amount))),
      new Decimal(0),
    );
    const gross = new Decimal(String(load.customerRate)).plus(accessorialsSum);
    if (gross.isZero()) return null;
    return new Decimal(String(load.companyMargin))
      .dividedBy(gross)
      .times(100)
      .toDecimalPlaces(2, ROUNDING)
      .toFixed(2);
  })();

  const estimatedNetEarnings =
    load.carrierPayout !== null && load.estimatedCost !== null
      ? new Decimal(String(load.carrierPayout))
          .minus(new Decimal(String(load.estimatedCost)))
          .toDecimalPlaces(2, ROUNDING)
          .toFixed(2)
      : null;

  return { carrierRpm, companyNet, marginPercent, estimatedNetEarnings };
};

export const toLoadDetailResponse = (load: LoadWithRelations): LoadDetailResponse => {
  const cargo = computeCommoditySummary(load.stops);
  const derived = computeDerivedFinancials(load);

  return {
    id: load.id,
    status: load.status,
    organizationId: load.organizationId,
    loadNumber: load.loadNumber,
    externalRefNumber: load.externalRefNumber,
    equipmentType: load.equipmentType,
    dispatcherNotes: load.dispatcherNotes,
    driverInstructions: load.driverInstructions,
    createdAt: load.createdAt.toISOString(),
    updatedAt: load.updatedAt.toISOString(),

    route: {
      loadedMiles: load.loadedMiles,
      deadheadMiles: load.deadheadMiles,
      totalMiles: load.totalMiles,
      estimatedHours: load.estimatedHours !== null ? String(load.estimatedHours) : null,
      stops: load.stops.map(toStopResponse),
    },

    cargo: {
      commodity: cargo.commodity,
      weight: cargo.weight,
      pieceCount: cargo.pieceCount,
      isHazmat: cargo.isHazmat,
      isTarp: cargo.isTarp,
      isTempControlled: load.stops.some((stop) => stop.isTempControlled),
    },

    financials: {
      customerRate: load.customerRate !== null ? String(load.customerRate) : null,
      carrierRate: load.carrierRate !== null ? String(load.carrierRate) : null,
      dispatchFee: load.dispatchFee !== null ? String(load.dispatchFee) : null,
      partnerSplit: load.partnerSplit !== null ? String(load.partnerSplit) : null,
      ratePerMile: load.ratePerMile !== null ? String(load.ratePerMile) : null,
      ratePerTotalMile: load.ratePerTotalMile !== null ? String(load.ratePerTotalMile) : null,
      carrierPayout: load.carrierPayout !== null ? String(load.carrierPayout) : null,
      companyMargin: load.companyMargin !== null ? String(load.companyMargin) : null,
      driverPay: load.driverPay !== null ? String(load.driverPay) : null,
      dispatcherComm: load.dispatcherComm !== null ? String(load.dispatcherComm) : null,
      estimatedCost: load.estimatedCost !== null ? String(load.estimatedCost) : null,
      ...derived,
    },

    assignment: {
      carrier:
        load.carrier !== null
          ? {
              id: load.carrier.id,
              name: load.carrier.name,
              type: load.carrier.type,
              dispatchFeePercent: String(load.carrier.dispatchFeePercent),
              partnerSplitPercent: String(load.carrier.partnerSplitPercent),
              feeIncludesAccessorials: load.carrier.feeIncludesAccessorials,
              feeType: load.carrier.feeType,
              payFromNet: load.carrier.payFromNet,
            }
          : null,
      driver:
        load.driver !== null
          ? { id: load.driver.id, firstName: load.driver.firstName, lastName: load.driver.lastName }
          : null,
      vehicle:
        load.vehicle !== null
          ? { id: load.vehicle.id, unitNumber: load.vehicle.unitNumber, type: load.vehicle.type }
          : null,
      isTeamDriver: load.isTeamDriver,
    },

    customer:
      load.customer !== null
        ? { id: load.customer.id, companyName: load.customer.companyName }
        : null,

    contact:
      load.contact !== null
        ? {
            id: load.contact.id,
            firstName: load.contact.firstName,
            lastName: load.contact.lastName,
            role: load.contact.role ?? null,
            phone: load.contact.phone ?? null,
            email: load.contact.email ?? null,
          }
        : null,

    tracking: {
      invoiceReadiness: load.invoiceReadiness,
      rateConReceivedAt: load.rateConReceivedAt?.toISOString() ?? null,
      bolUnsignedAt: load.bolUnsignedAt?.toISOString() ?? null,
      bolSignedAt: load.bolSignedAt?.toISOString() ?? null,
    },

    activity: {
      statusHistory: load.statusHistory.map(toStatusHistoryResponse),
      checkCalls: load.checkCalls.map(toCheckCallResponse),
      accessorialCharges: load.accessorialCharges.map(toAccessorialChargeResponse),
    },
  };
};

// ---------------------------------------------------------------------------
// List item response
// ---------------------------------------------------------------------------

interface StopSummary {
  city: string | null;
  state: string | null;
  appointmentStart: Date | null;
  schedulingType: string | null;
  latitude: number | null;
  longitude: number | null;
}

const getOriginStop = (stops: LoadListItem['stops']): StopSummary => {
  const pickup = stops.find((stop) => stop.type === 'PICKUP');
  if (pickup !== undefined) {
    return {
      city: pickup.city,
      state: pickup.state,
      appointmentStart: pickup.appointmentStart,
      schedulingType: pickup.schedulingType,
      latitude: toCoord(pickup.place?.latitude),
      longitude: toCoord(pickup.place?.longitude),
    };
  }
  return {
    city: null,
    state: null,
    appointmentStart: null,
    schedulingType: null,
    latitude: null,
    longitude: null,
  };
};

const getDestinationStop = (stops: LoadListItem['stops']): StopSummary => {
  const deliveries = stops.filter((stop) => stop.type === 'DELIVERY');
  const lastDelivery = deliveries[deliveries.length - 1];
  if (lastDelivery !== undefined) {
    return {
      city: lastDelivery.city,
      state: lastDelivery.state,
      appointmentStart: lastDelivery.appointmentStart,
      schedulingType: lastDelivery.schedulingType,
      latitude: toCoord(lastDelivery.place?.latitude),
      longitude: toCoord(lastDelivery.place?.longitude),
    };
  }
  return {
    city: null,
    state: null,
    appointmentStart: null,
    schedulingType: null,
    latitude: null,
    longitude: null,
  };
};

export const toLoadListItemResponse = (load: LoadListItem): LoadListItemResponse => {
  const origin = getOriginStop(load.stops);
  const destination = getDestinationStop(load.stops);
  const cargo = computeCommoditySummary(load.stops);

  return {
    id: load.id,
    loadNumber: load.loadNumber,
    status: load.status,
    equipmentType: load.equipmentType,
    invoiceReadiness: load.invoiceReadiness,
    accessorialChargeCount: load._count.accessorialCharges,
    createdAt: load.createdAt.toISOString(),
    updatedAt: load.updatedAt.toISOString(),

    route: {
      originCity: origin.city,
      originState: origin.state,
      destinationCity: destination.city,
      destinationState: destination.state,
      totalMiles: load.totalMiles,
      pickupDate: origin.appointmentStart?.toISOString() ?? null,
      pickupSchedulingType: origin.schedulingType,
      deliveryDate: destination.appointmentStart?.toISOString() ?? null,
      deliverySchedulingType: destination.schedulingType,
      originLat: origin.latitude,
      originLng: origin.longitude,
      destLat: destination.latitude,
      destLng: destination.longitude,
    },

    cargo: {
      commodity: cargo.commodity ?? null,
      weight: cargo.weight ?? null,
      pieceCount: cargo.pieceCount ?? null,
      isHazmat: cargo.isHazmat,
      isTarp: cargo.isTarp,
    },

    financials: {
      customerRate: load.customerRate !== null ? String(load.customerRate) : null,
      carrierRate: load.carrierRate !== null ? String(load.carrierRate) : null,
      ratePerMile: load.ratePerMile !== null ? String(load.ratePerMile) : null,
      ratePerTotalMile: load.ratePerTotalMile !== null ? String(load.ratePerTotalMile) : null,
      companyMargin: load.companyMargin !== null ? String(load.companyMargin) : null,
      carrierPayout: load.carrierPayout !== null ? String(load.carrierPayout) : null,
      companyNet:
        load.companyMargin !== null && load.dispatcherComm !== null
          ? new Decimal(String(load.companyMargin))
              .minus(new Decimal(String(load.dispatcherComm)))
              .toDecimalPlaces(2, Decimal.ROUND_HALF_EVEN)
              .toFixed(2)
          : null,
    },

    assignment: {
      carrierId: load.carrierId,
      carrierName: load.carrier?.name ?? null,
      driverId: load.driverId,
      driverName: load.driver !== null ? `${load.driver.firstName} ${load.driver.lastName}` : null,
    },

    customer: {
      customerName: load.customer?.companyName ?? null,
      contactName: load.contact
        ? `${load.contact.firstName} ${load.contact.lastName}`.trim()
        : null,
      contactEmail: load.contact?.email ?? null,
      contactPhone: load.contact?.phone ?? null,
    },
  };
};

export const toLoadListEnvelope = (
  loads: LoadListItem[],
  meta: PaginationMeta,
): { data: LoadListItemResponse[]; meta: PaginationMeta } => ({
  data: loads.map(toLoadListItemResponse),
  meta,
});
