import type { PaginationMeta } from '@/shared/responseEnvelope';
import type { LoadListItem, LoadWithRelations } from '../../types/loadTypes';

export interface StopResponse {
  id: string;
  type: string;
  sequence: number;
  contactId: string | null;
  placeId: string | null;
  facilityName: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  appointmentDate: string | null;
  appointmentTime: string | null;
  appointmentNumber: string | null;
  arrivalTime: string | null;
  departureTime: string | null;
  contactName: string | null;
  contactPhone: string | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface AccessorialChargeResponse {
  id: string;
  type: string;
  description: string | null;
  amount: unknown;
  billTo: string;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface LoadDetailResponse {
  id: string;
  organizationId: string;
  loadNumber: string;
  carrierId: string | null;
  driverId: string | null;
  vehicleId: string | null;
  brokerId: string | null;
  shipperId: string | null;
  consigneeId: string | null;
  brokerRefNumber: string | null;
  equipmentType: string | null;
  isHazmat: boolean;
  isTarp: boolean;
  isTeamDriver: boolean;
  commodity: string | null;
  weight: number | null;
  pieceCount: number | null;
  loadedMiles: number | null;
  deadheadMiles: number | null;
  totalMiles: number | null;
  customerRate: unknown;
  carrierRate: unknown;
  dispatchFee: unknown;
  partnerSplit: unknown;
  ratePerMile: unknown;
  status: string;
  rateConReceivedAt: string | null;
  bolUnsignedAt: string | null;
  bolSignedAt: string | null;
  dispatcherNotes: string | null;
  driverInstructions: string | null;
  createdAt: string;
  updatedAt: string;
  stops: StopResponse[];
  carrier: { id: string; name: string } | null;
  driver: { id: string; firstName: string; lastName: string } | null;
  vehicle: { id: string; unitNumber: string; type: string } | null;
  broker: { id: string; companyName: string } | null;
  shipper: { id: string; companyName: string } | null;
  consignee: { id: string; companyName: string } | null;
  statusHistory: { id: string; fromStatus: string | null; toStatus: string; notes: string | null; createdAt: string }[];
  checkCalls: { id: string; location: string | null; status: string | null; eta: string | null; notes: string | null; createdAt: string }[];
  accessorialCharges: AccessorialChargeResponse[];
}

const toStopResponse = (stop: LoadWithRelations['stops'][number]): StopResponse => ({
  id: stop.id,
  type: stop.type,
  sequence: stop.sequence,
  contactId: stop.contactId,
  placeId: stop.placeId,
  facilityName: stop.facilityName,
  address: stop.address,
  city: stop.city,
  state: stop.state,
  zip: stop.zip,
  appointmentDate: stop.appointmentDate?.toISOString() ?? null,
  appointmentTime: stop.appointmentTime,
  appointmentNumber: stop.appointmentNumber,
  arrivalTime: stop.arrivalTime?.toISOString() ?? null,
  departureTime: stop.departureTime?.toISOString() ?? null,
  contactName: stop.contactName,
  contactPhone: stop.contactPhone,
  notes: stop.notes,
  createdAt: stop.createdAt.toISOString(),
  updatedAt: stop.updatedAt.toISOString(),
});

const toAccessorialChargeResponse = (
  charge: LoadWithRelations['accessorialCharges'][number],
): AccessorialChargeResponse => ({
  id: charge.id,
  type: charge.type,
  description: charge.description,
  amount: charge.amount,
  billTo: charge.billTo,
  isAutoGenerated: charge.isAutoGenerated,
  createdAt: charge.createdAt.toISOString(),
  updatedAt: charge.updatedAt.toISOString(),
});

export const toLoadDetailResponse = (load: LoadWithRelations): LoadDetailResponse => ({
  id: load.id,
  organizationId: load.organizationId,
  loadNumber: load.loadNumber,
  carrierId: load.carrierId,
  driverId: load.driverId,
  vehicleId: load.vehicleId,
  brokerId: load.brokerId,
  shipperId: load.shipperId,
  consigneeId: load.consigneeId,
  brokerRefNumber: load.brokerRefNumber,
  equipmentType: load.equipmentType,
  isHazmat: load.isHazmat,
  isTarp: load.isTarp,
  isTeamDriver: load.isTeamDriver,
  commodity: load.commodity,
  weight: load.weight,
  pieceCount: load.pieceCount,
  loadedMiles: load.loadedMiles,
  deadheadMiles: load.deadheadMiles,
  totalMiles: load.totalMiles,
  customerRate: load.customerRate,
  carrierRate: load.carrierRate,
  dispatchFee: load.dispatchFee,
  partnerSplit: load.partnerSplit,
  ratePerMile: load.ratePerMile,
  status: load.status,
  rateConReceivedAt: load.rateConReceivedAt?.toISOString() ?? null,
  bolUnsignedAt: load.bolUnsignedAt?.toISOString() ?? null,
  bolSignedAt: load.bolSignedAt?.toISOString() ?? null,
  dispatcherNotes: load.dispatcherNotes,
  driverInstructions: load.driverInstructions,
  createdAt: load.createdAt.toISOString(),
  updatedAt: load.updatedAt.toISOString(),
  stops: load.stops.map(toStopResponse),
  carrier: load.carrier !== null
    ? { id: load.carrier.id, name: load.carrier.name }
    : null,
  driver: load.driver !== null
    ? { id: load.driver.id, firstName: load.driver.firstName, lastName: load.driver.lastName }
    : null,
  vehicle: load.vehicle !== null
    ? { id: load.vehicle.id, unitNumber: load.vehicle.unitNumber, type: load.vehicle.type }
    : null,
  broker: load.broker !== null
    ? { id: load.broker.id, companyName: load.broker.companyName }
    : null,
  shipper: load.shipper !== null
    ? { id: load.shipper.id, companyName: load.shipper.companyName }
    : null,
  consignee: load.consignee !== null
    ? { id: load.consignee.id, companyName: load.consignee.companyName }
    : null,
  statusHistory: load.statusHistory.map((entry) => ({
    id: entry.id,
    fromStatus: entry.fromStatus,
    toStatus: entry.toStatus,
    notes: entry.notes,
    createdAt: entry.createdAt.toISOString(),
  })),
  checkCalls: load.checkCalls.map((call) => ({
    id: call.id,
    location: call.location,
    status: call.status,
    eta: call.eta?.toISOString() ?? null,
    notes: call.notes,
    createdAt: call.createdAt.toISOString(),
  })),
  accessorialCharges: load.accessorialCharges.map(toAccessorialChargeResponse),
});

export interface LoadListItemResponse {
  id: string;
  loadNumber: string;
  status: string;
  equipmentType: string | null;
  commodity: string | null;
  customerRate: unknown;
  carrierRate: unknown;
  totalMiles: number | null;
  ratePerMile: unknown;
  carrierId: string | null;
  carrierName: string | null;
  driverId: string | null;
  driverName: string | null;
  originCity: string | null;
  originState: string | null;
  destinationCity: string | null;
  destinationState: string | null;
  accessorialChargeCount: number;
  createdAt: string;
  updatedAt: string;
}

const getOriginStop = (stops: LoadListItem['stops']): { city: string | null; state: string | null } => {
  const pickup = stops.find((stop) => stop.type === 'PICKUP');
  if (pickup !== undefined) {
    return { city: pickup.city, state: pickup.state };
  }
  return { city: null, state: null };
};

const getDestinationStop = (stops: LoadListItem['stops']): { city: string | null; state: string | null } => {
  const deliveries = stops.filter((stop) => stop.type === 'DELIVERY');
  const lastDelivery = deliveries[deliveries.length - 1];
  if (lastDelivery !== undefined) {
    return { city: lastDelivery.city, state: lastDelivery.state };
  }
  return { city: null, state: null };
};

export const toLoadListItemResponse = (load: LoadListItem): LoadListItemResponse => {
  const origin = getOriginStop(load.stops);
  const destination = getDestinationStop(load.stops);

  return {
    id: load.id,
    loadNumber: load.loadNumber,
    status: load.status,
    equipmentType: load.equipmentType,
    commodity: load.commodity,
    customerRate: load.customerRate,
    carrierRate: load.carrierRate,
    totalMiles: load.totalMiles,
    ratePerMile: load.ratePerMile,
    carrierId: load.carrierId,
    carrierName: load.carrier?.name ?? null,
    driverId: load.driverId,
    driverName: load.driver !== null
      ? `${load.driver.firstName} ${load.driver.lastName}`
      : null,
    originCity: origin.city,
    originState: origin.state,
    destinationCity: destination.city,
    destinationState: destination.state,
    accessorialChargeCount: load._count.accessorialCharges,
    createdAt: load.createdAt.toISOString(),
    updatedAt: load.updatedAt.toISOString(),
  };
};

export const toLoadListEnvelope = (
  loads: LoadListItem[],
  meta: PaginationMeta,
): { data: LoadListItemResponse[]; meta: PaginationMeta } => ({
  data: loads.map(toLoadListItemResponse),
  meta,
});
