import { ExpenseCategory } from '@prisma/client';

export const CPM_CATEGORY_MAP: Record<ExpenseCategory, 'FIXED' | 'VARIABLE'> = {
  FUEL: 'VARIABLE',
  MAINTENANCE: 'VARIABLE',
  TOLLS: 'VARIABLE',
  PARKING: 'VARIABLE',
  MEALS: 'VARIABLE',
  INSURANCE: 'FIXED',
  TRUCK_PAYMENT: 'FIXED',
  TRAILER_RENTAL: 'FIXED',
  PERMITS_TAGS: 'FIXED',
  SCALES: 'VARIABLE',
  LUMPER: 'VARIABLE',
  TIRES: 'VARIABLE',
  OIL_CHANGE: 'VARIABLE',
  DEF_FLUID: 'VARIABLE',
  TRUCK_WASH: 'VARIABLE',
  ELD_SUBSCRIPTION: 'FIXED',
  PHONE: 'FIXED',
  LODGING: 'VARIABLE',
  FACTORING_FEE: 'FIXED',
  OTHER: 'VARIABLE',
};
