FROM node:22-alpine

WORKDIR /usr/app

COPY package.json package-lock.json ./

RUN npm ci
RUN npm install --os=linux --cpu=arm64 @rollup/rollup-linux-arm64-musl || true

COPY . .
# COPY mocho-ui/ ./mocho-ui/
# COPY hussle-app-dispatch-ui/ ./hussle-app-dispatch-ui/

# WORKDIR /app/hussle-app-dispatch-ui

EXPOSE 5173

CMD ["npx", "vite", "--host", "0.0.0.0", "--force"]
