import Decimal from 'decimal.js';
import { DispatchFeeType } from '@prisma/client';
import { createInvoiceBuilderService } from '../invoiceBuilderService';
import type {
  InvoiceRepoPort,
  InvoiceLoadQueryPort,
  InvoiceWithRelations,
} from '../../types/invoiceTypes';
import type { Logger } from '../../../shared/utils/logger';

jest.mock('../../../shared/sequenceGenerator', () => ({
  generateSequenceNumber: jest.fn().mockResolvedValue('INV-0001'),
}));

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const buildMockDeps = () => {
  const invoiceRepo: jest.Mocked<
    Pick<InvoiceRepoPort, 'create' | 'findNonVoidByLoadId' | 'findById' | 'updateStatus'>
  > = {
    create: jest.fn(),
    findNonVoidByLoadId: jest.fn().mockResolvedValue(null),
    findById: jest.fn(),
    updateStatus: jest.fn(),
  };

  const loadQuery: jest.Mocked<
    Pick<InvoiceLoadQueryPort, 'findLoadById' | 'updateLoadStatus'>
  > = {
    findLoadById: jest.fn(),
    updateLoadStatus: jest.fn().mockResolvedValue(undefined),
  };

  const logger: jest.Mocked<Logger> = {
    info: jest.fn(),
    debug: jest.fn(),
    warn: jest.fn(),
    error: jest.fn(),
  };

  return {
    invoiceRepo: invoiceRepo as unknown as jest.Mocked<InvoiceRepoPort>,
    loadQuery: loadQuery as unknown as jest.Mocked<InvoiceLoadQueryPort>,
    logger,
  };
};

interface AccessorialInput {
  amount: string;
  billTo: string;
  type?: string;
}

const makeAccessorial = (a: AccessorialInput) => ({
  id: `acc-${a.billTo}-${a.amount}`,
  loadId: 'load-1',
  type: a.type ?? 'DETENTION',
  description: null,
  amount: a.amount,
  billTo: a.billTo,
  isAutoGenerated: false,
  approvalStatus: 'APPROVED',
  approvalSource: null,
  approvalNotes: null,
  documentId: null,
  stopId: null,
  createdAt: new Date(),
  updatedAt: new Date(),
});

type LoadFindResult = Awaited<ReturnType<InvoiceLoadQueryPort['findLoadById']>>;

const makeLoad = (overrides: {
  carrierType: string;
  customerRate?: string;
  dispatchFeeType?: 'PERCENTAGE' | 'FLAT';
  dispatchFeePercent?: string;
  dispatchFeeAmount?: string;
  feeIncludesAccessorials?: boolean;
  accessorials?: AccessorialInput[];
}): LoadFindResult => ({
  id: 'load-1',
  organizationId: 'org-1',
  loadNumber: 'LD-001',
  carrierId: 'carrier-1',
  customerId: 'customer-1',
  vehicleId: null,
  customerRate: overrides.customerRate ?? '0',
  carrierRate: null,
  dispatchFee: null,
  dispatchFeeOverrideType: null,
  dispatchFeeOverrideAmount: null,
  bolSignedAt: new Date(),
  status: 'DELIVERED',
  contact: null,
  carrier: {
    id: 'carrier-1',
    name: 'Acme',
    type: overrides.carrierType,
    billingMethod: 'DIRECT',
    dispatchFeeType:
      overrides.dispatchFeeType === 'FLAT'
        ? DispatchFeeType.FLAT
        : DispatchFeeType.PERCENTAGE,
    dispatchFeePercent: overrides.dispatchFeePercent ?? '10',
    dispatchFeeAmount: overrides.dispatchFeeAmount ?? '0',
    feeIncludesAccessorials: overrides.feeIncludesAccessorials ?? true,
    primaryContact: { id: 'ct-1', email: 'carrier@acme.com' },
  },
  customer: {
    id: 'customer-1',
    email: null,
    paymentTerms: 'net_30',
    paymentTermsDays: 30,
    billingMethod: 'DIRECT',
  },
  accessorialCharges: (overrides.accessorials ?? []).map(makeAccessorial) as LoadFindResult extends {
    accessorialCharges: infer A;
  }
    ? A
    : never,
});

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('invoiceBuilderService.createFromLoadWithFee', () => {
  let deps: ReturnType<typeof buildMockDeps>;

  beforeEach(() => {
    jest.clearAllMocks();
    deps = buildMockDeps();
    deps.invoiceRepo.create.mockImplementation(
      async (data) => ({ id: 'inv-1', ...data } as unknown as InvoiceWithRelations),
    );
  });

  it('computes PERCENTAGE fee on customerRate + customer accessorials when feeIncludesAccessorials=true', async () => {
    // Arrange: 15% of ($3,000 + $200) = $480
    deps.loadQuery.findLoadById.mockResolvedValue(
      makeLoad({
        carrierType: 'EXTERNAL_CARRIER',
        customerRate: '3000',
        dispatchFeeType: 'PERCENTAGE',
        dispatchFeePercent: '15',
        feeIncludesAccessorials: true,
        accessorials: [{ amount: '200', billTo: 'CUSTOMER' }],
      }),
    );
    const service = createInvoiceBuilderService(deps);

    // Act
    const result = await service.createFromLoadWithFee({
      loadId: 'load-1',
      organizationId: 'org-1',
      userId: 'system',
    });

    // Assert
    expect(result.dispatchFeeAmount).not.toBeNull();
    expect(new Decimal(result.dispatchFeeAmount!.toString()).toNumber()).toBeCloseTo(480, 2);
  });

  it('computes PERCENTAGE fee on customerRate only when feeIncludesAccessorials=false', async () => {
    // Arrange: 15% of $3,000 = $450
    deps.loadQuery.findLoadById.mockResolvedValue(
      makeLoad({
        carrierType: 'EXTERNAL_CARRIER',
        customerRate: '3000',
        dispatchFeeType: 'PERCENTAGE',
        dispatchFeePercent: '15',
        feeIncludesAccessorials: false,
        accessorials: [{ amount: '200', billTo: 'CUSTOMER' }],
      }),
    );
    const service = createInvoiceBuilderService(deps);

    // Act
    const result = await service.createFromLoadWithFee({
      loadId: 'load-1',
      organizationId: 'org-1',
      userId: 'system',
    });

    // Assert
    expect(new Decimal(result.dispatchFeeAmount!.toString()).toNumber()).toBeCloseTo(450, 2);
  });

  it('uses FLAT fee regardless of base or feeIncludesAccessorials flag', async () => {
    deps.loadQuery.findLoadById.mockResolvedValue(
      makeLoad({
        carrierType: 'EXTERNAL_CARRIER',
        customerRate: '3000',
        dispatchFeeType: 'FLAT',
        dispatchFeeAmount: '300',
        feeIncludesAccessorials: true,
        accessorials: [{ amount: '200', billTo: 'CUSTOMER' }],
      }),
    );
    const service = createInvoiceBuilderService(deps);

    const result = await service.createFromLoadWithFee({
      loadId: 'load-1',
      organizationId: 'org-1',
      userId: 'system',
    });

    expect(new Decimal(result.dispatchFeeAmount!.toString()).toNumber()).toBeCloseTo(300, 2);
  });

  it('excludes CARRIER-billed accessorials from the CUSTOMER invoice', async () => {
    deps.loadQuery.findLoadById.mockResolvedValue(
      makeLoad({
        carrierType: 'EXTERNAL_CARRIER',
        customerRate: '3000',
        dispatchFeeType: 'PERCENTAGE',
        dispatchFeePercent: '10',
        feeIncludesAccessorials: true,
        accessorials: [
          { amount: '200', billTo: 'CUSTOMER' },
          { amount: '150', billTo: 'CARRIER' },
        ],
      }),
    );
    const service = createInvoiceBuilderService(deps);

    await service.createFromLoadWithFee({
      loadId: 'load-1',
      organizationId: 'org-1',
      userId: 'system',
    });

    // CUSTOMER invoice: customerRate + only CUSTOMER-billed accessorial ($200)
    expect(deps.invoiceRepo.create).toHaveBeenCalledWith(
      expect.objectContaining({
        type: 'CUSTOMER',
        subtotal: 3000,
        accessorials: 200,
        totalAmount: 3200,
      }),
    );
  });

  it('includes BOTH-billed accessorials on CUSTOMER invoice', async () => {
    deps.loadQuery.findLoadById.mockResolvedValue(
      makeLoad({
        carrierType: 'EXTERNAL_CARRIER',
        customerRate: '3000',
        dispatchFeeType: 'PERCENTAGE',
        dispatchFeePercent: '10',
        feeIncludesAccessorials: false,
        accessorials: [{ amount: '75', billTo: 'BOTH' }],
      }),
    );
    const service = createInvoiceBuilderService(deps);

    await service.createFromLoadWithFee({
      loadId: 'load-1',
      organizationId: 'org-1',
      userId: 'system',
    });

    expect(deps.invoiceRepo.create).toHaveBeenCalledWith(
      expect.objectContaining({
        type: 'CUSTOMER',
        accessorials: 75,
        totalAmount: 3075,
      }),
    );
  });

  it('treats legacy lowercase "customer" as CUSTOMER-billed (case-insensitive)', async () => {
    deps.loadQuery.findLoadById.mockResolvedValue(
      makeLoad({
        carrierType: 'EXTERNAL_CARRIER',
        customerRate: '1000',
        dispatchFeeType: 'PERCENTAGE',
        dispatchFeePercent: '10',
        feeIncludesAccessorials: true,
        accessorials: [{ amount: '100', billTo: 'customer' }],
      }),
    );
    const service = createInvoiceBuilderService(deps);

    const result = await service.createFromLoadWithFee({
      loadId: 'load-1',
      organizationId: 'org-1',
      userId: 'system',
    });

    // 10% of (1000 + 100) = 110
    expect(new Decimal(result.dispatchFeeAmount!.toString()).toNumber()).toBeCloseTo(110, 2);
    expect(deps.invoiceRepo.create).toHaveBeenCalledWith(
      expect.objectContaining({ accessorials: 100 }),
    );
  });

  it('returns null dispatchFeeAmount for COMPANY_ASSET', async () => {
    deps.loadQuery.findLoadById.mockResolvedValue(
      makeLoad({
        carrierType: 'COMPANY_ASSET',
        customerRate: '2000',
      }),
    );
    const service = createInvoiceBuilderService(deps);

    const result = await service.createFromLoadWithFee({
      loadId: 'load-1',
      organizationId: 'org-1',
      userId: 'system',
    });

    expect(result.dispatchFeeAmount).toBeNull();
  });

  it('returns null dispatchFeeAmount for LEASED_CARRIER', async () => {
    deps.loadQuery.findLoadById.mockResolvedValue(
      makeLoad({
        carrierType: 'LEASED_CARRIER',
        customerRate: '2000',
      }),
    );
    const service = createInvoiceBuilderService(deps);

    const result = await service.createFromLoadWithFee({
      loadId: 'load-1',
      organizationId: 'org-1',
      userId: 'system',
    });

    expect(result.dispatchFeeAmount).toBeNull();
  });
});
