import type { AccessorialCharge } from '@prisma/client';
import { ForbiddenError, NotFoundError } from '@/shared/errors';
import type { EventBus } from '../../shared/messaging/eventBus';
import type { LoadRepoPort } from '../types/loadTypes';
import type {
  AccessorialRepoPort,
  CreateAccessorialInput,
  UpdateAccessorialInput,
  UpdateApprovalInput,
} from '../types/accessorialTypes';

interface AccessorialServiceDeps {
  accessorialRepository: AccessorialRepoPort;
  loadRepository: LoadRepoPort;
  eventBus: EventBus;
}

export interface AccessorialService {
  createAccessorial(input: CreateAccessorialInput): Promise<AccessorialCharge>;
  updateAccessorial(input: UpdateAccessorialInput): Promise<AccessorialCharge>;
  updateApproval(input: UpdateApprovalInput): Promise<AccessorialCharge>;
  deleteAccessorial(id: string, organizationId: string): Promise<void>;
  listAccessorials(loadId: string, organizationId: string): Promise<AccessorialCharge[]>;
  getAccessorial(id: string, organizationId: string): Promise<AccessorialCharge>;
}

const findLoadOrThrow = async (
  loadId: string,
  organizationId: string,
  deps: AccessorialServiceDeps,
): Promise<void> => {
  const load = await deps.loadRepository.findById(loadId, organizationId);
  if (load === null) {
    throw new NotFoundError('Load not found.');
  }
};

const findAccessorialOrThrow = async (
  id: string,
  organizationId: string,
  deps: AccessorialServiceDeps,
): Promise<AccessorialCharge> => {
  const charge = await deps.accessorialRepository.findById(id, organizationId);
  if (charge === null) {
    throw new NotFoundError('Accessorial charge not found.');
  }
  return charge;
};

const guardAutoGenerated = (charge: AccessorialCharge): void => {
  if (charge.isAutoGenerated) {
    throw new ForbiddenError('Auto-generated accessorial charges cannot be modified.');
  }
};

export const createAccessorialService = (deps: AccessorialServiceDeps): AccessorialService => ({
  createAccessorial: async (input: CreateAccessorialInput): Promise<AccessorialCharge> => {
    await findLoadOrThrow(input.loadId, input.organizationId, deps);
    const charge = await deps.accessorialRepository.create(input);
    deps.eventBus
      .publish('accessorial.created', { loadId: charge.loadId, organizationId: input.organizationId, accessorialId: charge.id })
      .catch((_error: unknown) => { /* fire-and-forget */ });
    return charge;
  },

  updateAccessorial: async (input: UpdateAccessorialInput): Promise<AccessorialCharge> => {
    const existing = await findAccessorialOrThrow(input.id, input.organizationId, deps);
    guardAutoGenerated(existing);
    const updated = await deps.accessorialRepository.update(input);
    deps.eventBus
      .publish('accessorial.updated', { loadId: updated.loadId, organizationId: input.organizationId, accessorialId: updated.id })
      .catch((_error: unknown) => { /* fire-and-forget */ });
    return updated;
  },

  updateApproval: async (input: UpdateApprovalInput): Promise<AccessorialCharge> => {
    await findAccessorialOrThrow(input.id, input.organizationId, deps);
    const updated = await deps.accessorialRepository.updateApproval(input);
    deps.eventBus
      .publish('accessorial.updated', { loadId: updated.loadId, organizationId: input.organizationId, accessorialId: updated.id })
      .catch((_error: unknown) => { /* fire-and-forget */ });
    return updated;
  },

  deleteAccessorial: async (id: string, organizationId: string): Promise<void> => {
    const existing = await findAccessorialOrThrow(id, organizationId, deps);
    guardAutoGenerated(existing);
    const { loadId } = existing;
    await deps.accessorialRepository.delete(id, organizationId);
    deps.eventBus
      .publish('accessorial.deleted', { loadId, organizationId, accessorialId: id })
      .catch((_error: unknown) => { /* fire-and-forget */ });
  },

  listAccessorials: async (
    loadId: string,
    organizationId: string,
  ): Promise<AccessorialCharge[]> => {
    await findLoadOrThrow(loadId, organizationId, deps);
    return deps.accessorialRepository.findByLoadId(loadId, organizationId);
  },

  getAccessorial: async (id: string, organizationId: string): Promise<AccessorialCharge> => {
    return findAccessorialOrThrow(id, organizationId, deps);
  },
});
