import type { AccessorialCharge, Stop } from '@prisma/client';

// ---------------------------------------------------------------------------
// Result type
// ---------------------------------------------------------------------------

export type DetentionResult =
  | { detected: false }
  | { detected: true; billableHours: number; amount: number; description: string };

// ---------------------------------------------------------------------------
// Pure detection function — no side effects
// ---------------------------------------------------------------------------

export const checkDetentionForStop = (
  stop: Pick<Stop, 'id' | 'type' | 'arrivalTime' | 'departureTime' | 'facilityName' | 'city' | 'state' | 'sequence'>,
  freeHours: number,
  detentionRate: number,
  existingCharges: Pick<AccessorialCharge, 'stopId' | 'type' | 'isAutoGenerated'>[],
): DetentionResult => {
  // 1. DROP_HOOK stops are exempt from detention
  if (stop.type === 'DROP_HOOK') {
    return { detected: false };
  }

  // 2. Both arrival and departure times are required
  if (stop.arrivalTime === null || stop.departureTime === null) {
    return { detected: false };
  }

  // 3. Calculate total wait hours
  const waitHours = (stop.departureTime.getTime() - stop.arrivalTime.getTime()) / 3600000;
  if (waitHours <= freeHours) {
    return { detected: false };
  }

  // 4. Skip if an auto-generated detention charge already exists for this stop
  const hasDuplicate = existingCharges.some(
    (c) => c.stopId === stop.id && c.type === 'DETENTION' && c.isAutoGenerated,
  );
  if (hasDuplicate) {
    return { detected: false };
  }

  // 5. Calculate billable hours (rounded up) and amount
  const billableHours = Math.ceil(waitHours - freeHours);
  const amount = billableHours * detentionRate;
  const location =
    stop.facilityName ?? [stop.city, stop.state].filter(Boolean).join(', ') ?? 'Unknown';
  const description = `Auto-detected: ${waitHours.toFixed(1)}hr wait at ${location}`;

  return { detected: true, billableHours, amount, description };
};
