import type { LoadStatus } from '@prisma/client';
import type { EventBus } from '@/shared/messaging/eventBus';
import type { Logger } from '@/shared/utils/logger';
import {
  NotFoundError,
  InvalidTransitionError,
  ForbiddenError,
  ValidationError,
} from '@/shared/errors';
import {
  validateTransition,
  TRANSITION_SIDE_EFFECTS,
} from '@/shared/stateMachine';
import type { LoadRepoPort } from '../types/loadTypes';
import type {
  TransitionStatusInput,
  StatusTransitionResponse,
  StatusTransitionWarning,
  LoadStatusRepoPort,
} from '../types/loadStatusTypes';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const TONU_ACCESSORIAL_AMOUNT = 250;

// ---------------------------------------------------------------------------
// Side effect executors
// ---------------------------------------------------------------------------

interface SideEffectDeps {
  loadStatusRepo: LoadStatusRepoPort;
  eventBus: EventBus;
  logger: Logger;
}

const executeSideEffects = async (
  loadId: string,
  targetStatus: LoadStatus,
  deps: SideEffectDeps,
): Promise<void> => {
  const effects = TRANSITION_SIDE_EFFECTS[targetStatus] ?? [];

  for (const effect of effects) {
    switch (effect) {
      case 'CALCULATE_FINANCIALS':
        deps.logger.info('Side effect: calculate financials', { loadId, targetStatus });
        // Financials are calculated via the existing load update flow.
        // This hook is a placeholder for future auto-calculation integration.
        break;

      case 'FREEZE_FINANCIALS':
        deps.logger.info('Side effect: freeze financials', { loadId, targetStatus });
        // Financial freeze is enforced by the existing assertFinancialsNotChanged guard.
        break;

      case 'AUTO_GENERATE_INVOICE':
        deps.logger.info('Side effect: auto-generate invoice (pending)', { loadId, targetStatus });
        // Invoice generation will be wired in a future story.
        break;

      case 'AUTO_CREATE_TONU_ACCESSORIAL':
        deps.logger.info('Side effect: create TONU accessorial', { loadId, targetStatus });
        await deps.loadStatusRepo.createAccessorialCharge({
          loadId,
          type: 'TONU',
          description: 'Truck Order Not Used',
          amount: TONU_ACCESSORIAL_AMOUNT,
          billTo: 'customer',
          isAutoGenerated: true,
        });
        break;

      default:
        deps.logger.warn('Unknown side effect tag', { effect, loadId });
    }
  }
};

interface PublishDomainEventsInput {
  loadId: string;
  targetStatus: LoadStatus;
  eventBus: EventBus;
  logger: Logger;
}

const publishDomainEvents = async (input: PublishDomainEventsInput): Promise<void> => {
  const { loadId, targetStatus, eventBus, logger: log } = input;

  const eventMap: Partial<Record<LoadStatus, string>> = {
    DELIVERED: 'load.delivered',
    TONU: 'load.tonu',
    CANCELED: 'load.canceled',
  };

  const eventName = eventMap[targetStatus];

  if (eventName !== undefined) {
    await eventBus.publish(eventName, { loadId, status: targetStatus }).catch(
      (error: unknown) => {
        log.error('Failed to publish domain event', {
          eventName,
          loadId,
          error: error instanceof Error ? error.message : String(error),
        });
      },
    );
  }
};

// ---------------------------------------------------------------------------
// Service interface & factory
// ---------------------------------------------------------------------------

export interface LoadStatusService {
  transitionStatus(input: TransitionStatusInput): Promise<StatusTransitionResponse>;
}

interface LoadStatusServiceDeps {
  loadRepository: LoadRepoPort;
  loadStatusRepo: LoadStatusRepoPort;
  eventBus: EventBus;
  logger: Logger;
}

export const createLoadStatusService = (deps: LoadStatusServiceDeps): LoadStatusService => ({
  transitionStatus: async (input) => {
    const {
      loadId,
      organizationId,
      targetStatus,
      notes,
      overrideWarnings = false,
      userId,
      userRole,
    } = input;

    // 1. Load the current load
    const load = await deps.loadRepository.findById(loadId, organizationId);

    if (load === null) {
      throw new NotFoundError('Load not found.');
    }

    const currentStatus = load.status as LoadStatus;

    // 2. Validate the transition using the shared state machine
    const validationResult = validateTransition(currentStatus, targetStatus, {
      userRole,
      notes,
      load: {
        carrierId: load.carrierId,
        driverId: load.driverId,
        vehicleId: load.vehicleId,
        rateConReceivedAt: load.rateConReceivedAt,
        bolSignedAt: load.bolSignedAt,
      },
    });

    if (!validationResult.valid) {
      // Determine which error to throw based on the validation message
      const errorMessage = validationResult.error ?? 'Invalid transition';

      if (errorMessage.includes('requires ADMIN role')) {
        throw new ForbiddenError(errorMessage);
      }

      if (errorMessage.includes('requires notes')) {
        throw new ValidationError(errorMessage);
      }

      if (errorMessage.includes('Cannot transition from')) {
        const { TRANSITIONS } = await import('@/shared/stateMachine');
        const allowed = TRANSITIONS[currentStatus];
        throw new InvalidTransitionError(
          currentStatus,
          targetStatus,
          [...allowed],
        );
      }

      throw new ValidationError(errorMessage);
    }

    // 3. Check warnings — return them if not overridden
    if (
      validationResult.warnings !== undefined &&
      validationResult.warnings.length > 0 &&
      !overrideWarnings
    ) {
      const warnings: StatusTransitionWarning[] = validationResult.warnings.map(
        (message) => ({
          code: 'TRANSITION_WARNING',
          message,
        }),
      );

      return {
        success: false,
        warnings,
      };
    }

    // 4. Execute side effects
    await executeSideEffects(loadId, targetStatus, {
      loadStatusRepo: deps.loadStatusRepo,
      eventBus: deps.eventBus,
      logger: deps.logger,
    });

    // 5. Update the load status
    const updatedLoad = await deps.loadStatusRepo.updateStatus(loadId, targetStatus);

    // 6. Create status history record
    await deps.loadStatusRepo.createStatusHistory({
      loadId,
      fromStatus: currentStatus,
      toStatus: targetStatus,
      changedByUserId: userId,
      notes,
    });

    // 7. Publish domain events (fire-and-forget)
    await publishDomainEvents({
      loadId,
      targetStatus,
      eventBus: deps.eventBus,
      logger: deps.logger,
    });

    deps.logger.info('Load status transitioned', {
      loadId,
      from: currentStatus,
      to: targetStatus,
      userId,
    });

    return {
      success: true,
      load: updatedLoad,
    };
  },
});
