import type { LoadStatus } from '@prisma/client';
import type { EventBus } from '@/shared/messaging/eventBus';
import type { EventMap } from '@/shared/messaging/eventMap';
import type { Logger } from '@/shared/utils/logger';
import {
  NotFoundError,
  InvalidTransitionError,
  ForbiddenError,
  ValidationError,
} from '@/shared/errors';
import {
  validateTransition,
  TRANSITION_SIDE_EFFECTS,
} from '@/shared/stateMachine';
import type { LoadRepoPort, LoadWithRelations } from '../types/loadTypes';
import type {
  TransitionStatusInput,
  StatusTransitionResponse,
  StatusTransitionWarning,
  LoadStatusRepoPort,
} from '../types/loadStatusTypes';
import { checkDetentionForStop } from './detentionDetector';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const TONU_ACCESSORIAL_AMOUNT = 250;

// ---------------------------------------------------------------------------
// Side effect executors
// ---------------------------------------------------------------------------

interface DetentionSettingsQuery {
  findByOrganizationId(
    orgId: string,
  ): Promise<{ detentionFreeHours: number; defaultDetentionRate: { toString(): string } } | null>;
}

interface SideEffectDeps {
  loadStatusRepo: LoadStatusRepoPort;
  eventBus: EventBus;
  logger: Logger;
  load: LoadWithRelations;
  settingsQuery?: DetentionSettingsQuery;
}

const executeSideEffects = async (
  loadId: string,
  targetStatus: LoadStatus,
  deps: SideEffectDeps,
): Promise<void> => {
  const effects = TRANSITION_SIDE_EFFECTS[targetStatus] ?? [];

  for (const effect of effects) {
    switch (effect) {
      case 'FREEZE_FINANCIALS':
        deps.logger.info('Side effect: freeze financials', { loadId, targetStatus });
        // Financial freeze is enforced by the existing assertFinancialsNotChanged guard.
        break;

      case 'AUTO_GENERATE_INVOICE':
        deps.logger.info('Side effect: auto-generate invoice (via domain event)', { loadId, targetStatus });
        // Handled by invoiceReadinessSubscriber via load.delivered and load.status.changed events.
        break;

      case 'AUTO_CREATE_TONU_ACCESSORIAL':
        deps.logger.info('Side effect: create TONU accessorial', { loadId, targetStatus });
        await deps.loadStatusRepo.createAccessorialCharge({
          loadId,
          type: 'TONU',
          description: 'Truck Order Not Used',
          amount: TONU_ACCESSORIAL_AMOUNT,
          billTo: 'customer',
          isAutoGenerated: true,
        });
        break;

      case 'CHECK_DETENTION': {
        deps.logger.info('Side effect: check detention', { loadId, targetStatus });

        const stopTypeFilter = targetStatus === 'IN_TRANSIT' ? 'PICKUP' : 'DELIVERY';
        const relevantStops = deps.load.stops.filter((s) => s.type === stopTypeFilter);

        if (relevantStops.length === 0) {
          break;
        }

        if (deps.settingsQuery === undefined) {
          break;
        }

        const settings = await deps.settingsQuery.findByOrganizationId(deps.load.organizationId);
        if (settings === null) {
          break;
        }

        const existingCharges = deps.load.accessorialCharges;

        for (const stop of relevantStops) {
          const detResult = checkDetentionForStop(
            stop,
            settings.detentionFreeHours,
            Number(settings.defaultDetentionRate),
            existingCharges,
          );

          if (detResult.detected) {
            await deps.loadStatusRepo.createAccessorialCharge({
              loadId,
              type: 'DETENTION',
              description: detResult.description,
              amount: detResult.amount,
              billTo: 'customer',
              isAutoGenerated: true,
              stopId: stop.id,
            });

            await deps.eventBus
              .publish('load.detention.detected', {
                loadId,
                organizationId: deps.load.organizationId,
                loadNumber: deps.load.loadNumber,
                stopId: stop.id,
                stopSequence: stop.sequence,
                facilityName: stop.facilityName,
                city: stop.city,
                state: stop.state,
                waitHours:
                  (stop.departureTime!.getTime() - stop.arrivalTime!.getTime()) / 3600000,
                billableHours: detResult.billableHours,
                rate: Number(settings.defaultDetentionRate),
                amount: detResult.amount,
              })
              .catch((error: unknown) => {
                deps.logger.error('Failed to publish load.detention.detected', {
                  loadId,
                  error: error instanceof Error ? error.message : String(error),
                });
              });
          }
        }
        break;
      }

      default:
        deps.logger.warn('Unknown side effect tag', { effect, loadId });
    }
  }
};

interface PublishDomainEventsInput {
  loadId: string;
  organizationId: string;
  loadNumber: string;
  fromStatus: LoadStatus | null;
  targetStatus: LoadStatus;
  customerId: string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  contactCcEmails: string[];
  eventBus: EventBus;
  logger: Logger;
}

const publishDomainEvents = async (input: PublishDomainEventsInput): Promise<void> => {
  const {
    loadId,
    organizationId,
    loadNumber,
    fromStatus,
    targetStatus,
    customerId,
    contactEmail,
    contactPhone,
    contactCcEmails,
    eventBus,
    logger: log,
  } = input;

  const safePublish = async <K extends keyof EventMap>(
    eventName: K,
    data: EventMap[K],
  ): Promise<void> => {
    await eventBus.publish(eventName, data).catch((error: unknown) => {
      log.error('Failed to publish domain event', {
        eventName,
        loadId,
        error: error instanceof Error ? error.message : String(error),
      });
    });
  };

  // Always emit the generic status change event (for notifications)
  await safePublish('load.status.changed', {
    loadId,
    organizationId,
    loadNumber,
    fromStatus: fromStatus as string | null,
    toStatus: targetStatus as string,
    customerId,
    contactEmail,
    contactPhone,
    contactCcEmails,
  });

  // Emit specific lifecycle events
  const lifecycleMap: Partial<Record<LoadStatus, keyof EventMap>> = {
    DELIVERED: 'load.delivered',
    TONU: 'load.tonu',
    CANCELED: 'load.canceled',
  };

  const lifecycleEvent = lifecycleMap[targetStatus];

  if (lifecycleEvent !== undefined) {
    await safePublish(lifecycleEvent, { loadId, organizationId, status: targetStatus as string });
  }
};

// ---------------------------------------------------------------------------
// Service interface & factory
// ---------------------------------------------------------------------------

export interface LoadStatusService {
  transitionStatus(input: TransitionStatusInput): Promise<StatusTransitionResponse>;
}

interface LoadStatusServiceDeps {
  loadRepository: LoadRepoPort;
  loadStatusRepo: LoadStatusRepoPort;
  settingsQuery?: DetentionSettingsQuery;
  eventBus: EventBus;
  logger: Logger;
}

export const createLoadStatusService = (deps: LoadStatusServiceDeps): LoadStatusService => ({
  transitionStatus: async (input) => {
    const {
      loadId,
      organizationId,
      targetStatus,
      notes,
      overrideWarnings = false,
      userId,
      userRole,
    } = input;

    // 1. Load the current load
    const load = await deps.loadRepository.findById(loadId, organizationId);

    if (load === null) {
      throw new NotFoundError('Load not found.');
    }

    const currentStatus = load.status as LoadStatus;

    // 2. Validate the transition using the shared state machine
    const validationResult = validateTransition(currentStatus, targetStatus, {
      userRole,
      notes,
      load: {
        carrierId: load.carrierId,
        driverId: load.driverId,
        vehicleId: load.vehicleId,
        rateConReceivedAt: load.rateConReceivedAt,
        bolSignedAt: load.bolSignedAt,
        stops: load.stops.map((s) => ({
          sequence: s.sequence,
          schedulingType: s.schedulingType,
          appointmentNumber: s.appointmentNumber,
        })),
      },
    });

    if (!validationResult.valid) {
      // Determine which error to throw based on the validation message
      const errorMessage = validationResult.error ?? 'Invalid transition';

      if (errorMessage.includes('requires ADMIN role')) {
        throw new ForbiddenError(errorMessage);
      }

      if (errorMessage.includes('requires notes')) {
        throw new ValidationError(errorMessage);
      }

      if (errorMessage.includes('Cannot transition from')) {
        const { TRANSITIONS } = await import('@/shared/stateMachine');
        const allowed = TRANSITIONS[currentStatus];
        throw new InvalidTransitionError(
          currentStatus,
          targetStatus,
          [...allowed],
        );
      }

      throw new ValidationError(errorMessage);
    }

    // 3. Check warnings — return them if not overridden
    if (
      validationResult.warnings !== undefined &&
      validationResult.warnings.length > 0 &&
      !overrideWarnings
    ) {
      const warnings: StatusTransitionWarning[] = validationResult.warnings.map(
        (message) => ({
          code: 'TRANSITION_WARNING',
          message,
        }),
      );

      return {
        success: false,
        warnings,
      };
    }

    // 4. Execute side effects
    await executeSideEffects(loadId, targetStatus, {
      loadStatusRepo: deps.loadStatusRepo,
      eventBus: deps.eventBus,
      logger: deps.logger,
      load,
      settingsQuery: deps.settingsQuery,
    });

    // 5. Update the load status (with optimistic locking when version provided)
    const updatedLoad = await deps.loadStatusRepo.updateStatus(loadId, targetStatus, input.version);

    // 6. Create status history record
    await deps.loadStatusRepo.createStatusHistory({
      loadId,
      fromStatus: currentStatus,
      toStatus: targetStatus,
      changedByUserId: userId,
      notes,
    });

    // 7. Publish domain events (fire-and-forget)
    await publishDomainEvents({
      loadId,
      organizationId,
      loadNumber: load.loadNumber,
      fromStatus: currentStatus,
      targetStatus,
      customerId: load.customerId ?? null,
      contactEmail: load.contact?.email ?? null,
      contactPhone: load.contact?.phone ?? null,
      contactCcEmails: load.contact?.ccEmails ?? [],
      eventBus: deps.eventBus,
      logger: deps.logger,
    });

    deps.logger.info('Load status transitioned', {
      loadId,
      from: currentStatus,
      to: targetStatus,
      userId,
    });

    return {
      success: true,
      load: updatedLoad,
    };
  },
});
