import type { AccessorialCharge, SchedulingType, Stop } from '@prisma/client';
import type { EventBus } from '@/shared/messaging/eventBus';
import type { Logger } from '@/shared/utils/logger';
import { NotFoundError, ValidationError } from '@/shared/errors';
import type { LoadRepoPort } from '../types/loadTypes';
import type { CreateAccessorialInput } from '../types/accessorialTypes';
import type {
  CreateStopInput,
  ReorderStopsInput,
  StopRepoPort,
  UpdateStopInput,
} from '../types/stopTypes';
import { checkDetentionForStop } from './detentionDetector';

interface DetentionSettingsQuery {
  findByOrganizationId(
    orgId: string,
  ): Promise<{ detentionFreeHours: number; defaultDetentionRate: { toString(): string } } | null>;
}

interface DetentionAccessorialQuery {
  findByLoadId(
    loadId: string,
    organizationId: string,
  ): Promise<Pick<AccessorialCharge, 'stopId' | 'type' | 'isAutoGenerated'>[]>;
}

interface DetentionAccessorialCreate {
  create(input: CreateAccessorialInput): Promise<unknown>;
}

interface StopServiceDeps {
  stopRepository: StopRepoPort;
  loadRepository: LoadRepoPort;
  eventBus: EventBus;
  logger: Logger;
  settingsQuery?: DetentionSettingsQuery;
  accessorialQuery?: DetentionAccessorialQuery;
  accessorialCreate?: DetentionAccessorialCreate;
}

export interface StopService {
  createStop(input: CreateStopInput): Promise<Stop>;
  updateStop(input: UpdateStopInput): Promise<Stop>;
  deleteStop(id: string, organizationId: string): Promise<void>;
  listStops(loadId: string, organizationId: string): Promise<Stop[]>;
  reorderStops(input: ReorderStopsInput): Promise<void>;
}

const findLoadOrThrow = async (
  loadId: string,
  organizationId: string,
  deps: Pick<StopServiceDeps, 'loadRepository'>,
): Promise<void> => {
  const load = await deps.loadRepository.findById(loadId, organizationId);
  if (load === null) {
    throw new NotFoundError('Load not found.');
  }
};

const validateSchedulingFields = (
  appointmentStart: Date | string | null | undefined,
  notificationHours: number | null | undefined,
): void => {
  if (appointmentStart === undefined || appointmentStart === null) {
    throw new ValidationError('appointmentStart is required.');
  }
};

const validateReorderInput = (
  existingStops: Stop[],
  stopOrder: { id: string; sequence: number }[],
): void => {
  if (stopOrder.length !== existingStops.length) {
    throw new ValidationError(
      `Reorder must include all stops. Expected ${existingStops.length}, received ${stopOrder.length}.`,
    );
  }

  const sequences = stopOrder.map((entry) => entry.sequence);
  const uniqueSequences = new Set(sequences);

  if (uniqueSequences.size !== sequences.length) {
    throw new ValidationError('Duplicate sequences are not allowed.');
  }

  const existingIds = new Set(existingStops.map((stop) => stop.id));
  const missingIds = stopOrder.filter((entry) => !existingIds.has(entry.id));

  if (missingIds.length > 0) {
    throw new ValidationError('Reorder contains stop IDs that do not belong to this load.');
  }
};

export const createStopService = (deps: StopServiceDeps): StopService => {
  const publishStopsChanged = (loadId: string, organizationId: string): void => {
    deps.eventBus.publish('load.stops.changed', { loadId, organizationId }).catch((error: unknown) => {
      deps.logger.warn('Failed to publish load.stops.changed', {
        loadId,
        error: error instanceof Error ? error.message : String(error),
      });
    });
  };

  return {
    createStop: async (input: CreateStopInput): Promise<Stop> => {
      await findLoadOrThrow(input.loadId, input.organizationId, deps);
      validateSchedulingFields(input.appointmentStart, input.notificationHours);

      let result: Stop;

      if (input.sequence === undefined) {
        const existingStops = await deps.stopRepository.findByLoadId(
          input.loadId,
          input.organizationId,
        );

        const maxSequence = existingStops.reduce(
          (max, stop) => Math.max(max, stop.sequence),
          0,
        );

        result = await deps.stopRepository.create({ ...input, sequence: maxSequence + 1 });
      } else {
        result = await deps.stopRepository.create(input);
      }

      publishStopsChanged(input.loadId, input.organizationId);
      return result;
    },

    updateStop: async (input: UpdateStopInput): Promise<Stop> => {
      validateSchedulingFields(input.appointmentStart, input.notificationHours);
      const result = await deps.stopRepository.update(input);

      // Detention auto-detection when departureTime is set
      if (
        input.departureTime !== undefined &&
        deps.settingsQuery !== undefined &&
        deps.accessorialCreate !== undefined &&
        deps.accessorialQuery !== undefined
      ) {
        const settings = await deps.settingsQuery.findByOrganizationId(input.organizationId);
        if (settings !== null) {
          const existingCharges = await deps.accessorialQuery.findByLoadId(
            result.loadId,
            input.organizationId,
          );
          const detentionResult = checkDetentionForStop(
            result,
            settings.detentionFreeHours,
            Number(settings.defaultDetentionRate),
            existingCharges,
          );

          if (detentionResult.detected) {
            const load = await deps.loadRepository.findById(result.loadId, input.organizationId);

            await deps.accessorialCreate.create({
              organizationId: input.organizationId,
              loadId: result.loadId,
              type: 'DETENTION',
              description: detentionResult.description,
              amount: detentionResult.amount,
              billTo: 'customer',
              isAutoGenerated: true,
              approvalStatus: 'PENDING',
              stopId: result.id,
            });

            deps.eventBus
              .publish('load.detention.detected', {
                loadId: result.loadId,
                organizationId: input.organizationId,
                loadNumber: load?.loadNumber ?? '',
                stopId: result.id,
                stopSequence: result.sequence,
                facilityName: result.facilityName,
                city: result.city,
                state: result.state,
                waitHours:
                  (result.departureTime!.getTime() - result.arrivalTime!.getTime()) / 3600000,
                billableHours: detentionResult.billableHours,
                rate: Number(settings.defaultDetentionRate),
                amount: detentionResult.amount,
              })
              .catch((error: unknown) => {
                deps.logger.warn('Failed to publish load.detention.detected', {
                  loadId: result.loadId,
                  error: error instanceof Error ? error.message : String(error),
                });
              });

            deps.logger.info('Detention auto-detected on stop update', {
              loadId: result.loadId,
              stopId: result.id,
              billableHours: detentionResult.billableHours,
              amount: detentionResult.amount,
            });
          }
        }
      }

      publishStopsChanged(result.loadId, input.organizationId);
      return result;
    },

    deleteStop: async (id: string, organizationId: string): Promise<void> => {
      const stop = await deps.stopRepository.findById(id, organizationId);

      if (!stop) {
        throw new NotFoundError(`Stop ${id} not found`);
      }

      const { loadId } = stop;
      await deps.stopRepository.delete(id, organizationId);

      publishStopsChanged(loadId, organizationId);
    },

    listStops: async (loadId: string, organizationId: string): Promise<Stop[]> => {
      await findLoadOrThrow(loadId, organizationId, deps);
      return deps.stopRepository.findByLoadId(loadId, organizationId);
    },

    reorderStops: async (input: ReorderStopsInput): Promise<void> => {
      await findLoadOrThrow(input.loadId, input.organizationId, deps);

      const existingStops = await deps.stopRepository.findByLoadId(
        input.loadId,
        input.organizationId,
      );

      validateReorderInput(existingStops, input.stopOrder);

      await deps.stopRepository.reorder(input);

      publishStopsChanged(input.loadId, input.organizationId);
    },
  };
};
