import type { AccessorialCharge, SchedulingType, Stop } from '@prisma/client';
import type { EventBus } from '@/shared/messaging/eventBus';
import type { Logger } from '@/shared/utils/logger';
import type { Warning } from '@/places';
import { NotFoundError, ValidationError } from '@/shared/errors';
import type { LoadRepoPort } from '../types/loadTypes';
import type { CreateAccessorialInput } from '../types/accessorialTypes';
import type {
  CreateStopInput,
  ReorderStopsInput,
  StopRepoPort,
  UpdateStopInput,
} from '../types/stopTypes';
import type { ResolveStopToPlace } from './loadService';
import { checkDetentionForStop } from './detentionDetector';
import { assertDeliveryAfterPickup } from '../utils/deliveryAfterPickup';

interface DetentionSettingsQuery {
  findByOrganizationId(
    orgId: string,
  ): Promise<{ detentionFreeHours: number; defaultDetentionRate: { toString(): string } } | null>;
}

interface DetentionAccessorialQuery {
  findByLoadId(
    loadId: string,
    organizationId: string,
  ): Promise<Pick<AccessorialCharge, 'stopId' | 'type' | 'isAutoGenerated'>[]>;
}

interface DetentionAccessorialCreate {
  create(input: CreateAccessorialInput): Promise<unknown>;
}

interface StopServiceDeps {
  stopRepository: StopRepoPort;
  loadRepository: LoadRepoPort;
  eventBus: EventBus;
  logger: Logger;
  resolveStopToPlace?: ResolveStopToPlace;
  settingsQuery?: DetentionSettingsQuery;
  accessorialQuery?: DetentionAccessorialQuery;
  accessorialCreate?: DetentionAccessorialCreate;
}

export interface StopWriteResult {
  stop: Stop;
  warnings: Warning[];
}

export interface StopService {
  createStop(input: CreateStopInput): Promise<StopWriteResult>;
  updateStop(input: UpdateStopInput): Promise<StopWriteResult>;
  deleteStop(id: string, organizationId: string): Promise<void>;
  listStops(loadId: string, organizationId: string): Promise<Stop[]>;
  reorderStops(input: ReorderStopsInput): Promise<void>;
}

const findLoadOrThrow = async (
  loadId: string,
  organizationId: string,
  deps: Pick<StopServiceDeps, 'loadRepository'>,
): Promise<void> => {
  const load = await deps.loadRepository.findById(loadId, organizationId);
  if (load === null) {
    throw new NotFoundError('Load not found.');
  }
};

const validateSchedulingFields = (
  appointmentStart: Date | string | null | undefined,
  notificationHours: number | null | undefined,
): void => {
  if (appointmentStart === undefined || appointmentStart === null) {
    throw new ValidationError('appointmentStart is required.');
  }
};

const resolveSingleStop = async (
  stop: {
    sequence: number;
    placeId?: string | null;
    facilityName?: string | null;
    address?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    contactName?: string | null;
    contactPhone?: string | null;
    notes?: string | null;
  },
  organizationId: string,
  resolveStopToPlace: ResolveStopToPlace | undefined,
): Promise<{
  placeId: string | null;
  resolutionStatus: string;
  facilityNameToWrite: string | undefined;
  warning: Warning | null;
}> => {
  if (resolveStopToPlace === undefined) {
    return {
      placeId: stop.placeId ?? null,
      resolutionStatus: 'UNRESOLVED',
      facilityNameToWrite: undefined,
      warning: null,
    };
  }

  const result = await resolveStopToPlace(
    {
      sequence: stop.sequence,
      placeId: stop.placeId ?? null,
      facilityName: stop.facilityName ?? null,
      address: stop.address ?? null,
      city: stop.city ?? null,
      state: stop.state ?? null,
      zip: stop.zip ?? null,
      contactName: stop.contactName ?? null,
      contactPhone: stop.contactPhone ?? null,
      notes: stop.notes ?? null,
    },
    organizationId,
  );

  return {
    placeId: result.placeId,
    resolutionStatus: result.resolutionStatus,
    facilityNameToWrite: result.facilityNameToWrite,
    warning: result.warning,
  };
};

const validateReorderInput = (
  existingStops: Stop[],
  stopOrder: { id: string; sequence: number }[],
): void => {
  if (stopOrder.length !== existingStops.length) {
    throw new ValidationError(
      `Reorder must include all stops. Expected ${existingStops.length}, received ${stopOrder.length}.`,
    );
  }

  const sequences = stopOrder.map((entry) => entry.sequence);
  const uniqueSequences = new Set(sequences);

  if (uniqueSequences.size !== sequences.length) {
    throw new ValidationError('Duplicate sequences are not allowed.');
  }

  const existingIds = new Set(existingStops.map((stop) => stop.id));
  const missingIds = stopOrder.filter((entry) => !existingIds.has(entry.id));

  if (missingIds.length > 0) {
    throw new ValidationError('Reorder contains stop IDs that do not belong to this load.');
  }
};

export const createStopService = (deps: StopServiceDeps): StopService => {
  const publishStopsChanged = (loadId: string, organizationId: string): void => {
    deps.eventBus.publish('load.stops.changed', { loadId, organizationId }).catch((error: unknown) => {
      deps.logger.warn('Failed to publish load.stops.changed', {
        loadId,
        error: error instanceof Error ? error.message : String(error),
      });
    });
  };

  return {
    createStop: async (input: CreateStopInput): Promise<StopWriteResult> => {
      await findLoadOrThrow(input.loadId, input.organizationId, deps);
      validateSchedulingFields(input.appointmentStart, input.notificationHours);

      const existingStops = await deps.stopRepository.findByLoadId(
        input.loadId,
        input.organizationId,
      );

      // Cross-stop check: project the new stop into the sibling list
      // and verify the rule before persisting.
      assertDeliveryAfterPickup([
        ...existingStops,
        { type: input.type, appointmentStart: input.appointmentStart },
      ]);

      const resolvedSequence =
        input.sequence ??
        existingStops.reduce((max, stop) => Math.max(max, stop.sequence), 0) + 1;

      // Resolve to Place BEFORE persist (no transaction = no
      // long-held DB connection during AWS round-trip).
      const resolution = await resolveSingleStop(
        { ...input, sequence: resolvedSequence },
        input.organizationId,
        deps.resolveStopToPlace,
      );

      const persistInput: CreateStopInput = {
        ...input,
        sequence: resolvedSequence,
        placeId: resolution.placeId,
        resolutionStatus: resolution.resolutionStatus,
        ...(resolution.facilityNameToWrite !== undefined
          ? { facilityName: resolution.facilityNameToWrite }
          : {}),
      };

      const result = await deps.stopRepository.create(persistInput);

      publishStopsChanged(input.loadId, input.organizationId);
      return {
        stop: result,
        warnings: resolution.warning !== null ? [resolution.warning] : [],
      };
    },

    updateStop: async (input: UpdateStopInput): Promise<StopWriteResult> => {
      validateSchedulingFields(input.appointmentStart, input.notificationHours);

      // Cross-stop check: only run when the change could affect the rule
      // (date or stop-type change). Fetch siblings and project the merged values.
      const targetStop = await deps.stopRepository.findById(input.id, input.organizationId);
      if (
        targetStop &&
        (input.appointmentStart !== undefined || input.type !== undefined)
      ) {
        const siblings = await deps.stopRepository.findByLoadId(
          targetStop.loadId,
          input.organizationId,
        );
        const projected = siblings.map((s) =>
          s.id === targetStop.id
            ? {
                type: input.type ?? s.type,
                appointmentStart:
                  input.appointmentStart !== undefined
                    ? input.appointmentStart
                    : s.appointmentStart,
              }
            : { type: s.type, appointmentStart: s.appointmentStart },
        );
        assertDeliveryAfterPickup(projected);
      }

      // Re-resolve the stop to a Place. Use the merged value of each
      // address field — if a field is omitted from input, fall back to
      // the existing stored value so the resolver sees the full picture.
      let warning: Warning | null = null;
      let persistInput: UpdateStopInput = input;
      if (targetStop !== null) {
        const merged = {
          sequence: input.sequence ?? targetStop.sequence,
          placeId: input.placeId !== undefined ? input.placeId : targetStop.placeId,
          facilityName:
            input.facilityName !== undefined ? input.facilityName : targetStop.facilityName,
          address: input.address !== undefined ? input.address : targetStop.address,
          city: input.city !== undefined ? input.city : targetStop.city,
          state: input.state !== undefined ? input.state : targetStop.state,
          zip: input.zip !== undefined ? input.zip : targetStop.zip,
          contactName:
            input.contactName !== undefined ? input.contactName : targetStop.contactName,
          contactPhone:
            input.contactPhone !== undefined ? input.contactPhone : targetStop.contactPhone,
          notes: input.notes !== undefined ? input.notes : targetStop.notes,
        };
        const resolution = await resolveSingleStop(
          merged,
          input.organizationId,
          deps.resolveStopToPlace,
        );
        warning = resolution.warning;
        persistInput = {
          ...input,
          placeId: resolution.placeId,
          resolutionStatus: resolution.resolutionStatus,
          ...(resolution.facilityNameToWrite !== undefined
            ? { facilityName: resolution.facilityNameToWrite }
            : {}),
        };
      }

      const result = await deps.stopRepository.update(persistInput);

      // Detention auto-detection when departureTime is set
      if (
        input.departureTime !== undefined &&
        deps.settingsQuery !== undefined &&
        deps.accessorialCreate !== undefined &&
        deps.accessorialQuery !== undefined
      ) {
        const settings = await deps.settingsQuery.findByOrganizationId(input.organizationId);
        if (settings !== null) {
          const existingCharges = await deps.accessorialQuery.findByLoadId(
            result.loadId,
            input.organizationId,
          );
          const detentionResult = checkDetentionForStop(
            result,
            settings.detentionFreeHours,
            Number(settings.defaultDetentionRate),
            existingCharges,
          );

          if (detentionResult.detected) {
            const load = await deps.loadRepository.findById(result.loadId, input.organizationId);

            await deps.accessorialCreate.create({
              organizationId: input.organizationId,
              loadId: result.loadId,
              type: 'DETENTION',
              description: detentionResult.description,
              amount: detentionResult.amount,
              billTo: 'customer',
              isAutoGenerated: true,
              approvalStatus: 'PENDING',
              stopId: result.id,
            });

            deps.eventBus
              .publish('load.detention.detected', {
                loadId: result.loadId,
                organizationId: input.organizationId,
                loadNumber: load?.loadNumber ?? '',
                stopId: result.id,
                stopSequence: result.sequence,
                facilityName: result.facilityName,
                city: result.city,
                state: result.state,
                waitHours:
                  (result.departureTime!.getTime() - result.arrivalTime!.getTime()) / 3600000,
                billableHours: detentionResult.billableHours,
                rate: Number(settings.defaultDetentionRate),
                amount: detentionResult.amount,
              })
              .catch((error: unknown) => {
                deps.logger.warn('Failed to publish load.detention.detected', {
                  loadId: result.loadId,
                  error: error instanceof Error ? error.message : String(error),
                });
              });

            deps.logger.info('Detention auto-detected on stop update', {
              loadId: result.loadId,
              stopId: result.id,
              billableHours: detentionResult.billableHours,
              amount: detentionResult.amount,
            });
          }
        }
      }

      publishStopsChanged(result.loadId, input.organizationId);
      return {
        stop: result,
        warnings: warning !== null ? [warning] : [],
      };
    },

    deleteStop: async (id: string, organizationId: string): Promise<void> => {
      const stop = await deps.stopRepository.findById(id, organizationId);

      if (!stop) {
        throw new NotFoundError(`Stop ${id} not found`);
      }

      const { loadId } = stop;
      await deps.stopRepository.delete(id, organizationId);

      publishStopsChanged(loadId, organizationId);
    },

    listStops: async (loadId: string, organizationId: string): Promise<Stop[]> => {
      await findLoadOrThrow(loadId, organizationId, deps);
      return deps.stopRepository.findByLoadId(loadId, organizationId);
    },

    reorderStops: async (input: ReorderStopsInput): Promise<void> => {
      await findLoadOrThrow(input.loadId, input.organizationId, deps);

      const existingStops = await deps.stopRepository.findByLoadId(
        input.loadId,
        input.organizationId,
      );

      validateReorderInput(existingStops, input.stopOrder);

      await deps.stopRepository.reorder(input);

      publishStopsChanged(input.loadId, input.organizationId);
    },
  };
};
