import type { AccessorialCharge, AccessorialType } from '@prisma/client';
import type { EventBus } from '../../shared/messaging/eventBus';

// ---------------------------------------------------------------------------
// Create accessorial charge input
// ---------------------------------------------------------------------------

export interface CreateAccessorialInput {
  organizationId: string;
  loadId: string;
  type: AccessorialType;
  description?: string;
  amount: number;
  billTo?: string;
  isAutoGenerated?: boolean;
  approvalStatus?: string;
  approvalSource?: string;
  approvalNotes?: string;
  documentId?: string;
}

// ---------------------------------------------------------------------------
// Update accessorial charge input
// ---------------------------------------------------------------------------

export interface UpdateAccessorialInput {
  id: string;
  organizationId: string;
  type?: AccessorialType;
  description?: string;
  amount?: number;
  billTo?: string;
  approvalStatus?: string;
  approvalSource?: string;
  approvalNotes?: string;
  documentId?: string;
}

// ---------------------------------------------------------------------------
// Update approval input
// ---------------------------------------------------------------------------

export interface UpdateApprovalInput {
  id: string;
  organizationId: string;
  approvalStatus: string;
  approvalSource?: string;
  approvalNotes?: string;
  documentId?: string;
}

// ---------------------------------------------------------------------------
// Repo port
// ---------------------------------------------------------------------------

export interface AccessorialRepoPort {
  create(input: CreateAccessorialInput): Promise<AccessorialCharge>;
  update(input: UpdateAccessorialInput): Promise<AccessorialCharge>;
  updateApproval(input: UpdateApprovalInput): Promise<AccessorialCharge>;
  delete(id: string, organizationId: string): Promise<void>;
  findByLoadId(loadId: string, organizationId: string): Promise<AccessorialCharge[]>;
  findById(id: string, organizationId: string): Promise<AccessorialCharge | null>;
}

// ---------------------------------------------------------------------------
// Service deps
// ---------------------------------------------------------------------------

export interface AccessorialServiceDeps {
  accessorialRepo: AccessorialRepoPort;
  eventBus: EventBus;
}
