import type {
  Load,
  Stop,
  AccessorialCharge,
  LoadStatusHistory,
  CheckCall,
  Carrier,
  Driver,
  Vehicle,
  Contact,
  EquipmentType,
  LoadStatus,
  StopType,
  AccessorialType,
} from '@prisma/client';
import type { SortOrder } from '@/shared/pagination';
import type { PaginationMeta } from '@/shared/responseEnvelope';

// ---------------------------------------------------------------------------
// Stop inputs
// ---------------------------------------------------------------------------

export interface StopInput {
  type: StopType;
  sequence: number;
  contactId?: string;
  placeId?: string;
  facilityName?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  appointmentDate?: Date;
  appointmentTime?: string;
  appointmentNumber?: string;
  contactName?: string;
  contactPhone?: string;
  notes?: string;
}

// ---------------------------------------------------------------------------
// Accessorial charge inputs
// ---------------------------------------------------------------------------

export interface AccessorialChargeInput {
  type: AccessorialType;
  description?: string;
  amount: number | string;
  billTo?: string;
  isAutoGenerated?: boolean;
}

// ---------------------------------------------------------------------------
// Create / Update inputs
// ---------------------------------------------------------------------------

export interface CreateLoadInput {
  carrierId?: string;
  driverId?: string;
  vehicleId?: string;
  brokerId?: string;
  shipperId?: string;
  consigneeId?: string;
  brokerRefNumber?: string;
  equipmentType?: EquipmentType;
  isHazmat?: boolean;
  isTarp?: boolean;
  isTeamDriver?: boolean;
  commodity?: string;
  weight?: number;
  pieceCount?: number;
  loadedMiles?: number;
  deadheadMiles?: number;
  totalMiles?: number;
  customerRate?: number | string;
  carrierRate?: number | string;
  dispatchFee?: number | string;
  partnerSplit?: number | string;
  ratePerMile?: number | string;
  status?: LoadStatus;
  rateConReceivedAt?: Date;
  bolUnsignedAt?: Date;
  bolSignedAt?: Date;
  dispatcherNotes?: string;
  driverInstructions?: string;
  stops: StopInput[];
  accessorialCharges?: AccessorialChargeInput[];
}

export interface UpdateLoadInput {
  carrierId?: string;
  driverId?: string;
  vehicleId?: string;
  brokerId?: string;
  shipperId?: string;
  consigneeId?: string;
  brokerRefNumber?: string;
  equipmentType?: EquipmentType;
  isHazmat?: boolean;
  isTarp?: boolean;
  isTeamDriver?: boolean;
  commodity?: string;
  weight?: number;
  pieceCount?: number;
  loadedMiles?: number;
  deadheadMiles?: number;
  totalMiles?: number;
  customerRate?: number | string;
  carrierRate?: number | string;
  dispatchFee?: number | string;
  partnerSplit?: number | string;
  ratePerMile?: number | string;
  status?: LoadStatus;
  rateConReceivedAt?: Date;
  bolUnsignedAt?: Date;
  bolSignedAt?: Date;
  dispatcherNotes?: string;
  driverInstructions?: string;
  stops?: StopInput[];
  accessorialCharges?: AccessorialChargeInput[];
}

// ---------------------------------------------------------------------------
// Query / filter types
// ---------------------------------------------------------------------------

export interface LoadListFilters {
  status?: LoadStatus[];
  carrierId?: string;
  equipmentType?: EquipmentType;
  search?: string;
  dateFrom?: Date;
  dateTo?: Date;
}

export interface LoadQueryInput {
  organizationId: string;
  filters: LoadListFilters;
}

export interface ListLoadsRepositoryInput extends LoadQueryInput {
  skip: number;
  take: number;
  orderBy: Record<string, SortOrder>;
}

// ---------------------------------------------------------------------------
// Loaded relations
// ---------------------------------------------------------------------------

export interface LoadWithRelations extends Load {
  stops: Stop[];
  carrier: Carrier | null;
  driver: Driver | null;
  vehicle: Vehicle | null;
  broker: Contact | null;
  shipper: Contact | null;
  consignee: Contact | null;
  statusHistory: LoadStatusHistory[];
  checkCalls: CheckCall[];
  accessorialCharges: AccessorialCharge[];
}

export interface LoadListItem extends Load {
  stops: Stop[];
  carrier: Pick<Carrier, 'id' | 'name'> | null;
  driver: Pick<Driver, 'id' | 'firstName' | 'lastName'> | null;
  _count: {
    accessorialCharges: number;
  };
}

// ---------------------------------------------------------------------------
// Result types
// ---------------------------------------------------------------------------

export interface ListLoadsResult {
  data: LoadListItem[];
  meta: PaginationMeta;
}

// ---------------------------------------------------------------------------
// Check call types
// ---------------------------------------------------------------------------

export interface CreateCheckCallInput {
  location?: string;
  latitude?: number;
  longitude?: number;
  status?: string;
  eta?: Date;
  notes?: string;
  brokerNotified: boolean;
  brokerNotes?: string;
}

export interface CheckCallWithUser {
  id: string;
  loadId: string;
  calledByUserId: string | null;
  location: string | null;
  latitude: unknown;
  longitude: unknown;
  status: string | null;
  eta: Date | null;
  brokerNotified: boolean;
  brokerNotes: string | null;
  notes: string | null;
  createdAt: Date;
  calledBy: { id: string; firstName: string; lastName: string } | null;
}

// ---------------------------------------------------------------------------
// Status history types
// ---------------------------------------------------------------------------

export interface StatusHistoryWithUser {
  id: string;
  loadId: string;
  fromStatus: string | null;
  toStatus: string;
  changedByUserId: string | null;
  notes: string | null;
  createdAt: Date;
  changedBy: { id: string; firstName: string; lastName: string } | null;
}

// ---------------------------------------------------------------------------
// Load document types
// ---------------------------------------------------------------------------

export interface LoadDocument {
  id: string;
  organizationId: string;
  loadId: string | null;
  type: string;
  fileName: string;
  fileSize: number | null;
  mimeType: string | null;
  uploadStatus: string;
  notes: string | null;
  createdAt: Date;
}

// ---------------------------------------------------------------------------
// Repo port
// ---------------------------------------------------------------------------

export interface LoadRepoPort {
  create(organizationId: string, loadNumber: string, input: CreateLoadInput): Promise<LoadWithRelations>;
  findById(id: string, organizationId: string): Promise<LoadWithRelations | null>;
  list(input: ListLoadsRepositoryInput): Promise<LoadListItem[]>;
  count(input: LoadQueryInput): Promise<number>;
  update(id: string, input: UpdateLoadInput): Promise<LoadWithRelations>;
  softDelete(id: string, deletedAt: Date): Promise<void>;
  createCheckCall(loadId: string, calledByUserId: string, input: CreateCheckCallInput): Promise<CheckCallWithUser>;
  listCheckCalls(loadId: string): Promise<CheckCallWithUser[]>;
  listStatusHistory(loadId: string): Promise<StatusHistoryWithUser[]>;
  listDocuments(loadId: string, organizationId: string): Promise<LoadDocument[]>;
}

// ---------------------------------------------------------------------------
// OrgSettings port (for prohibited commodities check)
// ---------------------------------------------------------------------------

export interface OrgSettingsQueryPort {
  getProhibitedCommodities(organizationId: string): Promise<string[]>;
}
