import type { LoadStatus } from '@prisma/client';
import type { LoadWithRelations } from './loadTypes';

// ---------------------------------------------------------------------------
// Transition input
// ---------------------------------------------------------------------------

export interface TransitionStatusInput {
  loadId: string;
  organizationId: string;
  targetStatus: LoadStatus;
  notes?: string;
  overrideWarnings?: boolean;
  userId: string | null;
  userRole: string;
}

// ---------------------------------------------------------------------------
// Status transition response
// ---------------------------------------------------------------------------

export interface StatusTransitionWarning {
  code: string;
  message: string;
  detail?: string;
}

export interface StatusTransitionError {
  code: string;
  message: string;
}

export interface StatusTransitionResponse {
  success: boolean;
  load?: LoadWithRelations;
  warnings?: StatusTransitionWarning[];
  error?: StatusTransitionError;
}

// ---------------------------------------------------------------------------
// Repo port for status-specific operations
// ---------------------------------------------------------------------------

export interface LoadStatusRepoPort {
  updateStatus(loadId: string, status: LoadStatus): Promise<LoadWithRelations>;
  createStatusHistory(data: {
    loadId: string;
    fromStatus: LoadStatus;
    toStatus: LoadStatus;
    changedByUserId: string | null;
    notes?: string;
  }): Promise<void>;
  createAccessorialCharge(data: {
    loadId: string;
    type: 'TONU' | 'DETENTION';
    description: string;
    amount: number;
    billTo: string;
    isAutoGenerated: boolean;
    stopId?: string;
  }): Promise<void>;
  sumAccessorialCharges(loadId: string): Promise<string>;
  updateFinancials(
    loadId: string,
    financials: {
      dispatchFee: string;
      partnerSplit: string;
      ratePerMile: string | null;
      ratePerTotalMile: string | null;
      carrierPayout: string;
      companyMargin: string;
      driverPay: string | null;
      estimatedCost: string | null;
      dispatcherComm: string | null;
    },
  ): Promise<void>;
}
