import type { Decimal } from '@prisma/client/runtime/library';
import type {
  Load,
  Stop,
  AccessorialCharge,
  LoadStatusHistory,
  CheckCall,
  Carrier,
  Driver,
  Vehicle,
  Contact,
  Customer,
  User,
  CarrierType,
  DispatchFeeType,
  DispatcherCommType,
  DriverPayType,
  EquipmentType,
  LoadStatus,
  SchedulingType,
  StopType,
  AccessorialType,
} from '@prisma/client';
import type { SortOrder } from '@/shared/pagination';
import type { PaginationMeta } from '@/shared/responseEnvelope';

// ---------------------------------------------------------------------------
// Stop inputs
// ---------------------------------------------------------------------------

export interface StopInput {
  type: StopType;
  sequence: number;
  contactId?: string;
  placeId?: string | null;
  resolutionStatus?: string;
  facilityName?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  schedulingType?: SchedulingType;
  appointmentStart: Date | string;
  appointmentEnd?: Date | string | null;
  notificationHours?: number | null;
  appointmentNumber?: string;
  contactName?: string;
  contactPhone?: string;
  commodity?: string;
  weight?: number;
  pieceCount?: number;
  isHazmat?: boolean;
  isTarp?: boolean;
  isTempControlled?: boolean;
  notes?: string;
  callByTime?: string;
  trailerNumber?: string;
  yardLocation?: string;
}

// ---------------------------------------------------------------------------
// Accessorial charge inputs
// ---------------------------------------------------------------------------

export interface AccessorialChargeInput {
  type: AccessorialType;
  description?: string;
  amount: number | string;
  billTo?: string;
  isAutoGenerated?: boolean;
}

// ---------------------------------------------------------------------------
// Create / Update inputs
// ---------------------------------------------------------------------------

export interface CreateLoadInput {
  carrierId?: string | null;
  driverId?: string | null;
  vehicleId?: string | null;
  contactId?: string | null;
  customerId?: string | null;
  dispatcherUserId?: string | null;
  externalRefNumber?: string;
  equipmentType?: EquipmentType;
  isTeamDriver?: boolean;
  loadedMiles?: number;
  deadheadMiles?: number;
  totalMiles?: number;
  customerRate?: number | string;
  carrierRate?: number | string;
  status?: LoadStatus;
  rateConReceivedAt?: Date;
  bolUnsignedAt?: Date;
  bolSignedAt?: Date;
  dispatcherNotes?: string;
  driverInstructions?: string;
  stops: StopInput[];
  accessorialCharges?: AccessorialChargeInput[];
  dispatchFeeType?: DispatchFeeType | null;
  dispatchFeeAmount?: number | string | null;
  partnerSplitPercent?: number | string | null;
  driverPayType?: DriverPayType | null;
  driverPayRate?: number | string | null;
  dispatcherCommissionType?: DispatcherCommType | null;
  dispatcherCommissionRate?: number | string | null;
  feeIncludesAccessorials?: boolean | null;
  payFromNet?: boolean | null;
  carrierType?: CarrierType | null;
}

export interface UpdateLoadInput {
  carrierId?: string | null;
  driverId?: string | null;
  vehicleId?: string | null;
  contactId?: string | null;
  customerId?: string | null;
  dispatcherUserId?: string | null;
  externalRefNumber?: string;
  equipmentType?: EquipmentType;
  isTeamDriver?: boolean;
  loadedMiles?: number;
  deadheadMiles?: number;
  totalMiles?: number;
  customerRate?: number | string;
  carrierRate?: number | string;
  dispatchFee?: number | string;
  partnerSplit?: number | string;
  ratePerMile?: number | string;
  status?: LoadStatus;
  rateConReceivedAt?: Date;
  bolUnsignedAt?: Date;
  bolSignedAt?: Date;
  dispatcherNotes?: string;
  driverInstructions?: string;
  stops?: StopInput[];
  accessorialCharges?: AccessorialChargeInput[];
  dispatchFeeType?: DispatchFeeType | null;
  dispatchFeeAmount?: number | string | null;
  partnerSplitPercent?: number | string | null;
  driverPayType?: DriverPayType | null;
  driverPayRate?: number | string | null;
  dispatcherCommissionType?: DispatcherCommType | null;
  dispatcherCommissionRate?: number | string | null;
  feeIncludesAccessorials?: boolean | null;
  payFromNet?: boolean | null;
  carrierType?: CarrierType | null;
}

// ---------------------------------------------------------------------------
// Query / filter types
// ---------------------------------------------------------------------------

export interface LoadListFilters {
  status?: LoadStatus[];
  carrierId?: string;
  customerId?: string;
  equipmentType?: EquipmentType;
  search?: string;
  dateFrom?: Date;
  dateTo?: Date;
}

export interface LoadQueryInput {
  organizationId: string;
  filters: LoadListFilters;
}

export interface ListLoadsRepositoryInput extends LoadQueryInput {
  skip: number;
  take: number;
  orderBy: Record<string, SortOrder>;
}

// ---------------------------------------------------------------------------
// Loaded relations
// ---------------------------------------------------------------------------

export interface LoadStatusHistoryWithUser extends LoadStatusHistory {
  changedBy: { id: string; firstName: string; lastName: string } | null;
}

export interface CheckCallWithRelations extends CheckCall {
  calledBy: { id: string; firstName: string; lastName: string } | null;
}

export interface LoadWithRelations extends Load {
  stops: LoadListStop[];
  carrier: Carrier | null;
  driver: Driver | null;
  vehicle: Vehicle | null;
  contact: Contact | null;
  customer: Customer | null;
  dispatcher: Pick<User, 'id' | 'firstName' | 'lastName'> | null;
  statusHistory: LoadStatusHistoryWithUser[];
  checkCalls: CheckCallWithRelations[];
  accessorialCharges: AccessorialCharge[];
  _count?: {
    // Optional so existing test fixtures don't break. When absent, the
    // INVOICE_CREATED short-circuit in computeInvoiceReadiness is skipped
    // and readiness is computed solely from documents (US-11).
    invoices: number;
  };
}

export interface LoadListStop extends Stop {
  place: { latitude: Decimal | null; longitude: Decimal | null } | null;
}

export interface LoadListItem extends Load {
  stops: LoadListStop[];
  carrier: Pick<Carrier, 'id' | 'name'> | null;
  driver: Pick<Driver, 'id' | 'firstName' | 'lastName'> | null;
  contact: Pick<Contact, 'id' | 'firstName' | 'lastName' | 'email' | 'phone'> | null;
  customer: Pick<Customer, 'id' | 'companyName'> | null;
  dispatcher: Pick<User, 'id' | 'firstName' | 'lastName'> | null;
  // Slim accessorial rows — amount only — to feed computeLoadFinancials in
  // the list transformer (US-11). Full rows are returned by the detail query.
  accessorialCharges: Pick<AccessorialCharge, 'amount'>[];
  _count: {
    accessorialCharges: number;
    invoices: number;
  };
}

// ---------------------------------------------------------------------------
// Result types
// ---------------------------------------------------------------------------

export interface ListLoadsResult {
  data: LoadListItem[];
  meta: PaginationMeta;
}

// ---------------------------------------------------------------------------
// Check call types
// ---------------------------------------------------------------------------

export interface CreateCheckCallInput {
  location?: string;
  latitude?: number;
  longitude?: number;
  status?: string;
  eta?: Date;
  notes?: string;
  brokerNotified: boolean;
  brokerNotes?: string;
}

export interface CheckCallWithUser {
  id: string;
  loadId: string;
  calledByUserId: string | null;
  location: string | null;
  latitude: unknown;
  longitude: unknown;
  status: string | null;
  eta: Date | null;
  brokerNotified: boolean;
  brokerNotes: string | null;
  notes: string | null;
  createdAt: Date;
  calledBy: { id: string; firstName: string; lastName: string } | null;
}

// ---------------------------------------------------------------------------
// Status history types
// ---------------------------------------------------------------------------

export interface StatusHistoryWithUser {
  id: string;
  loadId: string;
  fromStatus: string | null;
  toStatus: string;
  changedByUserId: string | null;
  notes: string | null;
  createdAt: Date;
  changedBy: { id: string; firstName: string; lastName: string } | null;
}

// ---------------------------------------------------------------------------
// Load document types
// ---------------------------------------------------------------------------

export interface LoadDocument {
  id: string;
  organizationId: string;
  loadId: string | null;
  type: string;
  fileName: string;
  fileSize: number | null;
  mimeType: string | null;
  uploadStatus: string;
  notes: string | null;
  createdAt: Date;
}

export interface LoadAssignmentInput {
  carrierId?: string | null;
  driverId?: string | null;
  vehicleId?: string | null;
  dispatcherUserId?: string | null;
}

export interface LoadAssignmentWarning {
  code: string;
  message: string;
  field?: string;
  detail?: string;
}

export interface AssignLoadResult {
  load: LoadWithRelations;
  warnings: LoadAssignmentWarning[];
}

// ---------------------------------------------------------------------------
// Repo port
// ---------------------------------------------------------------------------

export interface LoadRepoPort {
  create(
    organizationId: string,
    loadNumber: string,
    input: CreateLoadInput,
  ): Promise<LoadWithRelations>;
  findById(id: string, organizationId: string): Promise<LoadWithRelations | null>;
  findByIdUnscoped(id: string): Promise<LoadWithRelations | null>;
  list(input: ListLoadsRepositoryInput): Promise<LoadListItem[]>;
  count(input: LoadQueryInput): Promise<number>;
  update(id: string, input: UpdateLoadInput): Promise<LoadWithRelations>;
  findBlockingLoadIdsByDriver(
    driverId: string,
    statuses: readonly LoadStatus[],
    limit: number,
    excludeLoadId?: string,
  ): Promise<string[]>;
  findBlockingLoadIdsByVehicle(
    vehicleId: string,
    statuses: readonly LoadStatus[],
    limit: number,
    excludeLoadId?: string,
  ): Promise<string[]>;
  softDelete(id: string, deletedAt: Date): Promise<void>;
  createCheckCall(
    loadId: string,
    calledByUserId: string,
    input: CreateCheckCallInput,
  ): Promise<CheckCallWithUser>;
  listCheckCalls(loadId: string): Promise<CheckCallWithUser[]>;
  listStatusHistory(loadId: string): Promise<StatusHistoryWithUser[]>;
  listDocuments(loadId: string, organizationId: string): Promise<LoadDocument[]>;
  findLastDeliveryCoordinates(
    driverId: string,
    organizationId: string,
  ): Promise<{ lat: number; lng: number } | null>;
  findFirstPickupCoordinates(loadId: string): Promise<{ lat: number; lng: number } | null>;
}

// ---------------------------------------------------------------------------
// OrgSettings port (for prohibited commodities check)
// ---------------------------------------------------------------------------

export interface OrgSettingsQueryPort {
  getProhibitedCommodities(organizationId: string): Promise<string[]>;
}

export interface CarrierRateSnapshot {
  dispatchFeeType: DispatchFeeType;
  dispatchFeePercent: string;
  dispatchFeeAmount: string;
  partnerSplitPercent: string;
  feeIncludesAccessorials: boolean;
  payFromNet: boolean;
  carrierType: CarrierType;
}

export interface CarrierAssignmentQueryPort {
  findDispatchableById(
    carrierId: string,
    organizationId: string,
  ): Promise<{
    id: string;
    name: string;
    type: CarrierType;
    tinOnFile: boolean;
  } | null>;
  findRateSnapshot(
    carrierId: string,
    organizationId: string,
  ): Promise<CarrierRateSnapshot | null>;
}

export interface DriverRateSnapshot {
  payType: DriverPayType;
  payRate: string;
}

export interface DriverAssignmentQueryPort {
  findAssignableById(
    driverId: string,
    organizationId: string,
  ): Promise<{
    id: string;
    carrierId: string;
    firstName: string;
    lastName: string;
    isAvailable: boolean;
    licenseExpiry: Date | null;
  } | null>;
  findRateSnapshot(
    driverId: string,
    organizationId: string,
  ): Promise<DriverRateSnapshot | null>;
}

export interface VehicleAssignmentQueryPort {
  findAssignableById(
    vehicleId: string,
    organizationId: string,
  ): Promise<{
    id: string;
    carrierId: string;
    unitNumber: string;
    driverId: string | null;
    isActive: boolean;
    type: EquipmentType;
  } | null>;
}

export interface CustomerQueryPort {
  findById(id: string, organizationId: string): Promise<{ id: string } | null>;
}

export interface DispatcherProfileQueryPort {
  findByUserId(
    userId: string,
    organizationId: string,
  ): Promise<{
    commissionType: DispatcherCommType;
    commissionRate: string;
  } | null>;
}

export interface SettlementFreezeQueryPort {
  hasNonDraftSettlementForLoad(
    loadId: string,
    organizationId: string,
  ): Promise<boolean>;
}

// ---------------------------------------------------------------------------
// Response types (API → client)
// ---------------------------------------------------------------------------

export interface StopResponse {
  id: string;
  type: string;
  sequence: number;
  contactId: string | null;
  placeId: string | null;
  resolutionStatus: string;
  facilityName: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  lat: number | null;
  lng: number | null;
  schedulingType: string;
  appointmentStart: string;
  appointmentEnd: string | null;
  notificationHours: number | null;
  notifiedAt: string | null;
  appointmentNumber: string | null;
  arrivalTime: string | null;
  departureTime: string | null;
  contactName: string | null;
  contactPhone: string | null;
  commodity: string | null;
  weight: number | null;
  pieceCount: number | null;
  isHazmat: boolean;
  isTarp: boolean;
  isTempControlled: boolean;
  notes: string | null;
  callByTime: string | null;
  trailerNumber: string | null;
  yardLocation: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface AccessorialChargeResponse {
  id: string;
  type: string;
  description: string | null;
  amount: string;
  billTo: string;
  approvalStatus: string;
  stopId: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CheckCallResponse {
  id: string;
  location: string | null;
  latitude: number | null;
  longitude: number | null;
  status: string | null;
  eta: string | null;
  notes: string | null;
  brokerNotified: boolean;
  brokerNotes: string | null;
  calledByUserId: string | null;
  calledByName: string | null;
  createdAt: string;
}

export interface ContactResponse {
  id: string;
  firstName: string;
  lastName: string;
  role: string | null;
  phone: string | null;
  email: string | null;
}

export interface VehicleResponse {
  id: string;
  unitNumber: string;
  type: string;
}

export interface DriverResponse {
  id: string;
  firstName: string;
  lastName: string;
  phone: string | null;
  currentLatitude: number | null;
  currentLongitude: number | null;
}

export interface CarrierResponse {
  id: string;
  name: string;
  type: string;
  dispatchFeePercent: string;
  partnerSplitPercent: string;
  feeIncludesAccessorials: boolean;
  payFromNet: boolean;
}

export interface StatusHistoryResponse {
  id: string;
  fromStatus: string | null;
  toStatus: string;
  notes: string | null;
  changedByUserId: string | null;
  changedByName: string | null;
  createdAt: string;
}

export interface FinancialResponse {
  customerRate: string | null;
  carrierRate: string | null;
  dispatchFee: string | null;
  partnerSplit: string | null;
  ratePerMile: string | null;
  ratePerTotalMile: string | null;
  carrierPayout: string | null;
  companyMargin: string | null;
  driverPay: string | null;
  dispatcherComm: string | null;
  carrierRpm: string | null;
  companyNet: string | null;
  marginPercent: string | null;
  estimatedCost: string | null;
  estimatedNetEarnings: string | null;
  dispatchFeeType: DispatchFeeType | null;
  dispatchFeeAmount: string | null;
  partnerSplitPercent: string | null;
  driverPayType: DriverPayType | null;
  driverPayRate: string | null;
  dispatcherCommissionType: DispatcherCommType | null;
  dispatcherCommissionRate: string | null;
  feeIncludesAccessorials: boolean | null;
  payFromNet: boolean | null;
}

export interface RouteResponse {
  loadedMiles: number | null;
  deadheadMiles: number | null;
  totalMiles: number | null;
  estimatedHours: string | null;
  stops: StopResponse[];
}

export interface CargoResponse {
  commodity: string | null;
  weight: number | null;
  pieceCount: number | null;
  isHazmat: boolean;
  isTarp: boolean;
  isTempControlled: boolean;
}

export interface DispatcherResponse {
  id: string;
  firstName: string;
  lastName: string;
}

export interface AssignmentResponse {
  carrier: CarrierResponse | null;
  driver: DriverResponse | null;
  vehicle: VehicleResponse | null;
  dispatcher: DispatcherResponse | null;
  isTeamDriver: boolean;
}

export interface CustomerResponse {
  id: string;
  companyName: string;
}

export interface TrackingResponse {
  invoiceReadiness: string;
  rateConReceivedAt: string | null;
  bolUnsignedAt: string | null;
  bolSignedAt: string | null;
}

export interface ActivityResponse {
  statusHistory: StatusHistoryResponse[];
  checkCalls: CheckCallResponse[];
  accessorialCharges: AccessorialChargeResponse[];
}

export interface LoadDetailResponse {
  id: string;
  loadNumber: string;
  status: string;
  version: number;
  organizationId: string;
  externalRefNumber: string | null;
  equipmentType: string | null;
  dispatcherNotes: string | null;
  driverInstructions: string | null;
  createdAt: string;
  updatedAt: string;

  route: RouteResponse;
  cargo: CargoResponse;
  financials: FinancialResponse;
  assignment: AssignmentResponse;
  customer: CustomerResponse | null;
  contact: ContactResponse | null;
  tracking: TrackingResponse;
  activity: ActivityResponse;
}

// ---------------------------------------------------------------------------
// List item response — structural subset of LoadDetailResponse
// ---------------------------------------------------------------------------

export interface ListRouteResponse {
  totalMiles: number | null;
  stops: StopResponse[];
}

export interface ListCargoResponse {
  commodity: string | null;
  weight: number | null;
  pieceCount: number | null;
  isHazmat: boolean;
  isTarp: boolean;
}

export interface ListFinancialResponse {
  customerRate: string | null;
  carrierRate: string | null;
  ratePerMile: string | null;
  ratePerTotalMile: string | null;
  companyMargin: string | null;
  carrierPayout: string | null;
  companyNet: string | null;
}

export interface ListCarrierSummary {
  id: string;
  name: string;
}

export interface ListDriverSummary {
  id: string;
  firstName: string;
  lastName: string;
}

export interface ListAssignmentResponse {
  carrier: ListCarrierSummary | null;
  driver: ListDriverSummary | null;
  dispatcher: DispatcherResponse | null;
}

export interface ListContactResponse {
  id: string;
  firstName: string;
  lastName: string;
  email: string | null;
  phone: string | null;
}

export interface LoadListItemResponse {
  id: string;
  loadNumber: string;
  status: string;
  equipmentType: string | null;
  invoiceReadiness: string;
  accessorialChargeCount: number;
  createdAt: string;
  updatedAt: string;

  route: ListRouteResponse;
  cargo: ListCargoResponse;
  financials: ListFinancialResponse;
  assignment: ListAssignmentResponse;
  customer: CustomerResponse | null;
  contact: ListContactResponse | null;
}
