import { expect, test, type BrowserContext, type Page, type Route } from '@playwright/test';

// US-07 — SMS deep-link entry path coverage.
//
// The SMS prompt worker sends drivers a URL of the form
// `${trackingBaseUrl}/driver-portal/${token}` where `token` is a UUID-shaped
// value generated by trackingTokenService (DRIVER scope). The route matcher
// is the same `/driver-portal/:token` used everywhere else, but a "fresh
// landing" (cold mount, no prior state, real-shaped token) is the surface
// this spec exercises.
//
// Scope is intentionally narrow — auth states are owned by US-02, full load
// rendering by US-03, status transitions by US-04, check-in by US-05, and
// document upload by US-06. This spec only proves: a UUID-shaped deep-link
// hydrates the page and the page is interactive end-to-end on first mount.
//
// Scenarios (each runs at desktop + mobile via the playwright projects):
//  1. Deep-link landing renders load context (smoke)
//  2. Check-in submission from deep-linked landing
//  3. Status advance from deep-linked landing
//  4. Token format compatibility — UUID-shaped path param matches the route

interface MockStop {
  id: string;
  type: 'PICKUP' | 'DELIVERY';
  sequence: number;
  facilityName: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  appointmentStart: string | null;
  appointmentEnd: string | null;
  contactName: string | null;
  contactPhone: string | null;
  notes: string | null;
}

interface MockLoad {
  id: string;
  loadNumber: string;
  status: string;
  equipmentType: string | null;
  commodity: string | null;
  weight: number | null;
  driverInstructions: string | null;
  stops: MockStop[];
  driver: { firstName: string; lastName: string } | null;
}

// Realistic UUID v4 shape mirroring trackingTokenService output.
const SMS_TOKEN = '7e8d9c3a-1234-4abc-9def-0123456789ab';

const fulfillJson = async (
  route: Route,
  status: number,
  body: Record<string, unknown>,
): Promise<void> => {
  await route.fulfill({
    status,
    contentType: 'application/json',
    body: JSON.stringify(body),
  });
};

const buildLoad = (status: string): MockLoad => ({
  id: 'load-sms-1',
  loadNumber: 'LD-2026-SMS1',
  status,
  equipmentType: 'DRY_VAN',
  commodity: 'General Freight',
  weight: 25000,
  driverInstructions: null,
  stops: [
    {
      id: 'pickup-1',
      type: 'PICKUP',
      sequence: 1,
      facilityName: 'ACME Warehouse',
      address: '123 Main St',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      appointmentStart: '2026-04-26T14:00:00.000Z',
      appointmentEnd: '2026-04-26T16:00:00.000Z',
      contactName: 'John Smith',
      contactPhone: '5551234567',
      notes: null,
    },
    {
      id: 'delivery-1',
      type: 'DELIVERY',
      sequence: 2,
      facilityName: 'Beta Receiving',
      address: '900 Commerce St',
      city: 'Houston',
      state: 'TX',
      zip: '77002',
      appointmentStart: '2026-04-27T20:00:00.000Z',
      appointmentEnd: '2026-04-27T22:00:00.000Z',
      contactName: 'Mary Jones',
      contactPhone: '5559876543',
      notes: null,
    },
  ],
  driver: { firstName: 'Jane', lastName: 'Doe' },
});

const attachConsoleErrorWatcher = (page: Page): string[] => {
  const errors: string[] = [];
  page.on('console', (message) => {
    if (message.type() === 'error') {
      errors.push(message.text());
    }
  });
  page.on('pageerror', (err) => {
    errors.push(err.message);
  });
  return errors;
};

interface LoadEndpointController {
  advance: () => void;
  getCallCount: () => number;
}

const installLoadEndpointSequence = async (
  page: Page,
  statuses: string[],
): Promise<LoadEndpointController> => {
  let stageIndex = 0;
  let callCount = 0;
  await page.route('**/api/v1/driver-portal/portal/load*', async (route) => {
    if (route.request().method() !== 'GET') {
      await route.fallback();
      return;
    }
    const status = statuses[Math.min(stageIndex, statuses.length - 1)];
    callCount += 1;
    await fulfillJson(route, 200, { data: buildLoad(status) });
  });
  return {
    advance: () => {
      stageIndex += 1;
    },
    getCallCount: () => callCount,
  };
};

const installCheckInEndpoint = async (
  page: Page,
  responder?: (route: Route) => Promise<void>,
): Promise<void> => {
  await page.route('**/api/v1/driver-portal/portal/load/check-in*', async (route) => {
    if (responder) {
      await responder(route);
      return;
    }
    await fulfillJson(route, 200, { data: { success: true } });
  });
};

const installStatusEndpoint = async (
  page: Page,
  responder: (route: Route) => Promise<void>,
): Promise<void> => {
  await page.route('**/api/v1/driver-portal/portal/load/status*', responder);
};

const grantGeolocation = async (
  context: BrowserContext,
  latitude: number,
  longitude: number,
): Promise<void> => {
  await context.grantPermissions(['geolocation'], { origin: 'http://localhost:5173' });
  await context.setGeolocation({ latitude, longitude });
};

const screenshotPath = (page: Page, name: string): string => {
  const viewport = page.viewportSize()?.width ?? 0;
  const label = viewport >= 1000 ? 'desktop' : 'mobile';
  return `e2e-results/screenshots/sms-deep-link-${name}-${label}.png`;
};

test.describe('Driver portal SMS deep-link entry', () => {
  test.beforeEach(async ({ context }) => {
    await context.clearPermissions();
  });

  test('UUID-shaped deep-link landing renders load context', async ({ page }) => {
    const consoleErrors = attachConsoleErrorWatcher(page);

    const loadEndpoint = await installLoadEndpointSequence(page, ['DISPATCHED']);
    await installCheckInEndpoint(page);
    await installStatusEndpoint(page, async (route) => {
      // Should not be called for a passive landing.
      await fulfillJson(route, 500, { errors: [{ message: 'should not be called' }] });
    });

    // Cold navigation to the SMS-style URL — exactly what a driver tapping
    // the SMS link would see.
    await page.goto(`/driver-portal/${SMS_TOKEN}`);

    // Page hydrated: load number, status chip, and driver greeting all
    // present. We do not deeply assert stops — that is US-03's job.
    await expect(page.getByRole('heading', { name: /Load LD-2026-SMS1/ })).toBeVisible({
      timeout: 15000,
    });
    await expect(page.getByText('Dispatched', { exact: true })).toBeVisible();
    await expect(page.getByText(/Hi Jane,/)).toBeVisible();

    // The page should have called GET /load* at least once after mount.
    expect(loadEndpoint.getCallCount()).toBeGreaterThan(0);

    await page.screenshot({ path: screenshotPath(page, 'landing'), fullPage: true });

    expect(
      consoleErrors,
      `console errors during deep-link landing: ${consoleErrors.join(' | ')}`,
    ).toEqual([]);
  });

  test('check-in submission from deep-linked landing succeeds', async ({ page, context }) => {
    const consoleErrors = attachConsoleErrorWatcher(page);
    // Deny geolocation so the check-in body is purely notes-driven (no
    // entanglement with GPS shape — that is US-05's domain).
    await context.clearPermissions();

    await installLoadEndpointSequence(page, ['DISPATCHED']);
    let checkInBody: string | null = null;
    await installCheckInEndpoint(page, async (route) => {
      checkInBody = route.request().postData();
      await fulfillJson(route, 200, { data: { success: true } });
    });

    await page.goto(`/driver-portal/${SMS_TOKEN}`);

    const submitBtn = page.getByRole('button', { name: 'Submit Note', exact: true });
    await expect(submitBtn).toBeVisible({ timeout: 15000 });

    const note = 'Arrived at terminal lot, prepping for pickup.';
    await page.getByPlaceholder('Enter notes or ETA update...').fill(note);
    await submitBtn.click();

    await expect.poll(() => checkInBody, { timeout: 20000 }).not.toBeNull();
    const parsed: { notes?: string } = checkInBody !== null ? JSON.parse(checkInBody) : {};
    expect(parsed.notes).toBe(note);

    await expect(page.getByRole('alert').filter({ hasText: /Note submitted/i })).toBeVisible({
      timeout: 15000,
    });

    await page.screenshot({ path: screenshotPath(page, 'post-check-in'), fullPage: true });

    expect(
      consoleErrors,
      `console errors during check-in: ${consoleErrors.join(' | ')}`,
    ).toEqual([]);
  });

  test('status advance from deep-linked landing succeeds', async ({ page, context }) => {
    const consoleErrors = attachConsoleErrorWatcher(page);
    const lat = 39.7392;
    const lng = -104.9903;
    await grantGeolocation(context, lat, lng);

    const loadEndpoint = await installLoadEndpointSequence(page, [
      'DISPATCHED',
      'EN_ROUTE_PICKUP',
    ]);

    let statusBody: string | null = null;
    await installStatusEndpoint(page, async (route) => {
      statusBody = route.request().postData();
      loadEndpoint.advance();
      await fulfillJson(route, 200, {
        data: { success: true, status: 'EN_ROUTE_PICKUP' },
      });
    });

    await installCheckInEndpoint(page);

    await page.goto(`/driver-portal/${SMS_TOKEN}`);

    const advanceBtn = page.getByRole('button', { name: 'Start Route to Pickup', exact: true });
    await expect(advanceBtn).toBeVisible({ timeout: 15000 });
    await advanceBtn.click();

    await expect.poll(() => statusBody, { timeout: 20000 }).not.toBeNull();
    const parsed: { status?: string } = statusBody !== null ? JSON.parse(statusBody) : {};
    expect(parsed.status).toBe('EN_ROUTE_PICKUP');

    // UI reflects new status after re-fetch.
    await expect(page.getByText('En Route to Pickup', { exact: true })).toBeVisible({
      timeout: 15000,
    });

    await page.screenshot({ path: screenshotPath(page, 'post-status-advance'), fullPage: true });

    expect(
      consoleErrors,
      `console errors during status advance: ${consoleErrors.join(' | ')}`,
    ).toEqual([]);
  });

  test('UUID v4 token shape is matched by the route', async ({ page }) => {
    const consoleErrors = attachConsoleErrorWatcher(page);

    let observedRequestUrl: string | null = null;
    await page.route('**/api/v1/driver-portal/portal/load*', async (route) => {
      if (route.request().method() !== 'GET') {
        await route.fallback();
        return;
      }
      // The portal API client forwards the token via the `?token=` query
      // param (see driverPortalApi.createDriverPortalAxios). Capture the
      // full URL and assert the UUID survived route matching + extraction
      // intact (no truncation on hyphens, no segment splitting).
      observedRequestUrl = route.request().url();
      await fulfillJson(route, 200, { data: buildLoad('DISPATCHED') });
    });
    await installCheckInEndpoint(page);

    await page.goto(`/driver-portal/${SMS_TOKEN}`);

    // Page hydrated -> the route matched the UUID-shaped token without
    // truncation or mis-segmentation on the hyphens.
    await expect(page.getByRole('heading', { name: /Load LD-2026-SMS1/ })).toBeVisible({
      timeout: 15000,
    });

    // The token must reach the API exactly as it appeared in the URL.
    await expect.poll(() => observedRequestUrl, { timeout: 15000 }).not.toBeNull();
    expect(observedRequestUrl).toContain(`token=${SMS_TOKEN}`);

    expect(
      consoleErrors,
      `console errors during UUID token compatibility test: ${consoleErrors.join(' | ')}`,
    ).toEqual([]);
  });
});
